const RELEASE='52.2.0';
const SUPABASE_ORIGIN='https://mpcelmjiycjpdyyflisn.supabase.co';
const API_PREFIXES=['/auth/v1/','/functions/v1/','/rest/v1/','/storage/v1/'];
const ROUTES=new Map([['/access','/access.html'],['/member','/member.html'],['/owner','/owner.html'],['/live-markets','/live-markets.html'],['/gold-live','/gold-live.html'],['/intelligence','/intelligence.html'],['/status','/status.html'],['/privacy','/privacy.html'],['/terms','/terms.html'],['/visual-lab','/visual-lab.html']]);
const PRIVATE_ROUTES=new Set(['/member','/owner']);
function securityHeaders(headers,pathname){const h=new Headers(headers);h.set('X-Content-Type-Options','nosniff');h.set('Referrer-Policy','strict-origin-when-cross-origin');h.set('Permissions-Policy','camera=(), microphone=(), geolocation=()');h.set('X-Frame-Options','DENY');h.set('Cross-Origin-Opener-Policy','same-origin');if(pathname.endsWith('.html')||ROUTES.has(pathname)||pathname==='/')h.set('Content-Security-Policy',"default-src 'self'; script-src 'self' https://esm.sh; connect-src 'self' https://checkout.flutterwave.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self' https://checkout.flutterwave.com; upgrade-insecure-requests");if(PRIVATE_ROUTES.has(pathname)){h.set('Cache-Control','no-store, max-age=0');h.set('Pragma','no-cache');h.set('X-Robots-Tag','noindex, nofollow')}if(pathname==='/access'||pathname==='/status')h.set('X-Robots-Tag','noindex, nofollow');return h}
function publicLocation(raw,publicOrigin){if(!raw)return raw;try{const u=new URL(raw,SUPABASE_ORIGIN);if(u.origin===SUPABASE_ORIGIN&&API_PREFIXES.some(p=>u.pathname.startsWith(p)))return `${publicOrigin}${u.pathname}${u.search}${u.hash}`}catch{}return raw}
async function proxy(request,url){const upstream=new URL(url.pathname+url.search,SUPABASE_ORIGIN),headers=new Headers(request.headers);headers.set('X-Forwarded-Host',url.host);headers.set('X-Forwarded-Proto','https');for(const name of ['Host','Content-Length','CF-Connecting-IP','CF-Ray','CF-Visitor','CF-IPCountry'])headers.delete(name);const init={method:request.method,headers,redirect:'manual'};if(!['GET','HEAD'].includes(request.method))init.body=request.body;const response=await fetch(upstream.toString(),init),out=new Headers(response.headers);const location=out.get('Location');if(location)out.set('Location',publicLocation(location,url.origin));out.set('X-TFA-Gateway',`cloudflare-v${RELEASE}`);out.set('Vary','Origin, Accept-Encoding');out.delete('Server');if(url.pathname.startsWith('/auth/v1/')){out.set('Cache-Control','no-store, max-age=0');out.set('Pragma','no-cache')}return new Response(response.body,{status:response.status,statusText:response.statusText,headers:out})}
function health(url){return Response.json({ok:true,app:'THE FATHER ANALYTICS',gateway_version:RELEASE,gateway:'same-origin-supabase-proxy',host:url.host,auth_proxy:true,functions_proxy:true,provider_rate_limit:'UNVERIFIED_EXTERNALLY',generated_at:new Date().toISOString()},{headers:{'Cache-Control':'no-store','X-TFA-Gateway':`cloudflare-v${RELEASE}`}})}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/__tfa/health')return health(url);if(API_PREFIXES.some(prefix=>url.pathname.startsWith(prefix)))return proxy(request,url);const mapped=ROUTES.get(url.pathname),assetURL=mapped?new URL(mapped+url.search,url.origin):url,assetReq=new Request(assetURL.toString(),request),response=await env.ASSETS.fetch(assetReq);return new Response(response.body,{status:response.status,statusText:response.statusText,headers:securityHeaders(response.headers,url.pathname)})}};
