import{createClient}from'https://esm.sh/@supabase/supabase-js@2.57.4';
import{SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,BASE,api,gatewayHealth,esc,fmtDate,stateClass}from'./common.js?v=52.2.0';
const $=id=>document.getElementById(id),authBox=$('authBox'),memberBox=$('memberBox'),msg=$('authMessage'),signOut=$('signOut'),ownerLink=$('ownerLink');let recovery=false,caps=null;
function guardedFetch(input,init={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);if(init.signal)init.signal.addEventListener('abort',()=>c.abort(),{once:true});return fetch(input,{...init,signal:c.signal}).finally(()=>clearTimeout(timer))}
const sb=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{global:{fetch:guardedFetch},auth:{persistSession:true,detectSessionInUrl:true,autoRefreshToken:true}});
function note(t,k=''){msg.textContent=t;msg.className=`notice ${k}`.trim();msg.classList.remove('hidden')}function hideNote(){msg.classList.add('hidden');msg.textContent=''}
function mode(m){for(const id of['signInForm','signUpForm','forgotForm','resetForm'])$(id).classList.toggle('hidden',id!==({signin:'signInForm',signup:'signUpForm',forgot:'forgotForm',reset:'resetForm'}[m]));$('tabSignIn').classList.toggle('active',m==='signin');$('tabSignUp').classList.toggle('active',m==='signup');hideNote()}
async function explainAuthFailure(err){const h=await gatewayHealth();if(!h.ok)return `Access gateway unavailable (${h.error||'network'}). Your password was not retried.`;if(err?.name==='AbortError')return 'Authentication timed out. No automatic retry was sent.';if(/failed to fetch|network/i.test(String(err?.message||'')))return 'Authentication network request failed. The gateway itself is reachable, so retry once after checking your connection.';return err?.message||'Sign in failed.'}
async function authed(name){const{data:{session}}=await sb.auth.getSession();if(!session)throw new Error('Sign in required');const r=await guardedFetch(`${BASE}/${name}`,{headers:{Authorization:`Bearer ${session.access_token}`,apikey:SUPABASE_PUBLISHABLE_KEY,Accept:'application/json'}}),j=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(j.error||`${name} ${r.status}`),{status:r.status});return j}
async function loadCaps(){try{caps=await api('public-auth-capabilities',{ttl:120000});$('authCapabilityLine').textContent=`Email/password ${caps.password_sign_in?'ready':'off'} · sign up ${caps.signup_enabled?'open':'closed'} · recovery ${caps.password_reset?'ready':'off'} · Google ${caps.google_enabled?'ready':'setup pending'}`;$('googleBtn').disabled=!caps.google_enabled;$('googleLabel').textContent=caps.google_enabled?'Continue with Google':'Google setup pending'}catch{$('authCapabilityLine').textContent='Capability check delayed. Email/password sign-in remains available.';$('googleBtn').disabled=true}}
$('tabSignIn').onclick=()=>mode('signin');$('tabSignUp').onclick=()=>mode('signup');$('forgotBtn').onclick=()=>{$('forgotEmail').value=$('signInEmail').value.trim();mode('forgot')};$('backSignIn').onclick=()=>mode('signin');$('togglePassword').onclick=()=>{const p=$('signInPassword');p.type=p.type==='password'?'text':'password';$('togglePassword').textContent=p.type==='password'?'Show':'Hide'};
$('signInForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;b.textContent='Signing in…';hideNote();try{const{error}=await sb.auth.signInWithPassword({email:$('signInEmail').value.trim(),password:$('signInPassword').value});if(error)throw error;note('Authenticated. Opening Member Command…','success');await load()}catch(err){note(await explainAuthFailure(err),'error')}finally{b.disabled=false;b.textContent='Sign in'}};
$('signUpForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter,p=$('signUpPassword').value;if(p!==$('signUpConfirm').value)return note('Passwords do not match.','error');if(p.length<12)return note('Use at least 12 characters.','error');if(!$('termsConsent').checked)return note('Accept the Terms and Privacy Policy.','error');b.disabled=true;b.textContent='Creating…';try{const{data,error}=await sb.auth.signUp({email:$('signUpEmail').value.trim(),password:p,options:{emailRedirectTo:`${location.origin}/member`,data:{full_name:$('signUpName').value.trim()||undefined}}});if(error)throw error;note(data.session?'Account created and signed in.':'Account created. Check your email if confirmation is required.','success');if(data.session)await load()}catch(err){note(await explainAuthFailure(err),'error')}finally{b.disabled=false;b.textContent='Create account'}};
$('forgotForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;b.textContent='Sending…';try{const{error}=await sb.auth.resetPasswordForEmail($('forgotEmail').value.trim(),{redirectTo:`${location.origin}/member?mode=reset`});if(error)throw error;note('If the account exists, a recovery email has been sent.','success')}catch(err){note(await explainAuthFailure(err),'error')}finally{b.disabled=false;b.textContent='Send reset link'}};
$('resetForm').onsubmit=async e=>{e.preventDefault();const p=$('resetPassword').value;if(p!==$('resetConfirm').value)return note('Passwords do not match.','error');if(p.length<12)return note('Use at least 12 characters.','error');const b=e.submitter;b.disabled=true;b.textContent='Updating…';try{const{error}=await sb.auth.updateUser({password:p});if(error)throw error;recovery=false;history.replaceState({},'',location.pathname);note('Password updated.','success');await load()}catch(err){note(await explainAuthFailure(err),'error')}finally{b.disabled=false;b.textContent='Update password'}};
$('googleBtn').onclick=async()=>{if(!caps?.google_enabled)return note('Google provider is not enabled yet.','error');const{error}=await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${location.origin}/member`}});if(error)note(await explainAuthFailure(error),'error')};
signOut.onclick=async()=>{await sb.auth.signOut();location.replace('/member')};
async function load(){const{data:{session}}=await sb.auth.getSession();if(!session){authBox.classList.remove('hidden');memberBox.classList.add('hidden');signOut.classList.add('hidden');ownerLink.classList.add('hidden');if(!recovery)mode('signin');return}if(recovery){authBox.classList.remove('hidden');memberBox.classList.add('hidden');signOut.classList.remove('hidden');mode('reset');return}try{const s=await authed('member-session');authBox.classList.add('hidden');memberBox.classList.remove('hidden');signOut.classList.remove('hidden');ownerLink.classList.toggle('hidden',!s.is_owner);$('hello').textContent=`Welcome${s.profile?.full_name?' '+s.profile.full_name:''}`;$('planPill').textContent=String(s.access_label||s.subscription?.plan_name||'Free').toUpperCase();$('planPill').className='pill '+stateClass(s.access_state);$('memberGrid').innerHTML=`<article class="card"><div class="kicker">ACCESS</div><div class="metric">${esc(String(s.access_state||'limited').toUpperCase())}</div><p class="muted">${s.is_owner?'Owner account verified server-side.':'Entitlements follow the subscription ledger.'}</p></article><article class="card"><div class="kicker">PLAN</div><div class="metric">${esc(s.subscription?.plan_name||'Free')}</div><p class="muted">${esc(s.subscription?.status||'inactive')} · ${s.subscription?.current_period_end?'through '+esc(fmtDate(s.subscription.current_period_end)):'no paid period'}</p></article><article class="card"><div class="kicker">EMAIL</div><div class="metric">${s.user?.email_confirmed_at?'CONFIRMED':'PENDING'}</div><p class="muted">Supabase Auth session verified through the access gateway.</p></article>`}catch(err){if(err.status===401){await sb.auth.signOut();return load()}note(`Member session unavailable: ${err.message}`,'error')}}
sb.auth.onAuthStateChange(event=>{if(event==='PASSWORD_RECOVERY'){recovery=true;setTimeout(()=>{mode('reset');load()},0)}else setTimeout(load,0)});
await loadCaps();const requestedMode=new URLSearchParams(location.search).get('mode');if(requestedMode==='signup')mode('signup');if(requestedMode==='forgot'){const qEmail=new URLSearchParams(location.search).get('email');if(qEmail)$('forgotEmail').value=qEmail;mode('forgot')}if(requestedMode==='reset')recovery=true;await load();
