import{createClient}from'https://esm.sh/@supabase/supabase-js@2.57.4';
import{SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,BASE,esc,stateClass}from'./common.js?v=52.1.0';
const sb=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,detectSessionInUrl:true,autoRefreshToken:true}}),$=id=>document.getElementById(id);let factorId='';
function show(id){for(const x of['ownerAuth','mfaBox','ownerPanel'])$(x).classList.toggle('hidden',x!==id)}function note(t,k=''){const e=$('ownerMessage');e.textContent=t;e.className=`notice ${k}`.trim();e.classList.remove('hidden')}async function session(){return(await sb.auth.getSession()).data.session}
async function get(name){const s=await session();if(!s)throw Object.assign(new Error('NO_SESSION'),{status:401});const r=await fetch(`${BASE}/${name}`,{headers:{Authorization:`Bearer ${s.access_token}`,apikey:SUPABASE_PUBLISHABLE_KEY,Accept:'application/json'}}),j=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(j.error||`${name} ${r.status}`),{status:r.status});return j}
async function post(name,body){const s=await session();if(!s)throw Object.assign(new Error('NO_SESSION'),{status:401});const r=await fetch(`${BASE}/${name}`,{method:'POST',headers:{Authorization:`Bearer ${s.access_token}`,apikey:SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)throw Object.assign(new Error(j.error||`${name} ${r.status}`),{status:r.status,data:j});return j}
$('ownerLogin').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;b.textContent='Signing in…';try{const{error}=await sb.auth.signInWithPassword({email:$('ownerEmail').value.trim(),password:$('ownerPassword').value});if(error)throw error;await boot()}catch(err){note(err.message||'Owner sign-in failed.','error')}finally{b.disabled=false;b.textContent='Sign in'}};
$('ownerSignOut').onclick=async()=>{await sb.auth.signOut();location.replace('/owner')};
$('mfaEnrollBtn').onclick=async()=>{const b=$('mfaEnrollBtn');b.disabled=true;try{const o=await post('owner-mfa-actions',{action:'enroll'});factorId=o.factor_id||'';const t=o.totp||{};$('mfaQr').classList.remove('hidden');$('mfaQr').innerHTML=`${t.qr_code?`<img src="${esc(t.qr_code)}" alt="Authenticator QR" style="max-width:220px">`:''}<p class="muted">${t.secret?'Manual secret: <code>'+esc(t.secret)+'</code>':'Scan the QR code with your authenticator app.'}</p>`;$('mfaEnroll').classList.add('hidden');$('mfaForm').classList.remove('hidden')}catch(err){$('mfaMessage').classList.remove('hidden');$('mfaMessage').textContent=err.message||'MFA enrollment failed'}finally{b.disabled=false}};
$('mfaForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const o=await post('owner-mfa-actions',{action:'verify',factor_id:factorId||undefined,code:$('mfaCode').value.trim()});const s=o.session||o;if(!s.access_token||!s.refresh_token)throw new Error('Verified MFA session was not returned');const{error}=await sb.auth.setSession({access_token:s.access_token,refresh_token:s.refresh_token});if(error)throw error;await boot()}catch(err){$('mfaMessage').classList.remove('hidden');$('mfaMessage').textContent=err.message||'MFA verification failed'}finally{b.disabled=false}};
async function boot(){const s=await session();if(!s){show('ownerAuth');$('ownerSignOut').classList.add('hidden');return}$('ownerSignOut').classList.remove('hidden');try{const m=await get('member-session');if(!m.is_owner){show('ownerAuth');return note('This authenticated account is not authorized for Owner Command.','error')}const sec=await get('owner-security-status');if(!sec.mfa_enrolled||!sec.mfa_session_verified){show('mfaBox');$('mfaPill').textContent=sec.mfa_enrolled?'MFA VERIFY':'MFA ENROLL';const st=await post('owner-mfa-actions',{action:'status'});factorId=st.factors?.[0]?.id||'';$('mfaEnroll').classList.toggle('hidden',!!factorId);$('mfaForm').classList.toggle('hidden',!factorId);return}const [launch,commercial]=await Promise.all([get('owner-launch-control'),get('owner-commercial-status')]);show('ownerPanel');const ready=launch.build_ready===true;$('ownerPill').textContent=ready?'BUILD READY':'ATTENTION';$('ownerPill').className='pill '+stateClass(ready?'READY':'CHECK');$('ownerGrid').innerHTML=`<article class="card"><div class="kicker">PLATFORM</div><div class="metric">${launch.platform?.operational?'READY':'CHECK'}</div><p class="muted">Decision ${launch.platform?.decision_ready?'ready':'wait'} · ${esc(launch.platform?.capital_permission||'0R')}</p></article><article class="card"><div class="kicker">BILLING</div><div class="metric">${commercial.billing?.ready?'READY':'CHECK'}</div><p class="muted">Live payment ${commercial.acceptance?.first_real_payment_verified?'verified':'pending'}.</p></article><article class="card"><div class="kicker">SECURITY</div><div class="metric">AAL2</div><p class="muted">Owner allowlist and MFA verified server-side.</p></article>`}catch(err){if(err.status===401){await sb.auth.signOut();show('ownerAuth');return}note(`Owner Command unavailable: ${err.message}`,'error');show('ownerAuth')}}
sb.auth.onAuthStateChange(()=>setTimeout(boot,0));await boot();
