const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type, x-tfa-cron-secret","Access-Control-Allow-Methods":"POST, OPTIONS"};
function serverKey(){const b=Deno.env.get('SUPABASE_SECRET_KEYS');if(b){try{const p=JSON.parse(b);if(p?.default)return p.default}catch{}}const k=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!k)throw new Error('server key unavailable');return k}
async function sha256Hex(s:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function restUrl(base:string,table:string,params:Record<string,string>={}){const u=new URL(`${base}/rest/v1/${table}`);for(const[k,v]of Object.entries(params))u.searchParams.set(k,v);return u}
async function rows(base:string,key:string,table:string,params:Record<string,string>={}){const r=await fetch(restUrl(base,table,params),{headers:{apikey:key,Authorization:`Bearer ${key}`,Accept:'application/json'},signal:AbortSignal.timeout(2500)});if(!r.ok)throw new Error(`${table} ${r.status}`);return r.json()}
async function patch(base:string,key:string,id:string,body:any){const r=await fetch(restUrl(base,'transactional_email_outbox',{id:`eq.${id}`}),{method:'PATCH',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(body),signal:AbortSignal.timeout(2500)});if(!r.ok)throw new Error(`outbox patch ${r.status}`)}
function esc(v:any){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c] as string))}
function money(v:any,c:any){const n=Number(v);return Number.isFinite(n)?`${esc(c||'USD')} ${n.toFixed(2)}`:''}
function render(item:any){const p=item.payload||{};let heading='THE FATHER ANALYTICS';let body='';let cta='Open Member Command';let href=p.link||'https://thefatheranalytics.com/member';
 if(item.template_key==='support_reply'){heading='Support reply received';body=`<p>We replied to <strong>${esc(p.ticket_subject||'your support request')}</strong>.</p><p>${esc(p.message_preview||'Open Member Command to view the full reply.')}</p>`;cta='View support reply'}
 else if(item.template_key==='payment_receipt'){heading='Payment received';body=`<p>Your payment has been received successfully.</p><p><strong>${money(p.amount,p.currency)}</strong>${p.plan_id?` · ${esc(String(p.plan_id).toUpperCase())}`:''}</p>`;cta='View billing'}
 else if(item.template_key==='subscription_update'){heading='Subscription updated';body=`<p>Your THE FATHER ANALYTICS subscription has been updated.</p><p><strong>Plan:</strong> ${esc(p.plan_id||'')}<br><strong>Status:</strong> ${esc(p.status||'')}${p.current_period_end?`<br><strong>Period end:</strong> ${esc(new Date(p.current_period_end).toUTCString())}`:''}</p>`;cta='Manage subscription'}
 else {body='<p>You have a new account notification.</p>'}
 const html=`<!doctype html><html><body style="margin:0;background:#0b0712;color:#f7f3ff;font-family:Arial,Helvetica,sans-serif"><div style="max-width:620px;margin:0 auto;padding:40px 24px"><div style="letter-spacing:.16em;font-weight:700;font-size:14px">THE FATHER ANALYTICS</div><div style="color:#79f2b0;font-size:12px;letter-spacing:.18em;margin-top:8px">INTELLIGENCE BEFORE DECISIONS</div><div style="margin-top:34px;padding:30px;border:1px solid #33283f;border-radius:22px;background:#140d1e"><h1 style="font-size:30px;margin:0 0 18px">${esc(heading)}</h1>${body}<a href="${esc(href)}" style="display:inline-block;margin-top:22px;padding:14px 18px;border-radius:12px;background:#f7f3ff;color:#0b0712;text-decoration:none;font-weight:700">${esc(cta)}</a></div><p style="color:#92889d;font-size:12px;line-height:1.6;margin-top:24px">THE FATHER ANALYTICS · thefatheranalytics.com</p></div></body></html>`;
 const text=`THE FATHER ANALYTICS\n${heading}\n\n${String((body||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim())}\n\n${cta}: ${href}`;return{html,text}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return Response.json({ok:false,error:'method_not_allowed'},{status:405,headers:cors});const base=Deno.env.get('SUPABASE_URL');if(!base)return Response.json({ok:false,error:'server_not_configured'},{status:503,headers:cors});const key=serverKey();try{const supplied=req.headers.get('x-tfa-cron-secret')||'';if(!supplied)return Response.json({ok:false,error:'unauthorized'},{status:401,headers:cors});const tok=await rows(base,key,'runtime_tokens',{select:'token_hash',name:'eq.ingestion_cron',active:'eq.true',limit:'1'});if(!tok?.[0]?.token_hash||(await sha256Hex(supplied))!==tok[0].token_hash)return Response.json({ok:false,error:'unauthorized'},{status:401,headers:cors});const resend=Deno.env.get('RESEND_API_KEY');const from=Deno.env.get('BRANDED_EMAIL_FROM');const replyTo=Deno.env.get('BRANDED_EMAIL_REPLY_TO')||undefined;if(!resend||!from)return Response.json({ok:false,error:'email_provider_not_configured',required:['RESEND_API_KEY','BRANDED_EMAIL_FROM']},{status:503,headers:cors});const items=await rows(base,key,'transactional_email_outbox',{select:'id,recipient_email,subject,template_key,payload,attempts,status',status:'in.(queued,retry)',scheduled_at:`lte.${new Date().toISOString()}`,order:'created_at.asc',limit:'20'});let sent=0,retried=0,failed=0;for(const item of items){const attempts=Number(item.attempts||0)+1;await patch(base,key,item.id,{status:'sending',attempts,updated_at:new Date().toISOString()});try{const rendered=render(item);const payload:any={from,to:[item.recipient_email],subject:item.subject,html:rendered.html,text:rendered.text};if(replyTo)payload.reply_to=replyTo;const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${resend}`,'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(5000)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`resend_${r.status}:${JSON.stringify(data).slice(0,300)}`);await patch(base,key,item.id,{status:'sent',provider:'resend',provider_message_id:data.id||null,sent_at:new Date().toISOString(),last_error:null,updated_at:new Date().toISOString()});sent++}catch(e){const final=attempts>=5;const delay=Math.min(3600,Math.pow(2,attempts)*60);await patch(base,key,item.id,{status:final?'failed':'retry',scheduled_at:new Date(Date.now()+delay*1000).toISOString(),last_error:String(e).slice(0,1000),updated_at:new Date().toISOString()});if(final)failed++;else retried++}}
 return Response.json({ok:true,version:'transactional_email_v3_1_fail_fast',provider:'resend',processed:items.length,sent,retried,failed},{headers:{...cors,'Cache-Control':'no-store','X-TFA-Recovery':'FAIL_FAST_DB'}})}catch(e){return Response.json({ok:false,error:'dispatch_failed',state:'FAIL_CLOSED',detail:String(e).slice(0,300)},{status:503,headers:{...cors,'Cache-Control':'no-store','X-TFA-Recovery':'FAIL_FAST_DB'}})}});