import "jsr:@supabase/functions-js/edge-runtime.d.ts";
function key(){const b=Deno.env.get('SUPABASE_SECRET_KEYS');if(b){try{const p=JSON.parse(b);if(p?.default)return p.default}catch{}}const k=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!k)throw new Error('server key unavailable');return k}
async function sha256Hex(input:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(input));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,'0')).join('')}
function url(base:string,table:string,params:Record<string,string>={}){const u=new URL(`${base}/rest/v1/${table}`);for(const[k,v]of Object.entries(params))u.searchParams.set(k,v);return u}
async function rows(base:string,k:string,table:string,params:Record<string,string>){const r=await fetch(url(base,table,params),{headers:{apikey:k,Authorization:`Bearer ${k}`,Accept:'application/json'},signal:AbortSignal.timeout(2500)});if(!r.ok)throw new Error(`${table} ${r.status}: ${await r.text()}`);return r.json()}
async function insert(base:string,k:string,table:string,body:any){const r=await fetch(url(base,table),{method:'POST',headers:{apikey:k,Authorization:`Bearer ${k}`,'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(body),signal:AbortSignal.timeout(2500)});if(!r.ok)throw new Error(`${table} insert ${r.status}: ${await r.text()}`);return r.json()}
function horizonStatus(f:any,s:any){if(!f||!s)return 'PENDING';if(f.directional_correct===true&&s.directional_correct===true)return 'AGREE_WIN';if(f.directional_correct===false&&s.directional_correct===false)return 'AGREE_LOSS';return 'DIVERGE'}
const VERSION='finalize-gold-signal-resolution-v4_1-fail-fast';
Deno.serve(async(req:Request)=>{if(req.method!=='POST')return new Response('method not allowed',{status:405});try{const base=Deno.env.get('SUPABASE_URL')!,k=key(),supplied=req.headers.get('x-tfa-cron-secret')||'';if(!supplied)return new Response('unauthorized',{status:401});const token=await rows(base,k,'runtime_tokens',{select:'token_hash',name:'eq.ingestion_cron',active:'eq.true',limit:'1'});if(!token?.[0]?.token_hash||token[0].token_hash!==await sha256Hex(supplied))return new Response('unauthorized',{status:401});
const [pols,s1s,f1s]=await Promise.all([
 rows(base,k,'gold_resolution_policies',{select:'policy_version,t60_grace_minutes,require_fresh_f1,require_valid_s1,allow_data_quality_terminal',active:'eq.true',order:'created_at.desc',limit:'1'}),
 rows(base,k,'gold_spot_signal_events',{select:'id,snapshot_id,signaled_at,signal_direction,start_spot_price,futures_price,engine_state,confidence_pct,capital_permission',order:'signaled_at.desc',limit:'1'}),
 rows(base,k,'gold_live_signal_events',{select:'id,snapshot_id,signaled_at,signal_direction,start_price,engine_state,confidence_pct,capital_permission',order:'signaled_at.desc',limit:'5'})
]);
const policy=pols?.[0]||{policy_version:'TFA_GOLD_RESOLUTION_V2',t60_grace_minutes:10,require_fresh_f1:true,require_valid_s1:true,allow_data_quality_terminal:true};
const s1=s1s?.[0];if(!s1)return Response.json({ok:true,version:VERSION,status:'NO_S1_SIGNAL'});const existing=await rows(base,k,'gold_signal_resolution_records',{select:'id,final_state,resolved_at,evidence_hash,resolution_policy',s1_signal_event_id:`eq.${s1.id}`,limit:'1'});if(existing?.[0])return Response.json({ok:true,version:VERSION,status:'ALREADY_FINALIZED',resolution:existing[0]});
const st=new Date(s1.signaled_at).getTime();const targetMs=st+60*60000;const deadlineMs=targetMs+Number(policy.t60_grace_minutes||10)*60000;const nowMs=Date.now();const f1=(f1s||[]).find((x:any)=>x.signal_direction===s1.signal_direction&&Math.abs(new Date(x.signaled_at).getTime()-st)<=120000)||f1s?.[0];if(!f1)return Response.json({ok:true,version:VERSION,status:nowMs>deadlineMs?'WAITING_F1_LINK_EXPIRED':'WAITING_F1_LINK',s1_signal_event_id:s1.id});
const [se,fe,latestF1]=await Promise.all([
 rows(base,k,'gold_spot_evaluations',{select:'horizon_min,start_spot_price,end_spot_price,directional_return_pct,mfe_pct,mae_pct,directional_correct,scored_at',signal_event_id:`eq.${s1.id}`,order:'horizon_min.asc'}),
 rows(base,k,'gold_live_evaluations',{select:'horizon_min,start_price,end_price,return_pct,mfe_pct,mae_pct,directional_correct,scored_at',snapshot_id:`eq.${f1.snapshot_id}`,order:'horizon_min.asc'}),
 rows(base,k,'gold_live_snapshots',{select:'id,captured_at,feed_status,engine_state,quote_age_minutes,gold_price',order:'captured_at.desc',limit:'1'})
]);
const by=(arr:any[],h:number)=>arr.find((x:any)=>Number(x.horizon_min)===h);const s60=by(se,60),f60=by(fe,60);const f60OnTime=!!f60&&new Date(f60.scored_at).getTime()<=deadlineMs;const s60OnTime=!!s60&&new Date(s60.scored_at).getTime()<=deadlineMs;const haveValidF1=f60OnTime;const haveValidS1=s60OnTime;
if(!haveValidF1||!haveValidS1){
 const graceRemaining=Math.max(0,(deadlineMs-nowMs)/60000);
 if(nowMs<=deadlineMs||!policy.allow_data_quality_terminal)return Response.json({ok:true,version:VERSION,status:!haveValidF1&&haveValidS1?'BLOCKED_STALE_F1':'AWAITING_T60',have:{s1_60:haveValidS1,f1_60:haveValidF1},target:new Date(targetMs).toISOString(),deadline:new Date(deadlineMs).toISOString(),grace_minutes_remaining:Number(graceRemaining.toFixed(1)),latest_f1:latestF1?.[0]||null,horizons:{s1:se.map((x:any)=>x.horizon_min),f1:fe.map((x:any)=>x.horizon_min)}});
 const t15=horizonStatus(by(fe,15),by(se,15)),t30=horizonStatus(by(fe,30),by(se,30));const startBasis=Number(f1.start_price)-Number(s1.start_spot_price);const flags:string[]=['DATA_QUALITY_TERMINAL','T60_PAIR_INCOMPLETE'];if(haveValidS1)flags.push('S1_T60_VALID');else flags.push('S1_T60_MISSING_OR_LATE');if(haveValidF1)flags.push('F1_T60_VALID');else flags.push('F1_T60_MISSING_OR_LATE');if(latestF1?.[0]?.engine_state==='STALE_DATA'||latestF1?.[0]?.feed_status==='STALE')flags.push('F1_STALE_DATA_AT_EXPIRY');if(t15==='AGREE_WIN')flags.push('EARLY_T15_CONFIRMATION');if(t30==='DIVERGE')flags.push('T30_CROSS_LEDGER_DIVERGENCE');
 const evidence={policy:policy.policy_version,terminal_reason:'paired valid T+60 unavailable inside grace window',target:new Date(targetMs).toISOString(),deadline:new Date(deadlineMs).toISOString(),s1_signal:s1,f1_signal:f1,latest_f1:latestF1?.[0]||null,horizons:{f1:fe,s1:se},statuses:{t15,t30,t60:'DATA_QUALITY_UNRESOLVED'},validity:{f1_t60_valid:haveValidF1,s1_t60_valid:haveValidS1},lesson_flags:flags};const evidenceHash=await sha256Hex(JSON.stringify(evidence));const body={s1_signal_event_id:s1.id,f1_signal_event_id:f1.id,resolution_policy:policy.policy_version,direction:s1.signal_direction,final_state:'DATA_QUALITY_UNRESOLVED',t15_status:t15,t30_status:t30,t60_status:'DATA_QUALITY_UNRESOLVED',f1_entry:f1.start_price,s1_entry:s1.start_spot_price,f1_t60_end:haveValidF1?f60.end_price:null,s1_t60_end:haveValidS1?s60.end_spot_price:null,f1_t60_correct:haveValidF1?f60.directional_correct:null,s1_t60_correct:haveValidS1?s60.directional_correct:null,f1_t60_mfe_pct:haveValidF1?f60.mfe_pct:null,f1_t60_mae_pct:haveValidF1?f60.mae_pct:null,s1_t60_mfe_pct:haveValidS1?s60.mfe_pct:null,s1_t60_mae_pct:haveValidS1?s60.mae_pct:null,start_basis_usd:Number(startBasis.toFixed(4)),t60_basis_usd:null,basis_change_usd:null,lesson_flags:flags,evidence_bundle:evidence,evidence_hash:evidenceHash};const out=await insert(base,k,'gold_signal_resolution_records',body);return Response.json({ok:true,version:VERSION,status:'FINALIZED_DATA_QUALITY_UNRESOLVED',resolution:out?.[0]||body},{headers:{'Cache-Control':'no-store'}})
 }
const t15=horizonStatus(by(fe,15),by(se,15)),t30=horizonStatus(by(fe,30),by(se,30)),t60=horizonStatus(f60,s60);const finalState=t60==='AGREE_WIN'?'RECONFIRMED':t60==='AGREE_LOSS'?'FAILED_REVIEW':'DIVERGENT_UNRESOLVED';const startBasis=Number(f1.start_price)-Number(s1.start_spot_price),endBasis=Number(f60.end_price)-Number(s60.end_spot_price),basisChange=endBasis-startBasis;const flags:string[]=[];if(t15==='AGREE_WIN')flags.push('EARLY_T15_CONFIRMATION');if(t30==='DIVERGE')flags.push('T30_CROSS_LEDGER_DIVERGENCE');if(t60==='DIVERGE')flags.push('T60_CROSS_LEDGER_DIVERGENCE');if(t60==='AGREE_WIN')flags.push('T60_RECONFIRMED');if(t60==='AGREE_LOSS')flags.push('T60_AGREE_LOSS');if(basisChange<=-3)flags.push('MATERIAL_BASIS_COMPRESSION');else if(basisChange>=3)flags.push('MATERIAL_BASIS_EXPANSION');if(Number(s60.mfe_pct)>Math.abs(Number(s60.mae_pct)))flags.push('SPOT_MFE_EXCEEDED_MAE');if(Number(f60.mfe_pct)>Math.abs(Number(f60.mae_pct)))flags.push('FUTURES_MFE_EXCEEDED_MAE');
const evidence={policy:policy.policy_version,target:new Date(targetMs).toISOString(),deadline:new Date(deadlineMs).toISOString(),s1_signal:s1,f1_signal:f1,horizons:{f1:fe,s1:se},statuses:{t15,t30,t60},basis:{start_usd:Number(startBasis.toFixed(4)),t60_usd:Number(endBasis.toFixed(4)),change_usd:Number(basisChange.toFixed(4))},lesson_flags:flags};const evidenceHash=await sha256Hex(JSON.stringify(evidence));const body={s1_signal_event_id:s1.id,f1_signal_event_id:f1.id,resolution_policy:policy.policy_version,direction:s1.signal_direction,final_state:finalState,t15_status:t15,t30_status:t30,t60_status:t60,f1_entry:f1.start_price,s1_entry:s1.start_spot_price,f1_t60_end:f60.end_price,s1_t60_end:s60.end_spot_price,f1_t60_correct:f60.directional_correct,s1_t60_correct:s60.directional_correct,f1_t60_mfe_pct:f60.mfe_pct,f1_t60_mae_pct:f60.mae_pct,s1_t60_mfe_pct:s60.mfe_pct,s1_t60_mae_pct:s60.mae_pct,start_basis_usd:Number(startBasis.toFixed(4)),t60_basis_usd:Number(endBasis.toFixed(4)),basis_change_usd:Number(basisChange.toFixed(4)),lesson_flags:flags,evidence_bundle:evidence,evidence_hash:evidenceHash};const out=await insert(base,k,'gold_signal_resolution_records',body);return Response.json({ok:true,version:VERSION,status:'FINALIZED',resolution:out?.[0]||body},{headers:{'Cache-Control':'no-store'}})}catch(e){console.error(e);return Response.json({ok:false,version:VERSION,error:'resolution_finalize_failed'},{status:503,headers:{'Cache-Control':'no-store'}})}});