import './styles.css';

const JOURNAL_KEY='tfa.v167.journal.v1';
const PORTFOLIO_KEY='tfa.v167.portfolio.v1';
const state={journal:load(JOURNAL_KEY),portfolio:load(PORTFOLIO_KEY),calendar:[],earnings:[]};

function load(key){try{const v=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
function save(key,value){localStorage.setItem(key,JSON.stringify(value))}
function byId(id){return document.getElementById(id)}
function set(id,value){const el=byId(id);if(el)el.textContent=value??'—'}
function money(v){const n=Number(v||0);return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n)}
function pct(v,d=1){return `${Number(v||0).toFixed(d)}%`}
function num(v){const n=Number(v);return Number.isFinite(n)?n:0}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function uid(){return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`}
function download(name,content,type='application/json'){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
function asCsv(rows){if(!rows.length)return'';const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))];const q=v=>`"${String(v??'').replaceAll('"','""')}"`;return [keys.map(q).join(','),...rows.map(r=>keys.map(k=>q(r[k])).join(','))].join('\n')}

function setupTabs(){document.querySelectorAll('[data-tab]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.capital-panel').forEach(x=>x.classList.remove('active'));byId(`panel-${btn.dataset.tab}`)?.classList.add('active')}))}

function computeTrade(row){const entry=num(row.entry),exit=num(row.exit),stop=num(row.stop),size=Math.max(num(row.size),1);let pnl=Number(row.pnl);if(!Number.isFinite(pnl)||row.pnl===''){if(entry&&exit){const raw=(row.side==='SHORT'?entry-exit:exit-entry)*size;pnl=raw}else pnl=0}let r=Number(row.r);if(!Number.isFinite(r)||row.r===''){const risk=entry&&stop?Math.abs(entry-stop)*size:0;r=risk?pnl/risk:0}return{...row,pnl,r}}
function journalMetrics(){const closed=state.journal.filter(x=>x.status==='CLOSED').map(computeTrade);const net=closed.reduce((a,b)=>a+b.pnl,0);const wins=closed.filter(x=>x.pnl>0);const losses=closed.filter(x=>x.pnl<0);const rSum=closed.reduce((a,b)=>a+b.r,0);const expectancy=closed.length?rSum/closed.length:0;const grossWin=wins.reduce((a,b)=>a+b.pnl,0);const grossLoss=Math.abs(losses.reduce((a,b)=>a+b.pnl,0));const pf=grossLoss?grossWin/grossLoss:(grossWin>0?Infinity:0);const winrate=closed.length?wins.length/closed.length*100:0;return{closed,net,expectancy,pf,winrate}}
function renderJournal(){const m=journalMetrics();set('kpi-net-pnl',money(m.net));set('kpi-trades',`${m.closed.length} closed trades`);set('kpi-expectancy',`${m.expectancy.toFixed(2)}R`);set('kpi-winrate',`${m.winrate.toFixed(1)}% win rate`);set('overview-profit-factor',Number.isFinite(m.pf)?m.pf.toFixed(2):'∞');const body=byId('journal-body');if(body){body.innerHTML=state.journal.length?state.journal.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(row=>{const t=computeTrade(row);return `<tr><td>${esc(new Date(row.date||Date.now()).toLocaleString())}</td><td>${esc(row.type)}</td><td><strong>${esc(row.symbol)}</strong></td><td>${esc(row.side)}</td><td>${esc(row.setup||'—')}</td><td class="number ${t.pnl>0?'positive':t.pnl<0?'negative':''}">${money(t.pnl)}</td><td class="number ${t.r>0?'positive':t.r<0?'negative':''}">${t.r.toFixed(2)}R</td><td class="number">${pct(row.processScore||0,0)}</td><td>${esc(row.status)}</td><td><button class="capital-btn danger" data-delete-journal="${esc(row.id)}">DELETE</button></td></tr>`}).join(''):`<tr><td colspan="10"><div class="empty-state">No journal entries yet. Freeze your next thesis before the outcome is known.</div></td></tr>`;body.querySelectorAll('[data-delete-journal]').forEach(btn=>btn.addEventListener('click',()=>{state.journal=state.journal.filter(x=>x.id!==btn.dataset.deleteJournal);save(JOURNAL_KEY,state.journal);renderAll()}))}
 const setups={};m.closed.forEach(x=>{const k=x.setup||'Unclassified';setups[k]??={n:0,r:0};setups[k].n++;setups[k].r+=x.r});const perf=byId('overview-performance');if(perf){const rows=Object.entries(setups).sort((a,b)=>b[1].n-a[1].n).slice(0,6);perf.innerHTML=rows.length?rows.map(([k,v])=>{const avg=v.r/v.n;const width=Math.min(100,Math.max(5,50+avg*18));return `<div class="mini-bar-line"><span>${esc(k)}</span><div class="mini-bar"><span style="width:${width}%"></span></div><strong>${avg.toFixed(2)}R</strong></div>`}).join(''):'<div class="empty-state">Setup-level expectancy appears after closed journal samples exist.</div>'}}

function portfolioMetrics(){const total=state.portfolio.reduce((a,b)=>a+num(b.value),0);const enriched=state.portfolio.map(x=>{const actual=total?num(x.value)/total*100:0;const drift=actual-num(x.target);const targetValue=total*num(x.target)/100;const rebalance=targetValue-num(x.value);return{...x,actual,drift,rebalance}});const targetSum=enriched.reduce((a,b)=>a+num(b.target),0);const maxWeight=enriched.reduce((m,x)=>Math.max(m,x.actual),0);const hhi=enriched.reduce((a,x)=>a+Math.pow(x.actual,2),0);return{total,enriched,targetSum,maxWeight,hhi}}
function renderPortfolio(){const p=portfolioMetrics();set('kpi-portfolio',money(p.total));set('kpi-holdings',`${p.enriched.length} holdings`);set('portfolio-total',money(p.total));set('portfolio-target-sum',pct(p.targetSum,1));set('portfolio-max-weight',pct(p.maxWeight,1));set('portfolio-hhi',Math.round(p.hhi).toLocaleString());const complete=Math.min(100,Math.max(0,p.targetSum));byId('target-completion-bar')?.setAttribute('style',`width:${complete}%`);set('target-completion-copy',`Target weights: ${p.targetSum.toFixed(2)}%`);const outOfBand=p.enriched.filter(x=>Math.abs(x.drift)>num(x.driftBand||2));if(!p.enriched.length){set('allocation-health','NO PORTFOLIO YET');set('allocation-health-copy','Add holdings and target weights to calculate drift, concentration and rebalance amounts.')}else if(Math.abs(p.targetSum-100)>.1){set('allocation-health','TARGETS ≠ 100%');set('allocation-health-copy','Policy target weights must sum to 100% before rebalance amounts should be treated as complete.')}else if(outOfBand.length){set('allocation-health',`${outOfBand.length} DRIFT FLAGS`);set('allocation-health-copy','One or more holdings moved outside the user-defined drift band. Review, do not auto-trade.')}else{set('allocation-health','WITHIN POLICY BANDS');set('allocation-health-copy','Current weights sit inside the user-defined drift bands. No automatic trade is generated.')}
 const body=byId('portfolio-body');if(body){body.innerHTML=p.enriched.length?p.enriched.map(x=>`<tr><td><strong>${esc(x.symbol)}</strong></td><td>${esc(x.assetClass)}</td><td class="number">${money(x.value)}</td><td class="number">${pct(x.actual,2)}</td><td class="number">${pct(x.target,2)}</td><td class="number ${Math.abs(x.drift)>num(x.driftBand||2)?'negative':''}">${x.drift>=0?'+':''}${x.drift.toFixed(2)}%</td><td class="number ${x.rebalance>=0?'positive':'negative'}">${x.rebalance>=0?'+':''}${money(x.rebalance)}</td><td>${Math.abs(x.drift)>num(x.driftBand||2)?'REVIEW':'IN BAND'}</td><td><button class="capital-btn danger" data-delete-holding="${esc(x.id)}">DELETE</button></td></tr>`).join(''):`<tr><td colspan="9"><div class="empty-state">No holdings yet.</div></td></tr>`;body.querySelectorAll('[data-delete-holding]').forEach(btn=>btn.addEventListener('click',()=>{state.portfolio=state.portfolio.filter(x=>x.id!==btn.dataset.deleteHolding);save(PORTFOLIO_KEY,state.portfolio);renderAll()}))}
 const mix={};p.enriched.forEach(x=>mix[x.assetClass]=(mix[x.assetClass]||0)+x.actual);const mixHost=byId('allocation-mix');if(mixHost)mixHost.innerHTML=Object.entries(mix).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="mini-bar-line"><span>${esc(k)}</span><div class="mini-bar"><span style="width:${Math.min(100,v)}%"></span></div><strong>${v.toFixed(1)}%</strong></div>`).join('')||'<div class="empty-state">Asset-class allocation appears here.</div>';set('rebalance-summary',p.enriched.length?`${outOfBand.length} holdings outside drift bands · target total ${p.targetSum.toFixed(2)}% · all rebalance amounts are calculations, not orders.`:'Targets are user-defined policy inputs. The machine calculates drift; it does not choose your investment policy.')}

function renderAll(){renderJournal();renderPortfolio()}

function setupJournal(){const form=byId('journal-form');const date=form?.querySelector('[name=date]');if(date&&!date.value)date.value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);form?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form);const row=Object.fromEntries(fd.entries());state.journal.push({...row,id:uid(),createdAt:new Date().toISOString()});save(JOURNAL_KEY,state.journal);form.reset();if(date)date.value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);renderAll()});byId('export-journal-json')?.addEventListener('click',()=>download(`tfa-journal-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(state.journal,null,2)));byId('export-journal-csv')?.addEventListener('click',()=>download(`tfa-journal-${new Date().toISOString().slice(0,10)}.csv`,asCsv(state.journal),'text/csv'));byId('clear-journal')?.addEventListener('click',()=>{if(confirm('Clear the local journal on this browser? Export first if you need a backup.')){state.journal=[];save(JOURNAL_KEY,[]);renderAll()}})}
function setupPortfolio(){const form=byId('portfolio-form');form?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form);const row=Object.fromEntries(fd.entries());const symbol=String(row.symbol||'').trim().toUpperCase();const existing=state.portfolio.find(x=>x.symbol===symbol);const payload={...row,symbol,id:existing?.id||uid(),updatedAt:new Date().toISOString()};state.portfolio=existing?state.portfolio.map(x=>x.id===existing.id?payload:x):[...state.portfolio,payload];save(PORTFOLIO_KEY,state.portfolio);form.reset();const band=form.querySelector('[name=driftBand]');if(band)band.value='2';renderAll()});byId('export-portfolio')?.addEventListener('click',()=>download(`tfa-portfolio-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({generatedAt:new Date().toISOString(),holdings:state.portfolio,metrics:portfolioMetrics()},null,2)));byId('clear-portfolio')?.addEventListener('click',()=>{if(confirm('Clear the local portfolio on this browser?')){state.portfolio=[];save(PORTFOLIO_KEY,[]);renderAll()}})}

function impactClass(x){return String(x||'').toLowerCase()==='high'?'high':String(x||'').toLowerCase()==='medium'?'medium':'low'}
function countdown(iso){const t=new Date(iso).getTime();if(!Number.isFinite(t))return'—';const d=t-Date.now();if(d<=0)return'RELEASED / IN PROGRESS';const mins=Math.floor(d/60000);const days=Math.floor(mins/1440);const hours=Math.floor((mins%1440)/60);const m=mins%60;return days?`${days}d ${hours}h ${m}m`:hours?`${hours}h ${m}m`:`${m}m`}
function renderCalendar(data){state.calendar=Array.isArray(data?.events)?data.events:[];set('calendar-source-state',data?.state||'UNAVAILABLE');set('calendar-source-copy',data?.detail||'Official BLS + Federal Reserve schedules.');const future=state.calendar.filter(x=>new Date(x.datetime).getTime()>=Date.now()).sort((a,b)=>new Date(a.datetime)-new Date(b.datetime));const high=future.find(x=>String(x.impact).toUpperCase()==='HIGH')||future[0];if(high){set('calendar-next-title',high.title);set('calendar-next-time',`${new Date(high.datetime).toLocaleString()} · ${countdown(high.datetime)}`);set('calendar-next-meta',`${high.country||'US'} · ${high.source||'Official schedule'}`);set('kpi-next-event',high.short||high.title);set('kpi-next-countdown',countdown(high.datetime));set('overview-event-title',high.title);set('overview-event-copy',`${new Date(high.datetime).toLocaleString()} · ${high.impact} impact · ${high.source}`);set('overview-event-countdown',countdown(high.datetime));const hours=(new Date(high.datetime)-Date.now())/36e5;set('calendar-risk-state',hours<=6?'EVENT WINDOW · <6H':hours<=24?'EVENT WINDOW · <24H':'NORMAL WATCH')}else{set('calendar-next-title','NO UPCOMING EVENTS');set('calendar-risk-state','NO EVENT FOUND')}
 const host=byId('calendar-list');if(host)host.innerHTML=future.length?future.slice(0,40).map(x=>`<article class="event-card"><div class="event-time">${esc(new Date(x.datetime).toLocaleString())}<br><span class="countdown">${esc(countdown(x.datetime))}</span></div><div><div class="event-title">${esc(x.title)}</div><div class="event-meta">${esc(x.country||'US')} · ${esc(x.source||'Official')} · ${esc(x.notes||'')}</div></div><span class="impact ${impactClass(x.impact)}">${esc(String(x.impact||'LOW').toUpperCase())}</span></article>`).join(''):'<div class="empty-state">No verified future events were returned. The calendar remains fail-closed rather than inventing dates.</div>'}
async function loadCalendar(){set('calendar-source-state','SYNCING');try{const r=await fetch('/api/capital-calendar',{cache:'no-store'});renderCalendar(await r.json())}catch{renderCalendar({state:'UNAVAILABLE',events:[],detail:'Calendar transport unavailable.'})}}

function renderEarnings(data){state.earnings=Array.isArray(data?.rows)?data.rows:[];set('earnings-feed-state',data?.state||'UNAVAILABLE');set('earnings-feed-copy',data?.detail||'Earnings feed unavailable.');set('earnings-today-count',String(state.earnings.length));const large=state.earnings.filter(x=>num(String(x.marketCap||'').replace(/[^0-9.-]/g,''))>=1e9);set('earnings-large-count',String(large.length));set('overview-earnings-title',state.earnings.length?`${state.earnings.length} REPORTS LOADED`:'NO VERIFIED REPORTS');set('overview-earnings-copy',data?.detail||'No verified earnings rows were returned.');const host=byId('earnings-list');if(host)host.innerHTML=state.earnings.length?state.earnings.map(x=>`<article class="event-card"><div class="event-time">${esc(x.time||'TIME UNSUPPLIED')}<br>${esc(x.fiscalQuarterEnding||'')}</div><div><div class="event-title">${esc(x.symbol||'—')} · ${esc(x.name||'')}</div><div class="event-meta">EPS forecast ${esc(x.epsForecast||'WITHHELD')} · Last year EPS ${esc(x.lastYearEPS||'WITHHELD')} · Ests ${esc(x.noOfEsts||'—')}</div></div><span class="impact low">EARNINGS</span></article>`).join(''):'<div class="empty-state">No verified earnings rows for this date, or the upstream feed is unavailable.</div>';set('earnings-source-line',data?.source?`Source: ${data.source} · generated ${data.generated_at||'unknown'}`:'Source unavailable')}
async function loadEarnings(){const date=byId('earnings-date')?.value||new Date().toISOString().slice(0,10);set('earnings-feed-state','SYNCING');try{const r=await fetch(`/api/earnings-calendar?date=${encodeURIComponent(date)}`,{cache:'no-store'});renderEarnings(await r.json())}catch{renderEarnings({state:'UNAVAILABLE',rows:[],detail:'Earnings transport unavailable.'})}}

async function loadGovernance(){try{const r=await fetch('/api/production-closure',{cache:'no-store'});const d=await r.json();set('governance-state',d?.state||'FAIL CLOSED');set('governance-copy',d?.closure?.note||'V166 governance unavailable; defaulting to WAIT / 0R.');set('governance-action',d?.governance?.action_permitted||'WAIT');set('governance-capital',d?.governance?.capital_permission||'0R')}catch{set('governance-state','V166 UNAVAILABLE');set('governance-copy','Governance transport unavailable. Defaulting to WAIT / 0R.');set('governance-action','WAIT');set('governance-capital','0R')}}

function boot(){setupTabs();setupJournal();setupPortfolio();renderAll();const today=new Date().toISOString().slice(0,10);const d=byId('earnings-date');if(d)d.value=today;byId('refresh-calendar')?.addEventListener('click',loadCalendar);byId('refresh-earnings')?.addEventListener('click',loadEarnings);void Promise.allSettled([loadGovernance(),loadCalendar(),loadEarnings()]);setInterval(()=>{if(state.calendar.length)renderCalendar({state:'LIVE / CACHED',events:state.calendar,detail:'Countdown refreshed locally. Source refresh is manual or on page load.'})},60000)}
boot();
