-- V125 Gold Signal Reputation
-- Transition-linked review candidates -> human review event ledger -> prospective outcomes -> sample-gated reputation.

create table if not exists public.gold_trigger_review_requests (
  id bigint generated by default as identity primary key,
  requested_at timestamptz not null default now(),
  transition_id bigint not null references public.gold_live_desk_transitions(id),
  snapshot_id bigint not null references public.gold_live_desk_snapshots(id),
  market_time timestamptz,
  event_class text not null,
  transition_code text not null,
  signal_key text not null,
  direction text not null,
  review_stage text not null,
  source_state text,
  source_price numeric,
  request_reason jsonb not null default '{}'::jsonb,
  request_sha256 text not null,
  unique(transition_id)
);

alter table public.gold_trigger_review_requests enable row level security;
revoke all privileges on table public.gold_trigger_review_requests from public, anon, authenticated;
grant select, insert on table public.gold_trigger_review_requests to service_role;
grant usage, select on sequence public.gold_trigger_review_requests_id_seq to service_role;

create index if not exists gold_trigger_review_requests_snapshot_idx
  on public.gold_trigger_review_requests(snapshot_id);
create index if not exists gold_trigger_review_requests_signal_idx
  on public.gold_trigger_review_requests(signal_key, requested_at desc);

create table if not exists public.gold_human_review_events (
  id bigint generated by default as identity primary key,
  review_request_id bigint not null references public.gold_trigger_review_requests(id),
  event_at timestamptz not null default now(),
  event_type text not null,
  reviewer_source text not null,
  decision text,
  note text,
  evidence_sha256 text not null
);

alter table public.gold_human_review_events enable row level security;
revoke all privileges on table public.gold_human_review_events from public, anon, authenticated;
grant select, insert on table public.gold_human_review_events to service_role;
grant usage, select on sequence public.gold_human_review_events_id_seq to service_role;

create index if not exists gold_human_review_events_request_idx
  on public.gold_human_review_events(review_request_id, event_at desc);

create table if not exists public.gold_signal_reputation_snapshots (
  id bigint generated by default as identity primary key,
  evaluated_at timestamptz not null default now(),
  signal_key text not null,
  transition_code text not null,
  source_state text,
  direction text not null,
  horizon_minutes integer not null,
  sample_count integer not null,
  favorable_count integer not null,
  adverse_count integer not null,
  flat_count integer not null,
  observed_hit_rate_pct numeric,
  wilson_lower_pct numeric,
  avg_signed_delta numeric,
  avg_favorable_excursion numeric,
  avg_adverse_excursion numeric,
  source_outcome_max_id bigint not null,
  reputation_state text not null,
  evidence_review_state text not null,
  automatic_weight numeric,
  automatic_promotion boolean not null default false,
  capital_permission text not null default '0R',
  payload_sha256 text not null,
  unique(signal_key,horizon_minutes,source_outcome_max_id)
);

alter table public.gold_signal_reputation_snapshots enable row level security;
revoke all privileges on table public.gold_signal_reputation_snapshots from public, anon, authenticated;
grant select, insert on table public.gold_signal_reputation_snapshots to service_role;
grant usage, select on sequence public.gold_signal_reputation_snapshots_id_seq to service_role;

create index if not exists gold_signal_reputation_signal_idx
  on public.gold_signal_reputation_snapshots(signal_key,horizon_minutes,evaluated_at desc);
create index if not exists gold_signal_reputation_state_idx
  on public.gold_signal_reputation_snapshots(reputation_state,evaluated_at desc);

create or replace function public.prevent_v125_gold_learning_mutation()
returns trigger
language plpgsql
set search_path to ''
as $$
begin
  raise exception 'V125 Gold learning ledgers are append-only';
end;
$$;

revoke all on function public.prevent_v125_gold_learning_mutation() from public, anon, authenticated;

drop trigger if exists prevent_v125_review_request_update_delete on public.gold_trigger_review_requests;
create trigger prevent_v125_review_request_update_delete
before update or delete on public.gold_trigger_review_requests
for each row execute function public.prevent_v125_gold_learning_mutation();

drop trigger if exists prevent_v125_human_review_update_delete on public.gold_human_review_events;
create trigger prevent_v125_human_review_update_delete
before update or delete on public.gold_human_review_events
for each row execute function public.prevent_v125_gold_learning_mutation();

drop trigger if exists prevent_v125_signal_reputation_update_delete on public.gold_signal_reputation_snapshots;
create trigger prevent_v125_signal_reputation_update_delete
before update or delete on public.gold_signal_reputation_snapshots
for each row execute function public.prevent_v125_gold_learning_mutation();

create or replace function public.capture_v125_gold_review_requests()
returns jsonb
language plpgsql
set search_path to 'public','extensions','pg_temp'
as $$
declare
  t record;
  v_direction text;
  v_signal_key text;
  v_stage text;
  v_reason jsonb;
  v_inserted integer := 0;
begin
  for t in
    select *
    from public.gold_live_desk_transitions x
    where x.event_class in ('SETUP','LEVEL','STRUCTURE')
      and not exists (
        select 1 from public.gold_trigger_review_requests r
        where r.transition_id=x.id
      )
    order by x.id
  loop
    v_direction:=case
      when t.transition_code='LONG_RETEST_ZONE_ENTERED'
        or coalesce(t.to_state,'') ilike '%LONG%'
        or coalesce(t.changes->>'long_to','') ilike '%LONG%'
        then 'LONG'
      when t.transition_code='SHORT_FAILURE_THRESHOLD_BREACHED'
        or coalesce(t.to_state,'') ilike '%SHORT%'
        or coalesce(t.changes->>'short_to','') ilike '%SHORT%'
        then 'SHORT'
      else 'UNCLASSIFIED'
    end;

    v_signal_key:=concat_ws(':',t.transition_code,coalesce(nullif(t.to_state,''),'STATE_UNKNOWN'));
    v_stage:=case
      when t.severity='REVIEW_REQUIRED' then 'HUMAN_REVIEW_REQUIRED'
      when t.event_class='LEVEL' then 'LEVEL_REVIEW_CANDIDATE'
      when t.event_class='STRUCTURE' then 'STRUCTURE_REVIEW_CANDIDATE'
      else 'WATCH_REVIEW_CANDIDATE'
    end;
    v_reason:=jsonb_build_object(
      'severity',t.severity,
      'event_class',t.event_class,
      'from_state',t.from_state,
      'to_state',t.to_state,
      'changes',t.changes,
      'human_decision_required_for_promotion',true,
      'automatic_promotion',false
    );

    insert into public.gold_trigger_review_requests(
      transition_id,snapshot_id,market_time,event_class,transition_code,
      signal_key,direction,review_stage,source_state,source_price,
      request_reason,request_sha256
    ) values (
      t.id,t.to_snapshot_id,t.to_market_time,t.event_class,t.transition_code,
      v_signal_key,v_direction,v_stage,t.to_state,t.to_price,v_reason,
      encode(extensions.digest(convert_to(concat_ws('|',
        t.id::text,t.to_snapshot_id::text,coalesce(t.to_market_time::text,''),
        t.event_class,t.transition_code,v_signal_key,v_direction,v_stage,
        coalesce(t.to_state,''),coalesce(t.to_price::text,''),v_reason::text
      ),'UTF8'),'sha256'),'hex')
    )
    on conflict(transition_id) do nothing;

    if found then v_inserted:=v_inserted+1; end if;
  end loop;

  return jsonb_build_object(
    'ok',true,'version','v125-review-capture-v1','inserted',v_inserted,
    'total_requests',(select count(*) from public.gold_trigger_review_requests),
    'directional_requests',(select count(*) from public.gold_trigger_review_requests where direction in ('LONG','SHORT')),
    'human_review_events',(select count(*) from public.gold_human_review_events),
    'checked_at',now()
  );
end;
$$;

revoke all on function public.capture_v125_gold_review_requests() from public, anon, authenticated;
grant execute on function public.capture_v125_gold_review_requests() to service_role;

create or replace function public.refresh_v125_gold_signal_reputation()
returns jsonb
language plpgsql
set search_path to 'public','extensions','pg_temp'
as $$
declare
  g record;
  v_hit numeric;
  v_wilson numeric;
  v_state text;
  v_review_state text;
  v_inserted integer := 0;
begin
  perform public.capture_v125_gold_review_requests();

  for g in
    with linked as (
      select
        r.signal_key,r.transition_code,r.source_state,r.direction,o.horizon_minutes,o.id as outcome_id,
        case when r.direction='LONG' then o.price_delta else -o.price_delta end as signed_delta,
        case when r.direction='LONG' then o.up_excursion else o.down_excursion end as favorable_excursion,
        case when r.direction='LONG' then o.down_excursion else o.up_excursion end as adverse_excursion
      from public.gold_trigger_review_requests r
      join public.gold_live_desk_outcomes o on o.snapshot_id=r.snapshot_id
      where r.direction in ('LONG','SHORT')
    )
    select signal_key,transition_code,source_state,direction,horizon_minutes,
      count(*)::int as sample_count,
      count(*) filter(where signed_delta>0)::int as favorable_count,
      count(*) filter(where signed_delta<0)::int as adverse_count,
      count(*) filter(where signed_delta=0)::int as flat_count,
      avg(signed_delta)::numeric as avg_signed_delta,
      avg(favorable_excursion)::numeric as avg_favorable_excursion,
      avg(adverse_excursion)::numeric as avg_adverse_excursion,
      max(outcome_id)::bigint as source_outcome_max_id
    from linked
    group by signal_key,transition_code,source_state,direction,horizon_minutes
  loop
    v_hit:=case when g.sample_count>0 then g.favorable_count::numeric/g.sample_count::numeric else null end;
    v_wilson:=case when g.sample_count>0 then
      (v_hit+(1.96*1.96)/(2*g.sample_count)
       -1.96*sqrt((v_hit*(1-v_hit)/g.sample_count)+((1.96*1.96)/(4*g.sample_count*g.sample_count))))
      /(1+(1.96*1.96)/g.sample_count)
      else null end;
    v_state:=case
      when g.sample_count<10 then 'WITHHELD_SAMPLE_TOO_SMALL'
      when g.sample_count<30 then 'EARLY_REPUTATION_SAMPLE'
      when v_wilson>0.50 then 'MATURE_FAVORABLE_EVIDENCE'
      else 'MATURE_EDGE_NOT_PROVEN'
    end;
    v_review_state:=case
      when g.sample_count<10 then 'WITHHELD_UNDER_MINIMUM_N'
      when g.sample_count<30 then 'HUMAN_REVIEWABLE_EARLY_SAMPLE'
      else 'HUMAN_REVIEWABLE_MATURE_SAMPLE'
    end;

    insert into public.gold_signal_reputation_snapshots(
      signal_key,transition_code,source_state,direction,horizon_minutes,
      sample_count,favorable_count,adverse_count,flat_count,
      observed_hit_rate_pct,wilson_lower_pct,avg_signed_delta,
      avg_favorable_excursion,avg_adverse_excursion,source_outcome_max_id,
      reputation_state,evidence_review_state,automatic_weight,
      automatic_promotion,capital_permission,payload_sha256
    ) values (
      g.signal_key,g.transition_code,g.source_state,g.direction,g.horizon_minutes,
      g.sample_count,g.favorable_count,g.adverse_count,g.flat_count,
      round(v_hit*100,2),round(v_wilson*100,2),round(g.avg_signed_delta,4),
      round(g.avg_favorable_excursion,4),round(g.avg_adverse_excursion,4),g.source_outcome_max_id,
      v_state,v_review_state,null,false,'0R',
      encode(extensions.digest(convert_to(concat_ws('|',
        g.signal_key,g.transition_code,coalesce(g.source_state,''),g.direction,
        g.horizon_minutes::text,g.sample_count::text,g.favorable_count::text,
        g.adverse_count::text,g.flat_count::text,coalesce(round(v_hit*100,2)::text,''),
        coalesce(round(v_wilson*100,2)::text,''),coalesce(round(g.avg_signed_delta,4)::text,''),
        coalesce(round(g.avg_favorable_excursion,4)::text,''),coalesce(round(g.avg_adverse_excursion,4)::text,''),
        g.source_outcome_max_id::text,v_state,v_review_state,'0R'
      ),'UTF8'),'sha256'),'hex')
    )
    on conflict(signal_key,horizon_minutes,source_outcome_max_id) do nothing;

    if found then v_inserted:=v_inserted+1; end if;
  end loop;

  return jsonb_build_object(
    'ok',true,'version','v125-signal-reputation-refresh-v1','inserted',v_inserted,
    'reputation_snapshots',(select count(*) from public.gold_signal_reputation_snapshots),
    'latest_sample_max',(select coalesce(max(sample_count),0) from public.gold_signal_reputation_snapshots),
    'human_review_events',(select count(*) from public.gold_human_review_events),
    'automatic_promotion',false,'capital_permission','0R','checked_at',now()
  );
end;
$$;

revoke all on function public.refresh_v125_gold_signal_reputation() from public, anon, authenticated;
grant execute on function public.refresh_v125_gold_signal_reputation() to service_role;

do $$
begin
  if not exists(select 1 from cron.job where jobname='tfa-v125-gold-signal-reputation') then
    perform cron.schedule(
      'tfa-v125-gold-signal-reputation',
      '*/2 * * * *',
      'select public.refresh_v125_gold_signal_reputation();'
    );
  end if;
end $$;
