-- V136 Execution Qualification + Order Firewall
-- Auditable dry-run qualification only. No broker call, no live route, no real order, capital fixed at 0R.

create table if not exists public.gold_execution_qualification_snapshots (
  id bigint generated by default as identity primary key,
  evaluated_at timestamptz not null default now(),
  qualification_version text not null,
  portfolio_decision_id bigint not null references public.gold_shadow_portfolio_decisions(id),
  intent_id bigint not null references public.gold_shadow_trade_intents(id),
  strategy_code text not null,
  side text not null check (side in ('LONG','SHORT')),
  source_market_time timestamptz not null,
  reference_entry numeric not null,
  stop_price numeric not null,
  target_price numeric not null,
  risk_points numeric not null,
  reference_rr numeric not null,
  requested_paper_r numeric not null,
  dry_run_client_order_id text not null,
  risk_geometry_valid boolean not null,
  resolved_research_sample integer not null,
  mature_sample_required integer not null default 30,
  mature_research_sample boolean not null,
  adapter_lab_pass boolean not null,
  adapter_real_orders_sent integer not null default 0,
  production_broker_verified boolean not null default false,
  real_broker_connected boolean not null default false,
  live_order_route_present boolean not null default false,
  execution_grade_quote_available boolean not null default false,
  broker_spread_measured boolean not null default false,
  slippage_measured boolean not null default false,
  human_release_review_complete boolean not null default false,
  dry_run_order_ready boolean not null,
  live_order_qualified boolean not null default false,
  live_order_submission_enabled boolean not null default false,
  real_order_sent boolean not null default false,
  real_capital_permission text not null default '0R',
  blocker_codes jsonb not null default '[]'::jsonb,
  qualification_state text not null,
  source_readiness_sha256 text,
  source_adapter_sha256 text,
  qualification_sha256 text not null unique
);

alter table public.gold_execution_qualification_snapshots enable row level security;
revoke all privileges on table public.gold_execution_qualification_snapshots from public, anon, authenticated;
grant select, insert on table public.gold_execution_qualification_snapshots to service_role;
grant usage, select on sequence public.gold_execution_qualification_snapshots_id_seq to service_role;

create index if not exists gold_execution_qualification_decision_idx
  on public.gold_execution_qualification_snapshots(portfolio_decision_id,evaluated_at desc);
create index if not exists gold_execution_qualification_intent_idx
  on public.gold_execution_qualification_snapshots(intent_id,evaluated_at desc);
create index if not exists gold_execution_qualification_state_idx
  on public.gold_execution_qualification_snapshots(qualification_state,evaluated_at desc);

drop trigger if exists prevent_v136_execution_qualification_mutation on public.gold_execution_qualification_snapshots;
create trigger prevent_v136_execution_qualification_mutation
before update or delete on public.gold_execution_qualification_snapshots
for each row execute function public.prevent_v125_gold_learning_mutation();

create or replace function public.refresh_v136_gold_execution_qualification()
returns jsonb
language plpgsql
set search_path to 'public','extensions','pg_temp'
as $$
declare
  v_version constant text := 'v136-execution-qualification-firewall-v1';
  p record; i record; r record; a record;
  v_risk_valid boolean := false; v_lab_safe boolean := false; v_mature boolean := false;
  v_prod_broker boolean := false; v_real_broker boolean := false; v_live_route boolean := false;
  v_quote boolean := false; v_spread boolean := false; v_slippage boolean := false;
  v_human_release boolean := false; v_dry_ready boolean := false; v_live_qualified boolean := false;
  v_blockers text[] := '{}'::text[]; v_existing_blockers text[] := '{}'::text[];
  v_state text; v_client_order_id text; v_sha text; v_requested_r numeric; v_row_id bigint;
begin
  perform public.refresh_v133_gold_shadow_portfolio();

  select x.* into p
  from public.gold_shadow_portfolio_decisions x
  where x.decision='ALLOCATE'
    and not exists (select 1 from public.gold_shadow_portfolio_outcomes o where o.decision_id=x.id)
  order by x.source_market_time desc,x.id desc limit 1;

  if not found then
    return jsonb_build_object('ok',true,'version',v_version,'state','WAITING_FOR_OPEN_PAPER_POSITION',
      'dry_run_order_ready',false,'live_order_qualified',false,'live_order_submission_enabled',false,
      'real_order_sent',false,'real_capital_permission','0R','checked_at',now());
  end if;

  select x.* into i from public.gold_shadow_trade_intents x where x.id=p.intent_id limit 1;
  if not found then
    return jsonb_build_object('ok',false,'version',v_version,'state','FAIL_CLOSED_INTENT_MISSING',
      'portfolio_decision_id',p.id,'live_order_submission_enabled',false,'real_order_sent',false,
      'real_capital_permission','0R','checked_at',now());
  end if;

  select x.* into r from public.gold_execution_readiness_snapshots x
  where x.strategy_code=i.strategy_code order by x.id desc limit 1;
  if not found then
    select x.* into r from public.gold_execution_readiness_snapshots x order by x.id desc limit 1;
  end if;

  select z.*,run.real_broker_connected,run.live_order_route_present,
         run.live_order_submission_enabled as run_live_order_submission_enabled
  into a
  from public.gold_broker_adapter_lab_results z
  join public.gold_broker_adapter_lab_runs run on run.id=z.run_id
  order by z.id desc limit 1;

  v_risk_valid := i.risk_points is not null and i.risk_points > 0
    and i.stop_price is not null and i.target_price is not null
    and i.reference_rr is not null and i.reference_rr > 0
    and ((i.side='LONG' and i.stop_price < i.source_price and i.target_price > i.source_price)
      or (i.side='SHORT' and i.stop_price > i.source_price and i.target_price < i.source_price));

  v_lab_safe := a.id is not null and a.result_state='PASS_SIMULATION_ONLY'
    and a.dry_run_lifecycle_pass=true and a.idempotency_pass=true and a.reconciliation_pass=true
    and a.kill_switch_pass=true and a.live_route_denial_pass=true
    and a.unauthorized_submit_blocked=true and coalesce(a.real_orders_sent,0)=0;

  v_mature := coalesce(r.resolved_sample,0) >= 30;
  v_prod_broker := coalesce(a.production_broker_readiness,'NOT_TESTED')='VERIFIED';
  v_real_broker := coalesce(a.real_broker_connected,false);
  v_live_route := coalesce(a.live_order_route_present,false);
  v_quote := coalesce(r.execution_grade_quote_available,false);
  v_spread := coalesce(r.broker_spread_measured,false);
  v_slippage := coalesce(r.slippage_measured,false);
  v_human_release := false;

  if r.blocker_codes is not null and jsonb_typeof(r.blocker_codes)='array' then
    select coalesce(array_agg(value),'{}'::text[]) into v_existing_blockers
    from jsonb_array_elements_text(r.blocker_codes);
    v_blockers := v_blockers || v_existing_blockers;
  end if;

  if not v_risk_valid then v_blockers := array_append(v_blockers,'INVALID_RISK_GEOMETRY'); end if;
  if not v_lab_safe then v_blockers := array_append(v_blockers,'ADAPTER_LAB_NOT_PASSING'); end if;
  if not v_mature then v_blockers := array_append(v_blockers,'MATURE_SAMPLE_BELOW_30'); end if;
  if not v_prod_broker then v_blockers := array_append(v_blockers,'PRODUCTION_BROKER_NOT_VERIFIED'); end if;
  if not v_real_broker then v_blockers := array_append(v_blockers,'REAL_BROKER_NOT_CONNECTED'); end if;
  if not v_live_route then v_blockers := array_append(v_blockers,'LIVE_ORDER_ROUTE_ABSENT'); end if;
  if not v_quote then v_blockers := array_append(v_blockers,'EXECUTION_GRADE_QUOTE_UNAVAILABLE'); end if;
  if not v_spread then v_blockers := array_append(v_blockers,'BROKER_SPREAD_NOT_MEASURED'); end if;
  if not v_slippage then v_blockers := array_append(v_blockers,'SLIPPAGE_NOT_MEASURED'); end if;
  if not v_human_release then v_blockers := array_append(v_blockers,'HUMAN_RELEASE_REVIEW_REQUIRED'); end if;

  select coalesce(array_agg(x order by x),'{}'::text[]) into v_blockers
  from (select distinct unnest(v_blockers) as x) q;

  v_requested_r := least(greatest(coalesce(p.allocated_risk_r,0),0),1);
  v_client_order_id := concat('DRY-V136-',p.id,'-',p.intent_id);
  v_dry_ready := v_risk_valid and v_lab_safe
    and p.live_order_eligible=false and p.live_trading_enabled=false
    and i.live_order_eligible=false and i.live_trading_enabled=false;

  v_live_qualified := v_dry_ready and v_mature and coalesce(cardinality(v_existing_blockers),0)=0
    and v_prod_broker and v_real_broker and v_live_route and v_quote and v_spread and v_slippage and v_human_release;

  v_state := case
    when not v_risk_valid then 'FAIL_CLOSED_INVALID_RISK'
    when not v_lab_safe then 'FAIL_CLOSED_ADAPTER_LAB'
    when v_live_qualified then 'HUMAN_RELEASE_ELIGIBLE'
    when v_dry_ready then 'DRY_RUN_READY_LIVE_LOCKED'
    else 'FAIL_CLOSED' end;

  v_sha := encode(extensions.digest(convert_to(concat_ws('|',
    v_version,p.id::text,i.id::text,i.strategy_code,i.side,i.source_market_time::text,
    i.source_price::text,i.stop_price::text,i.target_price::text,i.risk_points::text,
    i.reference_rr::text,v_requested_r::text,v_risk_valid::text,coalesce(r.resolved_sample,0)::text,
    v_mature::text,v_lab_safe::text,coalesce(a.real_orders_sent,0)::text,v_prod_broker::text,
    v_real_broker::text,v_live_route::text,v_quote::text,v_spread::text,v_slippage::text,
    v_human_release::text,v_dry_ready::text,v_live_qualified::text,array_to_string(v_blockers,','),
    v_state,coalesce(r.payload_sha256,''),coalesce(a.payload_sha256,''),'false','false','0R'
  ),'UTF8'),'sha256'),'hex');

  insert into public.gold_execution_qualification_snapshots(
    qualification_version,portfolio_decision_id,intent_id,strategy_code,side,source_market_time,
    reference_entry,stop_price,target_price,risk_points,reference_rr,requested_paper_r,
    dry_run_client_order_id,risk_geometry_valid,resolved_research_sample,mature_sample_required,
    mature_research_sample,adapter_lab_pass,adapter_real_orders_sent,production_broker_verified,
    real_broker_connected,live_order_route_present,execution_grade_quote_available,broker_spread_measured,
    slippage_measured,human_release_review_complete,dry_run_order_ready,live_order_qualified,
    live_order_submission_enabled,real_order_sent,real_capital_permission,blocker_codes,qualification_state,
    source_readiness_sha256,source_adapter_sha256,qualification_sha256
  ) values (
    v_version,p.id,i.id,i.strategy_code,i.side,i.source_market_time,i.source_price,i.stop_price,
    i.target_price,i.risk_points,i.reference_rr,v_requested_r,v_client_order_id,v_risk_valid,
    coalesce(r.resolved_sample,0),30,v_mature,v_lab_safe,coalesce(a.real_orders_sent,0),v_prod_broker,
    v_real_broker,v_live_route,v_quote,v_spread,v_slippage,v_human_release,v_dry_ready,v_live_qualified,
    false,false,'0R',to_jsonb(v_blockers),v_state,r.payload_sha256,a.payload_sha256,v_sha
  )
  on conflict(qualification_sha256) do nothing returning id into v_row_id;

  if v_row_id is null then
    select id into v_row_id from public.gold_execution_qualification_snapshots
    where qualification_sha256=v_sha limit 1;
  end if;

  return jsonb_build_object(
    'ok',true,'version',v_version,'snapshot_id',v_row_id,'state',v_state,
    'portfolio_decision_id',p.id,'intent_id',i.id,'dry_run_client_order_id',v_client_order_id,
    'side',i.side,'reference_entry',i.source_price,'stop_price',i.stop_price,'target_price',i.target_price,
    'reference_rr',i.reference_rr,'requested_paper_r',v_requested_r,'risk_geometry_valid',v_risk_valid,
    'resolved_research_sample',coalesce(r.resolved_sample,0),'mature_sample_required',30,
    'adapter_lab_pass',v_lab_safe,'dry_run_order_ready',v_dry_ready,'live_order_qualified',v_live_qualified,
    'blocker_codes',to_jsonb(v_blockers),'live_order_submission_enabled',false,'real_order_sent',false,
    'real_capital_permission','0R','checked_at',now()
  );
end;
$$;

revoke all on function public.refresh_v136_gold_execution_qualification() from public, anon, authenticated;
grant execute on function public.refresh_v136_gold_execution_qualification() to service_role;

do $$
begin
  if not exists(select 1 from cron.job where jobname='tfa-v136-gold-execution-qualification') then
    perform cron.schedule('tfa-v136-gold-execution-qualification','*/2 * * * *',
      'select public.refresh_v136_gold_execution_qualification();');
  end if;
end $$;
