-- V133.1 Execution Reality
-- Cost-stress research and hard readiness gates before any broker/live-capital path.
-- Stress values are risk-normalized research scenarios, not measured broker costs.

create table if not exists public.gold_shadow_cost_stress (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  outcome_id bigint not null references public.gold_shadow_trade_outcomes(id),
  intent_id bigint not null references public.gold_shadow_trade_intents(id),
  strategy_code text not null,
  scenario_code text not null,
  stress_cost_r numeric not null,
  stress_cost_points numeric not null,
  gross_r numeric not null,
  stress_net_r numeric not null,
  gross_pnl_points numeric not null,
  stress_net_points numeric not null,
  scenario_basis text not null default 'RISK_NORMALIZED_FRICTION_STRESS_NOT_BROKER_MEASUREMENT',
  actual_broker_cost_claim boolean not null default false,
  payload_sha256 text not null,
  unique(outcome_id,scenario_code)
);

alter table public.gold_shadow_cost_stress enable row level security;
revoke all privileges on table public.gold_shadow_cost_stress from public, anon, authenticated;
grant select, insert on table public.gold_shadow_cost_stress to service_role;
grant usage, select on sequence public.gold_shadow_cost_stress_id_seq to service_role;

create index if not exists gold_shadow_cost_stress_outcome_idx on public.gold_shadow_cost_stress(outcome_id);
create index if not exists gold_shadow_cost_stress_intent_idx on public.gold_shadow_cost_stress(intent_id);
create index if not exists gold_shadow_cost_stress_scenario_idx on public.gold_shadow_cost_stress(scenario_code,created_at desc);
create index if not exists gold_shadow_cost_stress_strategy_idx on public.gold_shadow_cost_stress(strategy_code,scenario_code,created_at desc);

create table if not exists public.gold_execution_readiness_snapshots (
  id bigint generated by default as identity primary key,
  evaluated_at timestamptz not null default now(),
  scope_key text not null,
  strategy_code text,
  resolved_sample integer not null,
  source_outcome_max_id bigint not null,
  avg_gross_r numeric,
  avg_net_r_low_stress numeric,
  avg_net_r_moderate_stress numeric,
  avg_net_r_high_stress numeric,
  high_stress_positive_count integer not null,
  high_stress_positive_rate_pct numeric,
  high_stress_total_r numeric,
  sample_state text not null,
  execution_evidence_state text not null,
  broker_adapter_state text not null,
  execution_grade_quote_available boolean not null,
  broker_spread_measured boolean not null,
  slippage_measured boolean not null,
  order_reconciliation_tested boolean not null,
  kill_switch_tested boolean not null,
  live_trading_enabled boolean not null,
  automatic_real_capital boolean not null,
  real_capital_permission text not null,
  blocker_codes jsonb not null default '[]'::jsonb,
  payload_sha256 text not null,
  unique(scope_key,source_outcome_max_id)
);

alter table public.gold_execution_readiness_snapshots enable row level security;
revoke all privileges on table public.gold_execution_readiness_snapshots from public, anon, authenticated;
grant select, insert on table public.gold_execution_readiness_snapshots to service_role;
grant usage, select on sequence public.gold_execution_readiness_snapshots_id_seq to service_role;

create index if not exists gold_execution_readiness_scope_idx
  on public.gold_execution_readiness_snapshots(scope_key,evaluated_at desc);

drop trigger if exists prevent_v133_cost_stress_mutation on public.gold_shadow_cost_stress;
create trigger prevent_v133_cost_stress_mutation
before update or delete on public.gold_shadow_cost_stress
for each row execute function public.prevent_v125_gold_learning_mutation();

drop trigger if exists prevent_v133_readiness_mutation on public.gold_execution_readiness_snapshots;
create trigger prevent_v133_readiness_mutation
before update or delete on public.gold_execution_readiness_snapshots
for each row execute function public.prevent_v125_gold_learning_mutation();

create or replace function public.refresh_v133_gold_execution_reality()
returns jsonb
language plpgsql
set search_path to 'public','extensions','pg_temp'
as $$
declare
  outc record;
  scenario record;
  aggrow record;
  v_cost_r numeric;
  v_cost_points numeric;
  v_net_r numeric;
  v_net_points numeric;
  v_sha text;
  v_sample_state text;
  v_evidence_state text;
  v_blockers jsonb;
  v_inserted_cost integer := 0;
  v_inserted_readiness integer := 0;
begin
  perform public.refresh_v132_gold_shadow_trader();

  for outc in
    select x.id as outcome_id,x.intent_id,x.gross_r,x.gross_pnl_points,
           i.risk_points,i.strategy_code
    from public.gold_shadow_trade_outcomes x
    join public.gold_shadow_trade_intents i on i.id=x.intent_id
    order by x.id
  loop
    for scenario in
      select * from (values
        ('LOW_FRICTION_STRESS',0.02::numeric),
        ('MODERATE_FRICTION_STRESS',0.05::numeric),
        ('HIGH_FRICTION_STRESS',0.10::numeric)
      ) v(scenario_code,stress_cost_r)
    loop
      v_cost_r:=scenario.stress_cost_r;
      v_cost_points:=outc.risk_points*v_cost_r;
      v_net_r:=outc.gross_r-v_cost_r;
      v_net_points:=outc.gross_pnl_points-v_cost_points;
      v_sha:=encode(extensions.digest(convert_to(concat_ws('|',
        outc.outcome_id::text,outc.intent_id::text,outc.strategy_code,
        scenario.scenario_code,v_cost_r::text,v_cost_points::text,
        outc.gross_r::text,v_net_r::text,outc.gross_pnl_points::text,
        v_net_points::text,'RISK_NORMALIZED_FRICTION_STRESS_NOT_BROKER_MEASUREMENT','false'
      ),'UTF8'),'sha256'),'hex');

      insert into public.gold_shadow_cost_stress(
        outcome_id,intent_id,strategy_code,scenario_code,stress_cost_r,stress_cost_points,
        gross_r,stress_net_r,gross_pnl_points,stress_net_points,payload_sha256
      ) values (
        outc.outcome_id,outc.intent_id,outc.strategy_code,scenario.scenario_code,
        v_cost_r,v_cost_points,outc.gross_r,v_net_r,outc.gross_pnl_points,v_net_points,v_sha
      )
      on conflict(outcome_id,scenario_code) do nothing;
      if found then v_inserted_cost:=v_inserted_cost+1; end if;
    end loop;
  end loop;

  for aggrow in
    with scopes as (
      select 'ALL'::text as scope_key,null::text as strategy_code
      union all
      select distinct concat('STRATEGY:',strategy_code),strategy_code
      from public.gold_shadow_trade_intents
    ),
    agg as (
      select scp.scope_key,scp.strategy_code,
        count(distinct o.id)::int as resolved_sample,
        max(o.id)::bigint as source_outcome_max_id,
        avg(o.gross_r)::numeric as avg_gross_r,
        avg(c.stress_net_r) filter(where c.scenario_code='LOW_FRICTION_STRESS')::numeric as avg_low,
        avg(c.stress_net_r) filter(where c.scenario_code='MODERATE_FRICTION_STRESS')::numeric as avg_mod,
        avg(c.stress_net_r) filter(where c.scenario_code='HIGH_FRICTION_STRESS')::numeric as avg_high,
        count(*) filter(where c.scenario_code='HIGH_FRICTION_STRESS' and c.stress_net_r>0)::int as high_positive,
        sum(c.stress_net_r) filter(where c.scenario_code='HIGH_FRICTION_STRESS')::numeric as high_total_r
      from scopes scp
      join public.gold_shadow_trade_intents i
        on scp.strategy_code is null or i.strategy_code=scp.strategy_code
      join public.gold_shadow_trade_outcomes o on o.intent_id=i.id
      join public.gold_shadow_cost_stress c on c.outcome_id=o.id
      group by scp.scope_key,scp.strategy_code
    )
    select * from agg
  loop
    v_sample_state:=case
      when aggrow.resolved_sample<10 then 'WITHHELD_SAMPLE_TOO_SMALL'
      when aggrow.resolved_sample<30 then 'EARLY_SHADOW_EVIDENCE'
      else 'MATURE_SHADOW_EVIDENCE'
    end;
    v_evidence_state:=case
      when aggrow.resolved_sample<30 then 'NOT_EXECUTION_GRADE'
      when aggrow.avg_high is null then 'NOT_EXECUTION_GRADE'
      when aggrow.avg_high<=0 then 'STRESS_ADJUSTED_EDGE_NOT_PROVEN'
      else 'SHADOW_EVIDENCE_POSITIVE_NOT_BROKER_VERIFIED'
    end;
    v_blockers:=jsonb_build_array(
      'BROKER_ADAPTER_NOT_CONNECTED','EXECUTION_GRADE_QUOTE_UNAVAILABLE',
      'BROKER_SPREAD_NOT_MEASURED','SLIPPAGE_NOT_MEASURED',
      'ORDER_RECONCILIATION_NOT_TESTED','KILL_SWITCH_NOT_TESTED',
      case when aggrow.resolved_sample<30 then 'MATURE_SAMPLE_BELOW_30' else 'SHADOW_SAMPLE_MET' end,
      case when aggrow.avg_high is null or aggrow.avg_high<=0
        then 'HIGH_FRICTION_STRESS_EDGE_NOT_PROVEN' else 'HIGH_FRICTION_STRESS_POSITIVE' end
    );
    v_sha:=encode(extensions.digest(convert_to(concat_ws('|',
      aggrow.scope_key,coalesce(aggrow.strategy_code,''),aggrow.resolved_sample::text,
      aggrow.source_outcome_max_id::text,coalesce(round(aggrow.avg_gross_r,6)::text,''),
      coalesce(round(aggrow.avg_low,6)::text,''),coalesce(round(aggrow.avg_mod,6)::text,''),
      coalesce(round(aggrow.avg_high,6)::text,''),aggrow.high_positive::text,
      case when aggrow.resolved_sample>0
        then round((aggrow.high_positive::numeric/aggrow.resolved_sample::numeric)*100,4)::text else '' end,
      coalesce(round(aggrow.high_total_r,6)::text,''),v_sample_state,v_evidence_state,
      'NOT_CONNECTED','false','false','false','false','false','false','false','0R',v_blockers::text
    ),'UTF8'),'sha256'),'hex');

    insert into public.gold_execution_readiness_snapshots(
      scope_key,strategy_code,resolved_sample,source_outcome_max_id,avg_gross_r,
      avg_net_r_low_stress,avg_net_r_moderate_stress,avg_net_r_high_stress,
      high_stress_positive_count,high_stress_positive_rate_pct,high_stress_total_r,
      sample_state,execution_evidence_state,broker_adapter_state,
      execution_grade_quote_available,broker_spread_measured,slippage_measured,
      order_reconciliation_tested,kill_switch_tested,live_trading_enabled,
      automatic_real_capital,real_capital_permission,blocker_codes,payload_sha256
    ) values (
      aggrow.scope_key,aggrow.strategy_code,aggrow.resolved_sample,aggrow.source_outcome_max_id,
      round(aggrow.avg_gross_r,6),round(aggrow.avg_low,6),round(aggrow.avg_mod,6),
      round(aggrow.avg_high,6),aggrow.high_positive,
      case when aggrow.resolved_sample>0
        then round((aggrow.high_positive::numeric/aggrow.resolved_sample::numeric)*100,4) else null end,
      round(aggrow.high_total_r,6),v_sample_state,v_evidence_state,'NOT_CONNECTED',
      false,false,false,false,false,false,false,'0R',v_blockers,v_sha
    )
    on conflict(scope_key,source_outcome_max_id) do nothing;
    if found then v_inserted_readiness:=v_inserted_readiness+1; end if;
  end loop;

  return jsonb_build_object(
    'ok',true,'version','v133-execution-reality-refresh-v1',
    'cost_stress_rows_inserted',v_inserted_cost,
    'readiness_snapshots_inserted',v_inserted_readiness,
    'resolved_shadow_outcomes',(select count(*) from public.gold_shadow_trade_outcomes),
    'stress_rows',(select count(*) from public.gold_shadow_cost_stress),
    'latest_readiness_sample',(select coalesce(max(resolved_sample),0) from public.gold_execution_readiness_snapshots),
    'live_trading_enabled',false,'order_submission_enabled',false,
    'broker_adapter_state','NOT_CONNECTED','automatic_real_capital',false,
    'real_capital_permission','0R','checked_at',now()
  );
end;
$$;

revoke all on function public.refresh_v133_gold_execution_reality() from public, anon, authenticated;
grant execute on function public.refresh_v133_gold_execution_reality() to service_role;

do $$
begin
  if not exists(select 1 from cron.job where jobname='tfa-v133-gold-execution-reality') then
    perform cron.schedule(
      'tfa-v133-gold-execution-reality','*/2 * * * *',
      'select public.refresh_v133_gold_execution_reality();'
    );
  end if;
end $$;
