-- V137.1 Paper Risk Consensus
-- Reconciles two independently-derived paper-risk governors.
-- Any disagreement resolves to the smaller PAPER risk. Live capital remains 0R.

create table if not exists public.gold_paper_risk_consensus_snapshots (
  id bigint generated by default as identity primary key,
  evaluated_at timestamptz not null default now(),
  consensus_version text not null,
  adaptive_snapshot_id bigint references public.gold_adaptive_paper_risk_snapshots(id),
  independent_snapshot_id bigint references public.gold_paper_risk_governor_snapshots(id),
  adaptive_state text not null,
  independent_state text not null,
  adaptive_paper_r numeric not null check (adaptive_paper_r > 0 and adaptive_paper_r <= 1),
  independent_paper_r numeric not null check (independent_paper_r > 0 and independent_paper_r <= 1),
  consensus_paper_r numeric not null check (consensus_paper_r > 0 and consensus_paper_r <= 1),
  models_agree boolean not null,
  consensus_state text not null,
  reason_codes text[] not null default '{}'::text[],
  live_trading_enabled boolean not null default false,
  order_submission_enabled boolean not null default false,
  automatic_real_capital boolean not null default false,
  real_capital_permission text not null default '0R',
  payload_sha256 text not null unique
);

alter table public.gold_paper_risk_consensus_snapshots enable row level security;
revoke all privileges on table public.gold_paper_risk_consensus_snapshots from public, anon, authenticated;
grant select, insert on table public.gold_paper_risk_consensus_snapshots to service_role;
grant usage, select on sequence public.gold_paper_risk_consensus_snapshots_id_seq to service_role;

create index if not exists gold_paper_risk_consensus_eval_idx
  on public.gold_paper_risk_consensus_snapshots(evaluated_at desc);

drop trigger if exists prevent_v1371_risk_consensus_mutation on public.gold_paper_risk_consensus_snapshots;
create trigger prevent_v1371_risk_consensus_mutation
before update or delete on public.gold_paper_risk_consensus_snapshots
for each row execute function public.prevent_v125_gold_learning_mutation();

alter table public.gold_adaptive_paper_decisions
  add column if not exists risk_consensus_snapshot_id bigint
    references public.gold_paper_risk_consensus_snapshots(id);

create index if not exists gold_adaptive_paper_decisions_consensus_idx
  on public.gold_adaptive_paper_decisions(risk_consensus_snapshot_id);

create or replace function public.refresh_v1371_gold_paper_risk_consensus()
returns jsonb
language plpgsql
set search_path to 'public','extensions','pg_temp'
as $$
declare
  v_version constant text := 'v137.1-paper-risk-consensus-v1';
  a jsonb;
  b jsonb;
  v_a_id bigint;
  v_b_id bigint;
  v_a_state text;
  v_b_state text;
  v_a_r numeric;
  v_b_r numeric;
  v_consensus numeric;
  v_agree boolean;
  v_state text;
  v_reasons text[] := '{}'::text[];
  v_sha text;
  v_id bigint;
begin
  a := public.refresh_v137_gold_adaptive_paper_risk();
  b := public.refresh_v137_gold_paper_risk_governor();

  if coalesce((a->>'ok')::boolean,false) is not true
     or coalesce((b->>'ok')::boolean,false) is not true then
    return jsonb_build_object(
      'ok',false,
      'version',v_version,
      'state','FAIL_CLOSED_MODEL_UNAVAILABLE',
      'consensus_paper_r',0.10,
      'models_agree',false,
      'live_trading_enabled',false,
      'order_submission_enabled',false,
      'automatic_real_capital',false,
      'real_capital_permission','0R',
      'checked_at',now()
    );
  end if;

  v_a_id := nullif(a->>'snapshot_id','')::bigint;
  v_b_id := nullif(b->>'snapshot_id','')::bigint;
  v_a_state := coalesce(a->>'risk_state','UNKNOWN');
  v_b_state := coalesce(b->>'state','UNKNOWN');
  v_a_r := nullif(a->>'allowed_paper_r','')::numeric;
  v_b_r := nullif(b->>'recommended_next_paper_r','')::numeric;

  if v_a_r is null or v_b_r is null
     or v_a_r <= 0 or v_a_r > 1
     or v_b_r <= 0 or v_b_r > 1 then
    v_a_r := coalesce(nullif(v_a_r,0),0.10);
    v_b_r := coalesce(nullif(v_b_r,0),0.10);
    v_consensus := 0.10;
    v_agree := false;
    v_state := 'FAIL_CLOSED_MODEL_INVALID';
    v_reasons := array['INVALID_RISK_MODEL_OUTPUT_USE_FLOOR'];
  else
    v_consensus := least(v_a_r,v_b_r);
    v_agree := abs(v_a_r-v_b_r) < 0.000001;

    if v_agree then
      v_state := case
        when v_consensus <= 0.10 then 'CONSENSUS_DEEP_DEFENSE'
        when v_consensus <= 0.25 then 'CONSENSUS_DEFENSE'
        when v_consensus <= 0.50 then 'CONSENSUS_CAUTION'
        when v_consensus <= 0.75 then 'CONSENSUS_MATURING'
        else 'CONSENSUS_FULL_PAPER_BUDGET'
      end;
      v_reasons := array_append(v_reasons,'INDEPENDENT_RISK_MODELS_AGREE');
    else
      v_state := 'MODEL_DISAGREEMENT_DEFENSE';
      v_reasons := array_append(v_reasons,'RISK_MODEL_DISAGREEMENT_USE_MINIMUM');
    end if;
  end if;

  v_reasons := array_append(v_reasons,'CONTROL_V133_REMAINS_FIXED_1R');
  v_reasons := array_append(v_reasons,'V137_CHALLENGER_ONLY');
  v_reasons := array_append(v_reasons,'LIVE_CAPITAL_ALWAYS_0R');

  v_sha := encode(
    extensions.digest(
      convert_to(
        concat_ws('|',
          v_version,coalesce(v_a_id,0)::text,coalesce(v_b_id,0)::text,
          v_a_state,v_b_state,v_a_r::text,v_b_r::text,v_consensus::text,
          v_agree::text,v_state,array_to_string(v_reasons,','),
          'false','false','false','0R'
        ),
        'UTF8'
      ),
      'sha256'
    ),
    'hex'
  );

  insert into public.gold_paper_risk_consensus_snapshots(
    consensus_version,adaptive_snapshot_id,independent_snapshot_id,
    adaptive_state,independent_state,adaptive_paper_r,independent_paper_r,
    consensus_paper_r,models_agree,consensus_state,reason_codes,payload_sha256
  ) values (
    v_version,v_a_id,v_b_id,v_a_state,v_b_state,v_a_r,v_b_r,
    v_consensus,v_agree,v_state,v_reasons,v_sha
  )
  on conflict(payload_sha256) do nothing
  returning id into v_id;

  if v_id is null then
    select id into v_id
    from public.gold_paper_risk_consensus_snapshots
    where payload_sha256=v_sha
    limit 1;
  end if;

  return jsonb_build_object(
    'ok',true,
    'version',v_version,
    'snapshot_id',v_id,
    'state',v_state,
    'models_agree',v_agree,
    'adaptive',jsonb_build_object(
      'snapshot_id',v_a_id,'state',v_a_state,'paper_r',v_a_r
    ),
    'independent',jsonb_build_object(
      'snapshot_id',v_b_id,'state',v_b_state,'paper_r',v_b_r
    ),
    'consensus_paper_r',v_consensus,
    'reason_codes',to_jsonb(v_reasons),
    'control_policy','V133_FIXED_1R',
    'challenger_policy','V137_ADAPTIVE_CONSENSUS',
    'live_trading_enabled',false,
    'order_submission_enabled',false,
    'automatic_real_capital',false,
    'real_capital_permission','0R',
    'checked_at',now()
  );
end;
$$;

revoke all on function public.refresh_v1371_gold_paper_risk_consensus() from public, anon, authenticated;
grant execute on function public.refresh_v1371_gold_paper_risk_consensus() to service_role;

create or replace function public.refresh_v137_gold_adaptive_paper_portfolio()
returns jsonb
language plpgsql
set search_path to 'public','extensions','pg_temp'
as $$
declare
  v_policy constant text := 'v137-adaptive-one-slot-v1';
  v_risk_policy constant text := 'v137-adaptive-paper-risk-v1';
  cfg record;
  risk record;
  cons record;
  i record;
  conflict record;
  so record;
  d record;
  v_decision text;
  v_reason text;
  v_alloc numeric;
  v_conflict bigint;
  v_late boolean;
  v_sha text;
  v_outcome_sha text;
  v_inserted integer := 0;
  v_outcomes integer := 0;
  v_open integer := 0;
  v_allocated integer := 0;
  v_skipped integer := 0;
begin
  perform public.refresh_v132_gold_shadow_trader();
  perform public.refresh_v1371_gold_paper_risk_consensus();

  select * into cfg
  from public.gold_adaptive_paper_risk_policies
  where policy_version=v_risk_policy
  limit 1;

  select * into risk
  from public.gold_adaptive_paper_risk_snapshots
  where policy_version=v_risk_policy
  order by id desc
  limit 1;

  select * into cons
  from public.gold_paper_risk_consensus_snapshots
  order by id desc
  limit 1;

  if cfg.launched_at is null or risk.id is null or cons.id is null then
    return jsonb_build_object(
      'ok',false,'version','v137.1-adaptive-shadow-portfolio-v1',
      'state','FAIL_CLOSED_POLICY_STATE_MISSING',
      'real_capital_permission','0R'
    );
  end if;

  for i in
    select *
    from public.gold_shadow_trade_intents x
    where x.created_at >= cfg.launched_at
      and not exists (
        select 1 from public.gold_adaptive_paper_decisions p
        where p.intent_id=x.id and p.policy_version=v_policy
      )
    order by x.created_at asc,x.id asc
  loop
    select exists(
      select 1 from public.gold_shadow_trade_outcomes x where x.intent_id=i.id
    ) into v_late;

    conflict := null;
    select p.id,p.intent_id,p.source_market_time
    into conflict
    from public.gold_adaptive_paper_decisions p
    left join public.gold_adaptive_paper_outcomes o on o.decision_id=p.id
    where p.policy_version=v_policy
      and p.decision='ALLOCATE'
      and p.source_market_time<i.source_market_time
      and (o.id is null or o.resolved_market_time>i.source_market_time)
    order by p.source_market_time desc,p.id desc
    limit 1;

    if v_late then
      v_decision := 'SKIP';
      v_reason := 'LATE_RESEARCH_EVENT_OUTCOME_ALREADY_KNOWN';
      v_alloc := 0;
      v_conflict := null;
    elsif found then
      v_decision := 'SKIP';
      v_reason := 'ADAPTIVE_SLOT_OCCUPIED';
      v_alloc := 0;
      v_conflict := conflict.id;
    elsif i.live_order_eligible or i.live_trading_enabled then
      v_decision := 'SKIP';
      v_reason := 'FAIL_CLOSED_LIVE_FLAG_PRESENT';
      v_alloc := 0;
      v_conflict := null;
    else
      v_decision := 'ALLOCATE';
      v_reason := case when cons.models_agree
        then 'CONSENSUS_ADAPTIVE_RISK_FREE_SLOT'
        else 'DISAGREEMENT_MIN_RISK_FREE_SLOT'
      end;
      v_alloc := cons.consensus_paper_r;
      v_conflict := null;
    end if;

    v_sha := encode(
      extensions.digest(
        convert_to(
          concat_ws('|',
            v_policy,i.id::text,i.transition_id::text,risk.id::text,cons.id::text,
            v_decision,v_reason,i.side,i.source_market_time::text,
            i.source_price::text,i.stop_price::text,i.target_price::text,
            i.reference_rr::text,v_alloc::text,coalesce(v_conflict::text,''),
            'false','false','false','NOT_CONNECTED'
          ),
          'UTF8'
        ),
        'sha256'
      ),
      'hex'
    );

    insert into public.gold_adaptive_paper_decisions(
      intent_id,transition_id,policy_version,risk_snapshot_id,risk_consensus_snapshot_id,
      decision,decision_reason,side,source_market_time,source_price,stop_price,target_price,
      reference_rr,allocated_paper_r,conflicting_open_decision_id,decision_sha256
    ) values (
      i.id,i.transition_id,v_policy,risk.id,cons.id,
      v_decision,v_reason,i.side,i.source_market_time,i.source_price,i.stop_price,i.target_price,
      i.reference_rr,v_alloc,v_conflict,v_sha
    )
    on conflict(intent_id,policy_version) do nothing;

    if found then v_inserted := v_inserted+1; end if;
  end loop;

  for d in
    select p.*
    from public.gold_adaptive_paper_decisions p
    where p.policy_version=v_policy
      and p.decision='ALLOCATE'
      and not exists (
        select 1 from public.gold_adaptive_paper_outcomes o where o.decision_id=p.id
      )
    order by p.id
  loop
    select * into so
    from public.gold_shadow_trade_outcomes x
    where x.intent_id=d.intent_id
    limit 1;

    if not found then continue; end if;

    v_outcome_sha := encode(
      extensions.digest(
        convert_to(
          concat_ws('|',
            d.id::text,d.intent_id::text,so.id::text,so.resolved_market_time::text,
            so.resolution_code,d.allocated_paper_r::text,so.gross_r::text,
            (so.gross_r*d.allocated_paper_r)::text,so.cost_model_state,
            coalesce((so.net_r*d.allocated_paper_r)::text,'')
          ),
          'UTF8'
        ),
        'sha256'
      ),
      'hex'
    );

    insert into public.gold_adaptive_paper_outcomes(
      decision_id,intent_id,shadow_outcome_id,resolved_market_time,resolution_code,
      allocated_paper_r,gross_trade_r,portfolio_gross_r,cost_model_state,
      portfolio_net_r,outcome_sha256
    ) values (
      d.id,d.intent_id,so.id,so.resolved_market_time,so.resolution_code,
      d.allocated_paper_r,so.gross_r,so.gross_r*d.allocated_paper_r,so.cost_model_state,
      case when so.net_r is null then null else so.net_r*d.allocated_paper_r end,
      v_outcome_sha
    )
    on conflict(decision_id) do nothing;

    if found then v_outcomes := v_outcomes+1; end if;
  end loop;

  perform public.refresh_v1371_gold_paper_risk_consensus();

  select count(*) into v_open
  from public.gold_adaptive_paper_decisions p
  where p.policy_version=v_policy and p.decision='ALLOCATE'
    and not exists (
      select 1 from public.gold_adaptive_paper_outcomes o where o.decision_id=p.id
    );

  select count(*) into v_allocated
  from public.gold_adaptive_paper_decisions
  where policy_version=v_policy and decision='ALLOCATE';

  select count(*) into v_skipped
  from public.gold_adaptive_paper_decisions
  where policy_version=v_policy and decision='SKIP';

  select * into cons
  from public.gold_paper_risk_consensus_snapshots
  order by id desc
  limit 1;

  select * into risk
  from public.gold_adaptive_paper_risk_snapshots
  where policy_version=v_risk_policy
  order by id desc
  limit 1;

  return jsonb_build_object(
    'ok',true,
    'version','v137.1-adaptive-shadow-portfolio-v1',
    'policy_version',v_policy,
    'launched_at',cfg.launched_at,
    'decisions_inserted',v_inserted,
    'outcomes_inserted',v_outcomes,
    'total_decisions',v_allocated+v_skipped,
    'allocated',v_allocated,
    'skipped',v_skipped,
    'open_allocations',v_open,
    'next_paper_risk_r',cons.consensus_paper_r,
    'risk_state',cons.consensus_state,
    'risk_models_agree',cons.models_agree,
    'adaptive_model_r',cons.adaptive_paper_r,
    'independent_model_r',cons.independent_paper_r,
    'consensus_snapshot_id',cons.id,
    'resolved_events',risk.resolved_events,
    'cumulative_gross_r',risk.cumulative_gross_r,
    'max_drawdown_r',risk.max_drawdown_r,
    'loss_streak',risk.loss_streak,
    'max_concurrent_positions',1,
    'resizes_existing_positions',false,
    'retroactive_allocation',false,
    'live_trading_enabled',false,
    'order_submission_enabled',false,
    'automatic_real_capital',false,
    'real_capital_permission','0R',
    'checked_at',now()
  );
end;
$$;

revoke all on function public.refresh_v137_gold_adaptive_paper_portfolio() from public, anon, authenticated;
grant execute on function public.refresh_v137_gold_adaptive_paper_portfolio() to service_role;

do $$
begin
  if not exists(select 1 from cron.job where jobname='tfa-v1371-paper-risk-consensus') then
    perform cron.schedule(
      'tfa-v1371-paper-risk-consensus',
      '*/2 * * * *',
      'select public.refresh_v1371_gold_paper_risk_consensus();'
    );
  end if;
end $$;
