-- V129 Contextual Disagreement Intelligence
-- Freeze review context at the post-review anchor snapshot and learn disagreement evidence by context.
-- No hindsight context reconstruction. No automatic weighting, override, promotion, orders, or capital.

create table if not exists public.gold_disagreement_context_events (
  id bigint generated by default as identity primary key,
  disagreement_event_id bigint not null references public.gold_human_machine_disagreement_events(id),
  review_outcome_id bigint not null references public.gold_human_review_outcomes(id),
  review_event_id bigint not null references public.gold_human_review_events(id),
  review_request_id bigint not null references public.gold_trigger_review_requests(id),
  reviewer_user_id uuid not null,
  classifier_version text not null,
  horizon_minutes integer not null,
  event_class text not null,
  transition_code text not null,
  signal_key text not null,
  direction text not null,
  human_stance text not null,
  comparison_state text not null,
  human_advantage_score integer,
  anchor_id bigint not null references public.gold_human_review_anchors(id),
  anchor_snapshot_id bigint not null references public.gold_live_desk_snapshots(id),
  anchor_market_time timestamptz not null,
  anchor_price numeric not null,
  market_status text,
  session_state text,
  daily_bias text,
  daily_structure text,
  state_phase text,
  path_state text,
  desk_state text,
  long_state text,
  short_state text,
  delayed_feed boolean,
  source_snapshot_sha256 text not null,
  source_disagreement_sha256 text not null,
  context_sha256 text not null,
  created_at timestamptz not null default now(),
  unique(disagreement_event_id)
);

alter table public.gold_disagreement_context_events enable row level security;
revoke all privileges on table public.gold_disagreement_context_events from public, anon, authenticated;
grant select, insert on table public.gold_disagreement_context_events to service_role;
grant usage, select on sequence public.gold_disagreement_context_events_id_seq to service_role;

create index if not exists gold_disagreement_context_review_event_idx
  on public.gold_disagreement_context_events(review_event_id,horizon_minutes);
create index if not exists gold_disagreement_context_request_idx
  on public.gold_disagreement_context_events(review_request_id);
create index if not exists gold_disagreement_context_outcome_idx
  on public.gold_disagreement_context_events(review_outcome_id);
create index if not exists gold_disagreement_context_anchor_idx
  on public.gold_disagreement_context_events(anchor_id);
create index if not exists gold_disagreement_context_snapshot_idx
  on public.gold_disagreement_context_events(anchor_snapshot_id);
create index if not exists gold_disagreement_context_reviewer_idx
  on public.gold_disagreement_context_events(reviewer_user_id,horizon_minutes,created_at desc);

create table if not exists public.gold_disagreement_context_cohort_snapshots (
  id bigint generated by default as identity primary key,
  evaluated_at timestamptz not null default now(),
  classifier_version text not null,
  context_dimension text not null,
  context_value text not null,
  horizon_minutes integer not null,
  scorable_disagreements integer not null,
  human_aligned_count integer not null,
  machine_aligned_count integer not null,
  human_alignment_rate_pct numeric,
  human_wilson_lower_pct numeric,
  source_context_max_id bigint not null,
  evidence_state text not null,
  statistics_publication_state text not null,
  automatic_context_weight numeric,
  automatic_promotion boolean not null default false,
  capital_permission text not null default '0R',
  payload_sha256 text not null,
  unique(classifier_version,context_dimension,context_value,horizon_minutes,source_context_max_id)
);

alter table public.gold_disagreement_context_cohort_snapshots enable row level security;
revoke all privileges on table public.gold_disagreement_context_cohort_snapshots from public, anon, authenticated;
grant select, insert on table public.gold_disagreement_context_cohort_snapshots to service_role;
grant usage, select on sequence public.gold_disagreement_context_cohort_snapshots_id_seq to service_role;

create index if not exists gold_disagreement_context_cohort_lookup_idx
  on public.gold_disagreement_context_cohort_snapshots(
    context_dimension,context_value,horizon_minutes,evaluated_at desc
  );

drop trigger if exists prevent_v129_context_event_update_delete
  on public.gold_disagreement_context_events;
create trigger prevent_v129_context_event_update_delete
before update or delete on public.gold_disagreement_context_events
for each row execute function public.prevent_v125_gold_learning_mutation();

drop trigger if exists prevent_v129_context_cohort_update_delete
  on public.gold_disagreement_context_cohort_snapshots;
create trigger prevent_v129_context_cohort_update_delete
before update or delete on public.gold_disagreement_context_cohort_snapshots
for each row execute function public.prevent_v125_gold_learning_mutation();

create or replace function public.refresh_v129_gold_contextual_disagreement_intelligence()
returns jsonb
language plpgsql
set search_path to 'public','extensions','pg_temp'
as $$
declare
  d record;
  g record;
  v_context_sha text;
  v_rate numeric;
  v_wilson numeric;
  v_state text;
  v_publication text;
  v_inserted_events integer := 0;
  v_inserted_cohorts integer := 0;
begin
  perform public.refresh_v128_gold_disagreement_intelligence();

  for d in
    select
      x.id as disagreement_event_id,
      x.review_outcome_id,
      x.review_event_id,
      x.review_request_id,
      x.reviewer_user_id,
      x.classifier_version,
      x.horizon_minutes,
      r.event_class,
      r.transition_code,
      x.signal_key,
      x.direction,
      x.human_stance,
      x.comparison_state,
      x.human_advantage_score,
      o.anchor_id,
      a.anchor_snapshot_id,
      a.anchor_market_time,
      a.anchor_price,
      s.market_status,
      s.session_state,
      s.daily_bias,
      s.daily_structure,
      s.state_phase,
      s.path_state,
      s.desk_state,
      s.long_state,
      s.short_state,
      s.delayed_feed,
      s.payload_sha256 as source_snapshot_sha256,
      x.payload_sha256 as source_disagreement_sha256
    from public.gold_human_machine_disagreement_events x
    join public.gold_human_review_outcomes o on o.id=x.review_outcome_id
    join public.gold_human_review_anchors a on a.id=o.anchor_id
    join public.gold_live_desk_snapshots s on s.id=a.anchor_snapshot_id
    join public.gold_trigger_review_requests r on r.id=x.review_request_id
    where x.classifier_version='v125.3-event-aware-v2'
      and not exists (
        select 1 from public.gold_disagreement_context_events c
        where c.disagreement_event_id=x.id
      )
    order by x.id
  loop
    v_context_sha:=encode(
      extensions.digest(
        convert_to(
          concat_ws('|',
            d.disagreement_event_id::text,d.review_outcome_id::text,
            d.review_event_id::text,d.review_request_id::text,d.reviewer_user_id::text,
            d.classifier_version,d.horizon_minutes::text,d.event_class,d.transition_code,
            d.signal_key,d.direction,d.human_stance,d.comparison_state,
            coalesce(d.human_advantage_score::text,''),d.anchor_id::text,
            d.anchor_snapshot_id::text,d.anchor_market_time::text,d.anchor_price::text,
            coalesce(d.market_status,''),coalesce(d.session_state,''),
            coalesce(d.daily_bias,''),coalesce(d.daily_structure,''),
            coalesce(d.state_phase,''),coalesce(d.path_state,''),
            coalesce(d.desk_state,''),coalesce(d.long_state,''),
            coalesce(d.short_state,''),coalesce(d.delayed_feed::text,''),
            d.source_snapshot_sha256,d.source_disagreement_sha256
          ),
          'UTF8'
        ),
        'sha256'
      ),
      'hex'
    );

    insert into public.gold_disagreement_context_events(
      disagreement_event_id,review_outcome_id,review_event_id,review_request_id,
      reviewer_user_id,classifier_version,horizon_minutes,event_class,
      transition_code,signal_key,direction,human_stance,comparison_state,
      human_advantage_score,anchor_id,anchor_snapshot_id,anchor_market_time,
      anchor_price,market_status,session_state,daily_bias,daily_structure,
      state_phase,path_state,desk_state,long_state,short_state,delayed_feed,
      source_snapshot_sha256,source_disagreement_sha256,context_sha256
    ) values (
      d.disagreement_event_id,d.review_outcome_id,d.review_event_id,d.review_request_id,
      d.reviewer_user_id,d.classifier_version,d.horizon_minutes,d.event_class,
      d.transition_code,d.signal_key,d.direction,d.human_stance,d.comparison_state,
      d.human_advantage_score,d.anchor_id,d.anchor_snapshot_id,d.anchor_market_time,
      d.anchor_price,d.market_status,d.session_state,d.daily_bias,d.daily_structure,
      d.state_phase,d.path_state,d.desk_state,d.long_state,d.short_state,d.delayed_feed,
      d.source_snapshot_sha256,d.source_disagreement_sha256,v_context_sha
    )
    on conflict(disagreement_event_id) do nothing;

    if found then v_inserted_events:=v_inserted_events+1; end if;
  end loop;

  for g in
    with base as (
      select *
      from public.gold_disagreement_context_events
      where classifier_version='v125.3-event-aware-v2'
        and human_stance='DISAGREE_WITH_MACHINE'
        and human_advantage_score in (-1,1)
    ),
    dimensions as (
      select id,classifier_version,horizon_minutes,human_advantage_score,
             'SESSION_STATE'::text as context_dimension,
             coalesce(nullif(session_state,''),'UNKNOWN') as context_value
      from base
      union all
      select id,classifier_version,horizon_minutes,human_advantage_score,
             'DAILY_STRUCTURE',coalesce(nullif(daily_structure,''),'UNKNOWN')
      from base
      union all
      select id,classifier_version,horizon_minutes,human_advantage_score,
             'STATE_PHASE',coalesce(nullif(state_phase,''),'UNKNOWN')
      from base
      union all
      select id,classifier_version,horizon_minutes,human_advantage_score,
             'DESK_STATE',coalesce(nullif(desk_state,''),'UNKNOWN')
      from base
      union all
      select id,classifier_version,horizon_minutes,human_advantage_score,
             'SIGNAL_FAMILY',coalesce(nullif(transition_code,''),'UNKNOWN')
      from base
    )
    select
      classifier_version,context_dimension,context_value,horizon_minutes,
      count(*)::int as scorable_disagreements,
      count(*) filter(where human_advantage_score=1)::int as human_aligned_count,
      count(*) filter(where human_advantage_score=-1)::int as machine_aligned_count,
      max(id)::bigint as source_context_max_id
    from dimensions
    group by classifier_version,context_dimension,context_value,horizon_minutes
  loop
    v_rate:=g.human_aligned_count::numeric/g.scorable_disagreements::numeric;
    v_wilson:=(
      v_rate + (1.96*1.96)/(2*g.scorable_disagreements)
      - 1.96*sqrt(
          (v_rate*(1-v_rate)/g.scorable_disagreements)
          + ((1.96*1.96)/(4*g.scorable_disagreements*g.scorable_disagreements))
        )
    ) / (1 + (1.96*1.96)/g.scorable_disagreements);

    v_state:=case
      when g.scorable_disagreements<10 then 'WITHHELD_SAMPLE_TOO_SMALL'
      when g.scorable_disagreements<30 then 'EARLY_CONTEXT_EVIDENCE'
      else 'MATURE_CONTEXT_EVIDENCE'
    end;
    v_publication:=case
      when g.scorable_disagreements<10 then 'STATISTICS_WITHHELD'
      else 'DESCRIPTIVE_STATISTICS_AVAILABLE'
    end;

    insert into public.gold_disagreement_context_cohort_snapshots(
      classifier_version,context_dimension,context_value,horizon_minutes,
      scorable_disagreements,human_aligned_count,machine_aligned_count,
      human_alignment_rate_pct,human_wilson_lower_pct,source_context_max_id,
      evidence_state,statistics_publication_state,automatic_context_weight,
      automatic_promotion,capital_permission,payload_sha256
    ) values (
      g.classifier_version,g.context_dimension,g.context_value,g.horizon_minutes,
      g.scorable_disagreements,g.human_aligned_count,g.machine_aligned_count,
      round(v_rate*100,2),round(v_wilson*100,2),g.source_context_max_id,
      v_state,v_publication,null,false,'0R',
      encode(
        extensions.digest(
          convert_to(
            concat_ws('|',
              g.classifier_version,g.context_dimension,g.context_value,
              g.horizon_minutes::text,g.scorable_disagreements::text,
              g.human_aligned_count::text,g.machine_aligned_count::text,
              round(v_rate*100,2)::text,round(v_wilson*100,2)::text,
              g.source_context_max_id::text,v_state,v_publication,'0R'
            ),
            'UTF8'
          ),
          'sha256'
        ),
        'hex'
      )
    )
    on conflict(
      classifier_version,context_dimension,context_value,horizon_minutes,source_context_max_id
    ) do nothing;

    if found then v_inserted_cohorts:=v_inserted_cohorts+1; end if;
  end loop;

  return jsonb_build_object(
    'ok',true,'version','v129-contextual-disagreement-refresh-v1',
    'context_events_inserted',v_inserted_events,
    'cohort_snapshots_inserted',v_inserted_cohorts,
    'context_events',(select count(*) from public.gold_disagreement_context_events),
    'scorable_context_events',(
      select count(*) from public.gold_disagreement_context_events
      where human_stance='DISAGREE_WITH_MACHINE'
        and human_advantage_score in (-1,1)
    ),
    'cohort_snapshots',(select count(*) from public.gold_disagreement_context_cohort_snapshots),
    'automatic_context_weighting',false,'automatic_promotion',false,
    'automatic_orders',false,'capital_permission','0R','checked_at',now()
  );
end;
$$;

revoke all on function public.refresh_v129_gold_contextual_disagreement_intelligence()
from public, anon, authenticated;
grant execute on function public.refresh_v129_gold_contextual_disagreement_intelligence()
to service_role;

do $$
begin
  if not exists (
    select 1 from cron.job where jobname='tfa-v129-gold-contextual-disagreement'
  ) then
    perform cron.schedule(
      'tfa-v129-gold-contextual-disagreement',
      '*/2 * * * *',
      'select public.refresh_v129_gold_contextual_disagreement_intelligence();'
    );
  end if;
end $$;
