-- V127 Review Intelligence
-- Human review -> first valid post-review server capture -> future market-time outcomes -> descriptive reviewer evidence alignment.
-- No trade P&L claim. No automatic weighting, promotion, orders, or capital authority.

create table if not exists public.gold_human_review_anchors (
  id bigint generated by default as identity primary key,
  review_event_id bigint not null references public.gold_human_review_events(id),
  review_request_id bigint not null references public.gold_trigger_review_requests(id),
  reviewer_user_id uuid not null,
  reviewer_role text,
  classifier_version text not null,
  decision text not null,
  signal_key text not null,
  direction text not null,
  review_event_at timestamptz not null,
  anchor_snapshot_id bigint not null references public.gold_live_desk_snapshots(id),
  anchor_captured_at timestamptz not null,
  anchor_market_time timestamptz not null,
  anchor_price numeric not null,
  anchor_delay_seconds numeric not null,
  source_payload_sha256 text not null,
  anchor_sha256 text not null,
  created_at timestamptz not null default now(),
  unique(review_event_id)
);

alter table public.gold_human_review_anchors enable row level security;
revoke all privileges on table public.gold_human_review_anchors from public, anon, authenticated;
grant select, insert on table public.gold_human_review_anchors to service_role;
grant usage, select on sequence public.gold_human_review_anchors_id_seq to service_role;

create index if not exists gold_human_review_anchors_reviewer_idx
  on public.gold_human_review_anchors(reviewer_user_id,created_at desc);
create index if not exists gold_human_review_anchors_snapshot_idx
  on public.gold_human_review_anchors(anchor_snapshot_id);
create index if not exists gold_human_review_anchors_request_idx
  on public.gold_human_review_anchors(review_request_id);

create table if not exists public.gold_human_review_outcomes (
  id bigint generated by default as identity primary key,
  anchor_id bigint not null references public.gold_human_review_anchors(id),
  review_event_id bigint not null references public.gold_human_review_events(id),
  review_request_id bigint not null references public.gold_trigger_review_requests(id),
  reviewer_user_id uuid not null,
  classifier_version text not null,
  decision text not null,
  signal_key text not null,
  direction text not null,
  horizon_minutes integer not null,
  source_market_time timestamptz not null,
  resolved_snapshot_id bigint not null references public.gold_live_desk_snapshots(id),
  resolved_market_time timestamptz not null,
  source_price numeric not null,
  resolved_price numeric not null,
  price_delta numeric not null,
  signed_signal_delta numeric not null,
  signed_human_delta numeric,
  window_high numeric not null,
  window_low numeric not null,
  favorable_excursion numeric not null,
  adverse_excursion numeric not null,
  baseline_signal_state text not null,
  human_alignment_state text not null,
  human_alignment_score integer,
  observation_mode text not null default 'POST_REVIEW_TWO_MINUTE_SNAPSHOT_OBSERVED',
  sequence_claim text not null default 'NOT_INFERRED',
  resolved_at timestamptz not null default now(),
  outcome_sha256 text not null,
  unique(anchor_id,horizon_minutes)
);

alter table public.gold_human_review_outcomes enable row level security;
revoke all privileges on table public.gold_human_review_outcomes from public, anon, authenticated;
grant select, insert on table public.gold_human_review_outcomes to service_role;
grant usage, select on sequence public.gold_human_review_outcomes_id_seq to service_role;

create index if not exists gold_human_review_outcomes_reviewer_idx
  on public.gold_human_review_outcomes(reviewer_user_id,horizon_minutes,resolved_at desc);
create index if not exists gold_human_review_outcomes_event_idx
  on public.gold_human_review_outcomes(review_event_id,horizon_minutes);
create index if not exists gold_human_review_outcomes_request_idx
  on public.gold_human_review_outcomes(review_request_id);
create index if not exists gold_human_review_outcomes_resolved_snapshot_idx
  on public.gold_human_review_outcomes(resolved_snapshot_id);

create table if not exists public.gold_reviewer_intelligence_snapshots (
  id bigint generated by default as identity primary key,
  evaluated_at timestamptz not null default now(),
  reviewer_user_id uuid not null,
  classifier_version text not null,
  horizon_minutes integer not null,
  total_outcomes integer not null,
  scorable_count integer not null,
  aligned_count integer not null,
  contradicted_count integer not null,
  neutral_count integer not null,
  unscored_count integer not null,
  supportive_count integer not null,
  contradictory_count integer not null,
  human_alignment_rate_pct numeric,
  human_wilson_lower_pct numeric,
  baseline_signal_favorable_rate_pct numeric,
  observed_value_add_pp numeric,
  source_outcome_max_id bigint not null,
  intelligence_state text not null,
  statistics_publication_state text not null,
  automatic_weight numeric,
  automatic_promotion boolean not null default false,
  capital_permission text not null default '0R',
  payload_sha256 text not null,
  unique(reviewer_user_id,classifier_version,horizon_minutes,source_outcome_max_id)
);

alter table public.gold_reviewer_intelligence_snapshots enable row level security;
revoke all privileges on table public.gold_reviewer_intelligence_snapshots from public, anon, authenticated;
grant select, insert on table public.gold_reviewer_intelligence_snapshots to service_role;
grant usage, select on sequence public.gold_reviewer_intelligence_snapshots_id_seq to service_role;

create index if not exists gold_reviewer_intelligence_reviewer_idx
  on public.gold_reviewer_intelligence_snapshots(reviewer_user_id,horizon_minutes,evaluated_at desc);

drop trigger if exists prevent_v127_review_anchor_update_delete on public.gold_human_review_anchors;
create trigger prevent_v127_review_anchor_update_delete
before update or delete on public.gold_human_review_anchors
for each row execute function public.prevent_v125_gold_learning_mutation();

drop trigger if exists prevent_v127_review_outcome_update_delete on public.gold_human_review_outcomes;
create trigger prevent_v127_review_outcome_update_delete
before update or delete on public.gold_human_review_outcomes
for each row execute function public.prevent_v125_gold_learning_mutation();

drop trigger if exists prevent_v127_reviewer_intelligence_update_delete on public.gold_reviewer_intelligence_snapshots;
create trigger prevent_v127_reviewer_intelligence_update_delete
before update or delete on public.gold_reviewer_intelligence_snapshots
for each row execute function public.prevent_v125_gold_learning_mutation();

create or replace function public.capture_v127_gold_review_anchors()
returns jsonb
language plpgsql
set search_path to 'public','extensions','pg_temp'
as $$
declare
  e record;
  s record;
  v_inserted integer := 0;
  v_delay numeric;
  v_anchor_sha text;
begin
  for e in
    select
      h.id as review_event_id,
      h.review_request_id,
      h.reviewer_user_id,
      h.reviewer_role,
      h.classifier_version,
      h.decision,
      h.event_at,
      r.signal_key,
      r.direction
    from public.gold_human_review_events h
    join public.gold_trigger_review_requests r on r.id=h.review_request_id
    where h.event_type='HUMAN_EVIDENCE_REVIEW'
      and h.reviewer_user_id is not null
      and h.classifier_version='v125.3-event-aware-v2'
      and r.classifier_version='v125.3-event-aware-v2'
      and r.direction in ('LONG','SHORT')
      and h.decision in ('EVIDENCE_SUPPORTIVE','EVIDENCE_CONTRADICTORY','EVIDENCE_INCONCLUSIVE','DEFERRED')
      and not exists (
        select 1 from public.gold_human_review_anchors a where a.review_event_id=h.id
      )
    order by h.id
  loop
    select *
    into s
    from public.gold_live_desk_snapshots x
    where x.captured_at >= e.event_at
      and x.market_time is not null
      and x.futures_price is not null
    order by x.captured_at asc,x.id asc
    limit 1;

    if not found then continue; end if;

    v_delay:=extract(epoch from (s.captured_at-e.event_at));
    v_anchor_sha:=encode(
      extensions.digest(
        convert_to(
          concat_ws('|',
            e.review_event_id::text,e.review_request_id::text,e.reviewer_user_id::text,
            coalesce(e.reviewer_role,''),e.classifier_version,e.decision,e.signal_key,e.direction,
            e.event_at::text,s.id::text,s.captured_at::text,s.market_time::text,
            s.futures_price::text,v_delay::text,s.payload_sha256
          ),
          'UTF8'
        ),
        'sha256'
      ),
      'hex'
    );

    insert into public.gold_human_review_anchors(
      review_event_id,review_request_id,reviewer_user_id,reviewer_role,
      classifier_version,decision,signal_key,direction,review_event_at,
      anchor_snapshot_id,anchor_captured_at,anchor_market_time,anchor_price,
      anchor_delay_seconds,source_payload_sha256,anchor_sha256
    ) values (
      e.review_event_id,e.review_request_id,e.reviewer_user_id,e.reviewer_role,
      e.classifier_version,e.decision,e.signal_key,e.direction,e.event_at,
      s.id,s.captured_at,s.market_time,s.futures_price,
      v_delay,s.payload_sha256,v_anchor_sha
    )
    on conflict(review_event_id) do nothing;

    if found then v_inserted:=v_inserted+1; end if;
  end loop;

  return jsonb_build_object(
    'ok',true,'version','v127-review-anchor-v1','inserted',v_inserted,
    'total_anchors',(select count(*) from public.gold_human_review_anchors),
    'unanchored_reviews',(
      select count(*)
      from public.gold_human_review_events h
      join public.gold_trigger_review_requests r on r.id=h.review_request_id
      where h.event_type='HUMAN_EVIDENCE_REVIEW'
        and h.reviewer_user_id is not null
        and h.classifier_version='v125.3-event-aware-v2'
        and r.direction in ('LONG','SHORT')
        and not exists (
          select 1 from public.gold_human_review_anchors a where a.review_event_id=h.id
        )
    ),
    'checked_at',now()
  );
end;
$$;

revoke all on function public.capture_v127_gold_review_anchors() from public, anon, authenticated;
grant execute on function public.capture_v127_gold_review_anchors() to service_role;

create or replace function public.resolve_v127_gold_review_outcomes()
returns jsonb
language plpgsql
set search_path to 'public','extensions','pg_temp'
as $$
declare
  a record;
  r record;
  h integer;
  v_target timestamptz;
  v_latest_market_time timestamptz;
  v_low numeric;
  v_high numeric;
  v_signed_signal numeric;
  v_signed_human numeric;
  v_favorable numeric;
  v_adverse numeric;
  v_baseline_state text;
  v_human_state text;
  v_human_score integer;
  v_outcome_sha text;
  v_inserted integer := 0;
begin
  perform public.capture_v127_gold_review_anchors();

  select max(market_time)
  into v_latest_market_time
  from public.gold_live_desk_snapshots
  where market_time is not null and futures_price is not null;

  if v_latest_market_time is null then
    return jsonb_build_object(
      'ok',true,'version','v127-review-outcome-resolver-v1',
      'outcomes_inserted',0,'state','NO_MARKET_TIME_SAMPLES','checked_at',now()
    );
  end if;

  for a in
    select *
    from public.gold_human_review_anchors
    where classifier_version='v125.3-event-aware-v2'
    order by id
  loop
    foreach h in array array[15,30,60,120]
    loop
      if a.anchor_market_time + make_interval(mins=>h) > v_latest_market_time then continue; end if;
      if exists (
        select 1 from public.gold_human_review_outcomes o
        where o.anchor_id=a.id and o.horizon_minutes=h
      ) then continue; end if;

      v_target:=a.anchor_market_time + make_interval(mins=>h);

      select id,market_time,futures_price
      into r
      from public.gold_live_desk_snapshots
      where market_time >= v_target
        and market_time <= v_target + interval '6 minutes'
        and futures_price is not null
      order by market_time asc,id asc
      limit 1;

      if not found then continue; end if;

      select min(x.futures_price),max(x.futures_price)
      into v_low,v_high
      from public.gold_live_desk_snapshots x
      where x.market_time >= a.anchor_market_time
        and x.market_time <= r.market_time
        and x.futures_price is not null;

      if v_low is null or v_high is null then continue; end if;

      v_signed_signal:=case when a.direction='LONG'
        then r.futures_price-a.anchor_price else a.anchor_price-r.futures_price end;
      v_signed_human:=case
        when a.decision='EVIDENCE_SUPPORTIVE' then v_signed_signal
        when a.decision='EVIDENCE_CONTRADICTORY' then -v_signed_signal
        else null
      end;
      v_favorable:=case when a.direction='LONG'
        then v_high-a.anchor_price else a.anchor_price-v_low end;
      v_adverse:=case when a.direction='LONG'
        then a.anchor_price-v_low else v_high-a.anchor_price end;

      v_baseline_state:=case
        when v_signed_signal>0 then 'FAVORABLE_ENDPOINT'
        when v_signed_signal<0 then 'ADVERSE_ENDPOINT'
        else 'NEUTRAL_ENDPOINT'
      end;

      v_human_state:=case
        when a.decision in ('EVIDENCE_INCONCLUSIVE','DEFERRED') then 'UNSCORED_BY_DESIGN'
        when v_signed_human>0 then 'ALIGNED_WITH_SUBSEQUENT_ENDPOINT'
        when v_signed_human<0 then 'CONTRADICTED_BY_SUBSEQUENT_ENDPOINT'
        else 'NEUTRAL_ENDPOINT'
      end;

      v_human_score:=case
        when v_human_state='ALIGNED_WITH_SUBSEQUENT_ENDPOINT' then 1
        when v_human_state='CONTRADICTED_BY_SUBSEQUENT_ENDPOINT' then 0
        else null
      end;

      v_outcome_sha:=encode(
        extensions.digest(
          convert_to(
            concat_ws('|',
              a.id::text,a.review_event_id::text,a.review_request_id::text,
              a.reviewer_user_id::text,a.classifier_version,a.decision,a.signal_key,a.direction,
              h::text,a.anchor_market_time::text,r.id::text,r.market_time::text,
              a.anchor_price::text,r.futures_price::text,(r.futures_price-a.anchor_price)::text,
              v_signed_signal::text,coalesce(v_signed_human::text,''),
              v_high::text,v_low::text,v_favorable::text,v_adverse::text,
              v_baseline_state,v_human_state,coalesce(v_human_score::text,'')
            ),
            'UTF8'
          ),
          'sha256'
        ),
        'hex'
      );

      insert into public.gold_human_review_outcomes(
        anchor_id,review_event_id,review_request_id,reviewer_user_id,
        classifier_version,decision,signal_key,direction,horizon_minutes,
        source_market_time,resolved_snapshot_id,resolved_market_time,
        source_price,resolved_price,price_delta,signed_signal_delta,
        signed_human_delta,window_high,window_low,favorable_excursion,
        adverse_excursion,baseline_signal_state,human_alignment_state,
        human_alignment_score,outcome_sha256
      ) values (
        a.id,a.review_event_id,a.review_request_id,a.reviewer_user_id,
        a.classifier_version,a.decision,a.signal_key,a.direction,h,
        a.anchor_market_time,r.id,r.market_time,a.anchor_price,r.futures_price,
        r.futures_price-a.anchor_price,v_signed_signal,v_signed_human,
        v_high,v_low,v_favorable,v_adverse,v_baseline_state,v_human_state,
        v_human_score,v_outcome_sha
      )
      on conflict(anchor_id,horizon_minutes) do nothing;

      if found then v_inserted:=v_inserted+1; end if;
    end loop;
  end loop;

  return jsonb_build_object(
    'ok',true,'version','v127-review-outcome-resolver-v1',
    'latest_market_time',v_latest_market_time,
    'outcomes_inserted',v_inserted,
    'total_outcomes',(select count(*) from public.gold_human_review_outcomes),
    'checked_at',now(),
    'methodology',jsonb_build_object(
      'post_review_server_capture_anchor',true,
      'market_time_based',true,
      'observation_granularity','TWO_MINUTE_SNAPSHOT_OBSERVED',
      'sequence_inferred',false,
      'trade_pnl_claimed',false,
      'human_decision_scored_as_endpoint_alignment_only',true
    )
  );
end;
$$;

revoke all on function public.resolve_v127_gold_review_outcomes() from public, anon, authenticated;
grant execute on function public.resolve_v127_gold_review_outcomes() to service_role;

create or replace function public.refresh_v127_gold_review_intelligence()
returns jsonb
language plpgsql
set search_path to 'public','extensions','pg_temp'
as $$
declare
  g record;
  v_rate numeric;
  v_wilson numeric;
  v_baseline numeric;
  v_state text;
  v_publication text;
  v_inserted integer := 0;
begin
  perform public.resolve_v127_gold_review_outcomes();

  for g in
    select
      reviewer_user_id,classifier_version,horizon_minutes,
      count(*)::int as total_outcomes,
      count(*) filter(where human_alignment_score is not null)::int as scorable_count,
      count(*) filter(where human_alignment_score=1)::int as aligned_count,
      count(*) filter(where human_alignment_score=0)::int as contradicted_count,
      count(*) filter(where human_alignment_state='NEUTRAL_ENDPOINT')::int as neutral_count,
      count(*) filter(where human_alignment_state='UNSCORED_BY_DESIGN')::int as unscored_count,
      count(*) filter(where decision='EVIDENCE_SUPPORTIVE')::int as supportive_count,
      count(*) filter(where decision='EVIDENCE_CONTRADICTORY')::int as contradictory_count,
      count(*) filter(
        where human_alignment_score is not null
          and baseline_signal_state='FAVORABLE_ENDPOINT'
      )::int as baseline_favorable_count,
      max(id)::bigint as source_outcome_max_id
    from public.gold_human_review_outcomes
    where classifier_version='v125.3-event-aware-v2'
    group by reviewer_user_id,classifier_version,horizon_minutes
  loop
    v_rate:=case when g.scorable_count>0 then g.aligned_count::numeric/g.scorable_count::numeric else null end;
    v_wilson:=case when g.scorable_count>0 then
      (v_rate+(1.96*1.96)/(2*g.scorable_count)
       -1.96*sqrt((v_rate*(1-v_rate)/g.scorable_count)+((1.96*1.96)/(4*g.scorable_count*g.scorable_count))))
      /(1+(1.96*1.96)/g.scorable_count)
      else null end;
    v_baseline:=case when g.scorable_count>0
      then g.baseline_favorable_count::numeric/g.scorable_count::numeric else null end;

    v_state:=case
      when g.scorable_count=0 then 'WAITING_FOR_SCORABLE_REVIEW'
      when g.scorable_count<10 then 'WITHHELD_SAMPLE_TOO_SMALL'
      when g.scorable_count<30 then 'EARLY_REVIEW_EVIDENCE'
      else 'MATURE_REVIEW_EVIDENCE'
    end;

    v_publication:=case
      when g.scorable_count<10 then 'STATISTICS_WITHHELD'
      else 'DESCRIPTIVE_STATISTICS_AVAILABLE'
    end;

    insert into public.gold_reviewer_intelligence_snapshots(
      reviewer_user_id,classifier_version,horizon_minutes,total_outcomes,
      scorable_count,aligned_count,contradicted_count,neutral_count,unscored_count,
      supportive_count,contradictory_count,human_alignment_rate_pct,
      human_wilson_lower_pct,baseline_signal_favorable_rate_pct,
      observed_value_add_pp,source_outcome_max_id,intelligence_state,
      statistics_publication_state,automatic_weight,automatic_promotion,
      capital_permission,payload_sha256
    ) values (
      g.reviewer_user_id,g.classifier_version,g.horizon_minutes,g.total_outcomes,
      g.scorable_count,g.aligned_count,g.contradicted_count,g.neutral_count,g.unscored_count,
      g.supportive_count,g.contradictory_count,
      case when v_rate is null then null else round(v_rate*100,2) end,
      case when v_wilson is null then null else round(v_wilson*100,2) end,
      case when v_baseline is null then null else round(v_baseline*100,2) end,
      case when v_rate is null or v_baseline is null then null else round((v_rate-v_baseline)*100,2) end,
      g.source_outcome_max_id,v_state,v_publication,null,false,'0R',
      encode(
        extensions.digest(
          convert_to(
            concat_ws('|',
              g.reviewer_user_id::text,g.classifier_version,g.horizon_minutes::text,
              g.total_outcomes::text,g.scorable_count::text,g.aligned_count::text,
              g.contradicted_count::text,g.neutral_count::text,g.unscored_count::text,
              g.supportive_count::text,g.contradictory_count::text,
              coalesce(round(v_rate*100,2)::text,''),coalesce(round(v_wilson*100,2)::text,''),
              coalesce(round(v_baseline*100,2)::text,''),coalesce(round((v_rate-v_baseline)*100,2)::text,''),
              g.source_outcome_max_id::text,v_state,v_publication,'0R'
            ),
            'UTF8'
          ),
          'sha256'
        ),
        'hex'
      )
    )
    on conflict(reviewer_user_id,classifier_version,horizon_minutes,source_outcome_max_id) do nothing;

    if found then v_inserted:=v_inserted+1; end if;
  end loop;

  return jsonb_build_object(
    'ok',true,'version','v127-review-intelligence-refresh-v1','inserted',v_inserted,
    'human_review_events',(
      select count(*) from public.gold_human_review_events
      where event_type='HUMAN_EVIDENCE_REVIEW'
        and classifier_version='v125.3-event-aware-v2'
    ),
    'anchors',(select count(*) from public.gold_human_review_anchors),
    'resolved_outcomes',(select count(*) from public.gold_human_review_outcomes),
    'intelligence_snapshots',(select count(*) from public.gold_reviewer_intelligence_snapshots),
    'automatic_weighting',false,'automatic_promotion',false,
    'capital_permission','0R','checked_at',now()
  );
end;
$$;

revoke all on function public.refresh_v127_gold_review_intelligence() from public, anon, authenticated;
grant execute on function public.refresh_v127_gold_review_intelligence() to service_role;

do $$
begin
  if not exists(select 1 from cron.job where jobname='tfa-v127-gold-review-intelligence') then
    perform cron.schedule(
      'tfa-v127-gold-review-intelligence',
      '*/2 * * * *',
      'select public.refresh_v127_gold_review_intelligence();'
    );
  end if;
end $$;
