-- V132 Autonomous Shadow Execution
-- Event-study paper execution for Gold. Uses delayed COMEX structural references only.
-- No broker order route. No real capital. Append-only research ledger.

create table if not exists public.gold_shadow_trade_intents (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  transition_id bigint not null references public.gold_live_desk_transitions(id),
  source_snapshot_id bigint not null references public.gold_live_desk_snapshots(id),
  strategy_code text not null,
  side text not null check (side in ('LONG','SHORT')),
  source_market_time timestamptz not null,
  source_price numeric not null,
  stop_price numeric not null,
  target_price numeric not null,
  extension_target_price numeric,
  risk_points numeric not null,
  reward_points numeric not null,
  reference_rr numeric not null,
  market_status text,
  session_state text,
  daily_bias text,
  daily_structure text,
  desk_state text,
  source_payload_sha256 text not null,
  entry_basis text not null default 'DELAYED_COMEX_REFERENCE',
  simulation_mode text not null default 'EVENT_STUDY_SHADOW_ONLY',
  live_order_eligible boolean not null default false,
  live_trading_enabled boolean not null default false,
  broker_adapter_state text not null default 'NOT_CONNECTED',
  intent_sha256 text not null,
  unique(transition_id)
);

alter table public.gold_shadow_trade_intents enable row level security;
revoke all privileges on table public.gold_shadow_trade_intents from public, anon, authenticated;
grant select, insert on table public.gold_shadow_trade_intents to service_role;
grant usage, select on sequence public.gold_shadow_trade_intents_id_seq to service_role;

create index if not exists gold_shadow_trade_intents_snapshot_idx
  on public.gold_shadow_trade_intents(source_snapshot_id);
create index if not exists gold_shadow_trade_intents_strategy_idx
  on public.gold_shadow_trade_intents(strategy_code,created_at desc);

create table if not exists public.gold_shadow_trade_outcomes (
  id bigint generated by default as identity primary key,
  intent_id bigint not null references public.gold_shadow_trade_intents(id),
  resolved_at timestamptz not null default now(),
  resolution_code text not null,
  resolved_snapshot_id bigint not null references public.gold_live_desk_snapshots(id),
  resolved_market_time timestamptz not null,
  entry_price numeric not null,
  exit_price numeric not null,
  gross_pnl_points numeric not null,
  gross_r numeric not null,
  mfe_points numeric not null,
  mae_points numeric not null,
  elapsed_minutes numeric not null,
  observed_primary_target boolean not null,
  observed_stop boolean not null,
  cost_model_state text not null default 'UNAVAILABLE',
  estimated_cost_points numeric,
  net_pnl_points numeric,
  net_r numeric,
  observation_mode text not null default 'SNAPSHOT_OBSERVED',
  intrabar_sequence_claim text not null default 'NOT_INFERRED',
  outcome_sha256 text not null,
  unique(intent_id)
);

alter table public.gold_shadow_trade_outcomes enable row level security;
revoke all privileges on table public.gold_shadow_trade_outcomes from public, anon, authenticated;
grant select, insert on table public.gold_shadow_trade_outcomes to service_role;
grant usage, select on sequence public.gold_shadow_trade_outcomes_id_seq to service_role;

create index if not exists gold_shadow_trade_outcomes_snapshot_idx
  on public.gold_shadow_trade_outcomes(resolved_snapshot_id);
create index if not exists gold_shadow_trade_outcomes_resolved_idx
  on public.gold_shadow_trade_outcomes(resolved_at desc);

drop trigger if exists prevent_v132_shadow_intent_mutation on public.gold_shadow_trade_intents;
create trigger prevent_v132_shadow_intent_mutation
before update or delete on public.gold_shadow_trade_intents
for each row execute function public.prevent_v125_gold_learning_mutation();

drop trigger if exists prevent_v132_shadow_outcome_mutation on public.gold_shadow_trade_outcomes;
create trigger prevent_v132_shadow_outcome_mutation
before update or delete on public.gold_shadow_trade_outcomes
for each row execute function public.prevent_v125_gold_learning_mutation();

create or replace function public.capture_v130_gold_shadow_trade_intents()
returns jsonb
language plpgsql
set search_path to 'public','extensions','pg_temp'
as $$
declare
  r record;
  v_side text;
  v_strategy text;
  v_stop numeric;
  v_target numeric;
  v_extension numeric;
  v_risk numeric;
  v_reward numeric;
  v_rr numeric;
  v_sha text;
  v_inserted integer := 0;
begin
  for r in
    select
      t.id as transition_id,
      t.transition_code,
      t.to_snapshot_id,
      t.to_market_time,
      t.to_price,
      s.market_status,
      s.session_state,
      s.daily_bias,
      s.daily_structure,
      s.desk_state,
      s.long_invalidation,
      s.long_target_1,
      s.long_target_2,
      s.short_invalidation,
      s.short_target_1,
      s.short_target_2,
      s.payload_sha256
    from public.gold_live_desk_transitions t
    join public.gold_live_desk_snapshots s on s.id=t.to_snapshot_id
    where t.transition_code in ('LONG_RETEST_ZONE_ENTERED','SHORT_FAILURE_THRESHOLD_BREACHED')
      and t.to_market_time is not null
      and t.to_price is not null
      and not exists (
        select 1 from public.gold_shadow_trade_intents i where i.transition_id=t.id
      )
    order by t.id
  loop
    if r.transition_code='LONG_RETEST_ZONE_ENTERED' then
      v_side:='LONG';
      v_strategy:='STRUCTURAL_LONG_RETEST_EVENT';
      v_stop:=r.long_invalidation;
      v_target:=r.long_target_1;
      v_extension:=r.long_target_2;
      v_risk:=r.to_price-v_stop;
      v_reward:=v_target-r.to_price;
    else
      v_side:='SHORT';
      v_strategy:='FAILED_BREAK_SHORT_EVENT';
      v_stop:=r.short_invalidation;
      v_target:=r.short_target_1;
      v_extension:=r.short_target_2;
      v_risk:=v_stop-r.to_price;
      v_reward:=r.to_price-v_target;
    end if;

    if v_stop is null or v_target is null or v_risk is null or v_reward is null
       or v_risk<=0 or v_reward<=0 then
      continue;
    end if;

    v_rr:=v_reward/v_risk;
    v_sha:=encode(
      extensions.digest(
        convert_to(
          concat_ws('|',
            r.transition_id::text,r.to_snapshot_id::text,r.transition_code,
            v_strategy,v_side,r.to_market_time::text,r.to_price::text,
            v_stop::text,v_target::text,coalesce(v_extension::text,''),
            v_risk::text,v_reward::text,v_rr::text,
            coalesce(r.market_status,''),coalesce(r.session_state,''),
            coalesce(r.daily_bias,''),coalesce(r.daily_structure,''),
            coalesce(r.desk_state,''),r.payload_sha256,
            'DELAYED_COMEX_REFERENCE','EVENT_STUDY_SHADOW_ONLY',
            'false','false','NOT_CONNECTED'
          ),
          'UTF8'
        ),
        'sha256'
      ),
      'hex'
    );

    insert into public.gold_shadow_trade_intents(
      transition_id,source_snapshot_id,strategy_code,side,source_market_time,
      source_price,stop_price,target_price,extension_target_price,risk_points,
      reward_points,reference_rr,market_status,session_state,daily_bias,
      daily_structure,desk_state,source_payload_sha256,intent_sha256
    ) values (
      r.transition_id,r.to_snapshot_id,v_strategy,v_side,r.to_market_time,
      r.to_price,v_stop,v_target,v_extension,v_risk,v_reward,v_rr,
      r.market_status,r.session_state,r.daily_bias,r.daily_structure,
      r.desk_state,r.payload_sha256,v_sha
    )
    on conflict(transition_id) do nothing;

    if found then v_inserted:=v_inserted+1; end if;
  end loop;

  return jsonb_build_object(
    'ok',true,'version','v132-shadow-intent-capture-v1',
    'inserted',v_inserted,
    'total_intents',(select count(*) from public.gold_shadow_trade_intents),
    'live_trading_enabled',false,
    'order_submission_enabled',false,
    'broker_adapter_state','NOT_CONNECTED',
    'checked_at',now()
  );
end;
$$;

revoke all on function public.capture_v130_gold_shadow_trade_intents() from public, anon, authenticated;
grant execute on function public.capture_v130_gold_shadow_trade_intents() to service_role;

create or replace function public.resolve_v130_gold_shadow_trade_outcomes()
returns jsonb
language plpgsql
set search_path to 'public','extensions','pg_temp'
as $$
declare
  i record;
  v_latest_market_time timestamptz;
  v_exit_snapshot_id bigint;
  v_exit_market_time timestamptz;
  v_exit_price numeric;
  v_resolution text;
  v_high numeric;
  v_low numeric;
  v_mfe numeric;
  v_mae numeric;
  v_points numeric;
  v_r numeric;
  v_elapsed numeric;
  v_target_hit boolean;
  v_stop_hit boolean;
  v_sha text;
  v_inserted integer := 0;
begin
  perform public.capture_v130_gold_shadow_trade_intents();

  select max(market_time)
  into v_latest_market_time
  from public.gold_live_desk_snapshots
  where market_time is not null and futures_price is not null;

  for i in
    select *
    from public.gold_shadow_trade_intents q
    where not exists (
      select 1 from public.gold_shadow_trade_outcomes o where o.intent_id=q.id
    )
    order by q.id
  loop
    v_exit_snapshot_id:=null;
    v_exit_market_time:=null;
    v_exit_price:=null;
    v_resolution:=null;
    v_target_hit:=false;
    v_stop_hit:=false;

    select s.id,s.market_time,s.futures_price,
      case
        when i.side='LONG' and s.futures_price<=i.stop_price then 'STOP_OBSERVED'
        when i.side='LONG' and s.futures_price>=i.target_price then 'PRIMARY_TARGET_OBSERVED'
        when i.side='SHORT' and s.futures_price>=i.stop_price then 'STOP_OBSERVED'
        when i.side='SHORT' and s.futures_price<=i.target_price then 'PRIMARY_TARGET_OBSERVED'
      end
    into v_exit_snapshot_id,v_exit_market_time,v_exit_price,v_resolution
    from public.gold_live_desk_snapshots s
    where s.market_time>i.source_market_time
      and s.market_time<=i.source_market_time+interval '120 minutes'
      and s.futures_price is not null
      and (
        (i.side='LONG' and (s.futures_price<=i.stop_price or s.futures_price>=i.target_price))
        or
        (i.side='SHORT' and (s.futures_price>=i.stop_price or s.futures_price<=i.target_price))
      )
    order by s.market_time asc,s.id asc
    limit 1;

    if v_exit_snapshot_id is null
       and v_latest_market_time is not null
       and v_latest_market_time>=i.source_market_time+interval '120 minutes' then
      select s.id,s.market_time,s.futures_price,'TIME_EXIT_120M'
      into v_exit_snapshot_id,v_exit_market_time,v_exit_price,v_resolution
      from public.gold_live_desk_snapshots s
      where s.market_time>=i.source_market_time+interval '120 minutes'
        and s.market_time<=i.source_market_time+interval '126 minutes'
        and s.futures_price is not null
      order by s.market_time asc,s.id asc
      limit 1;
    end if;

    if v_exit_snapshot_id is null then continue; end if;

    select max(s.futures_price),min(s.futures_price)
    into v_high,v_low
    from public.gold_live_desk_snapshots s
    where s.market_time>=i.source_market_time
      and s.market_time<=v_exit_market_time
      and s.futures_price is not null;

    if i.side='LONG' then
      v_points:=v_exit_price-i.source_price;
      v_mfe:=v_high-i.source_price;
      v_mae:=i.source_price-v_low;
    else
      v_points:=i.source_price-v_exit_price;
      v_mfe:=i.source_price-v_low;
      v_mae:=v_high-i.source_price;
    end if;

    v_r:=v_points/i.risk_points;
    v_elapsed:=extract(epoch from (v_exit_market_time-i.source_market_time))/60.0;
    v_target_hit:=v_resolution='PRIMARY_TARGET_OBSERVED';
    v_stop_hit:=v_resolution='STOP_OBSERVED';

    v_sha:=encode(
      extensions.digest(
        convert_to(
          concat_ws('|',
            i.id::text,v_resolution,v_exit_snapshot_id::text,
            v_exit_market_time::text,i.source_price::text,v_exit_price::text,
            v_points::text,v_r::text,v_mfe::text,v_mae::text,
            v_elapsed::text,v_target_hit::text,v_stop_hit::text,
            'UNAVAILABLE','','','SNAPSHOT_OBSERVED','NOT_INFERRED'
          ),
          'UTF8'
        ),
        'sha256'
      ),
      'hex'
    );

    insert into public.gold_shadow_trade_outcomes(
      intent_id,resolution_code,resolved_snapshot_id,resolved_market_time,
      entry_price,exit_price,gross_pnl_points,gross_r,mfe_points,mae_points,
      elapsed_minutes,observed_primary_target,observed_stop,outcome_sha256
    ) values (
      i.id,v_resolution,v_exit_snapshot_id,v_exit_market_time,
      i.source_price,v_exit_price,v_points,v_r,v_mfe,v_mae,
      v_elapsed,v_target_hit,v_stop_hit,v_sha
    )
    on conflict(intent_id) do nothing;

    if found then v_inserted:=v_inserted+1; end if;
  end loop;

  return jsonb_build_object(
    'ok',true,'version','v132-shadow-outcome-resolver-v1',
    'outcomes_inserted',v_inserted,
    'total_intents',(select count(*) from public.gold_shadow_trade_intents),
    'resolved_outcomes',(select count(*) from public.gold_shadow_trade_outcomes),
    'open_shadow_intents',(
      select count(*)
      from public.gold_shadow_trade_intents q
      where not exists (
        select 1 from public.gold_shadow_trade_outcomes o where o.intent_id=q.id
      )
    ),
    'live_trading_enabled',false,
    'order_submission_enabled',false,
    'broker_adapter_state','NOT_CONNECTED',
    'checked_at',now()
  );
end;
$$;

revoke all on function public.resolve_v130_gold_shadow_trade_outcomes() from public, anon, authenticated;
grant execute on function public.resolve_v130_gold_shadow_trade_outcomes() to service_role;

create or replace function public.refresh_v132_gold_shadow_trader()
returns jsonb
language sql
security invoker
set search_path to 'public','pg_temp'
as $$
  select public.resolve_v130_gold_shadow_trade_outcomes();
$$;

revoke all on function public.refresh_v132_gold_shadow_trader() from public, anon, authenticated;
grant execute on function public.refresh_v132_gold_shadow_trader() to service_role;

do $$
begin
  if exists (select 1 from cron.job where jobname='tfa-v130-gold-shadow-trader') then
    perform cron.unschedule('tfa-v130-gold-shadow-trader');
  end if;
  if not exists (select 1 from cron.job where jobname='tfa-v132-gold-shadow-trader') then
    perform cron.schedule(
      'tfa-v132-gold-shadow-trader',
      '*/2 * * * *',
      'select public.refresh_v132_gold_shadow_trader();'
    );
  end if;
end $$;
