-- V133 Shadow Portfolio Brain
-- One virtual Gold slot, first eligible V132 event wins the slot until resolved.
-- No future-performance selection, no reviewer signal, no optimization, no live orders.

create table if not exists public.gold_shadow_portfolio_decisions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  intent_id bigint not null references public.gold_shadow_trade_intents(id),
  transition_id bigint not null references public.gold_live_desk_transitions(id),
  policy_version text not null,
  policy_mode text not null default 'ONE_SLOT_FIRST_ELIGIBLE',
  decision text not null check (decision in ('ALLOCATE','SKIP')),
  decision_reason text not null,
  side text not null,
  source_market_time timestamptz not null,
  source_price numeric not null,
  reference_rr numeric not null,
  max_concurrent_positions integer not null default 1,
  shadow_risk_budget_r numeric not null default 1,
  allocated_risk_r numeric not null default 0,
  conflicting_open_intent_id bigint references public.gold_shadow_trade_intents(id),
  future_performance_used boolean not null default false,
  reviewer_signal_used boolean not null default false,
  live_order_eligible boolean not null default false,
  live_trading_enabled boolean not null default false,
  broker_adapter_state text not null default 'NOT_CONNECTED',
  decision_sha256 text not null,
  unique(intent_id,policy_version)
);

alter table public.gold_shadow_portfolio_decisions enable row level security;
revoke all privileges on table public.gold_shadow_portfolio_decisions from public, anon, authenticated;
grant select, insert on table public.gold_shadow_portfolio_decisions to service_role;
grant usage, select on sequence public.gold_shadow_portfolio_decisions_id_seq to service_role;

create index if not exists gold_shadow_portfolio_decisions_intent_idx
  on public.gold_shadow_portfolio_decisions(intent_id);
create index if not exists gold_shadow_portfolio_decisions_transition_idx
  on public.gold_shadow_portfolio_decisions(transition_id);
create index if not exists gold_shadow_portfolio_decisions_time_idx
  on public.gold_shadow_portfolio_decisions(source_market_time,decision);

create table if not exists public.gold_shadow_portfolio_outcomes (
  id bigint generated by default as identity primary key,
  decision_id bigint not null references public.gold_shadow_portfolio_decisions(id),
  intent_id bigint not null references public.gold_shadow_trade_intents(id),
  shadow_outcome_id bigint not null references public.gold_shadow_trade_outcomes(id),
  resolved_at timestamptz not null default now(),
  resolved_market_time timestamptz not null,
  resolution_code text not null,
  allocated_risk_r numeric not null,
  gross_trade_r numeric not null,
  portfolio_gross_r numeric not null,
  cost_model_state text not null,
  portfolio_net_r numeric,
  outcome_sha256 text not null,
  unique(decision_id),
  unique(shadow_outcome_id)
);

alter table public.gold_shadow_portfolio_outcomes enable row level security;
revoke all privileges on table public.gold_shadow_portfolio_outcomes from public, anon, authenticated;
grant select, insert on table public.gold_shadow_portfolio_outcomes to service_role;
grant usage, select on sequence public.gold_shadow_portfolio_outcomes_id_seq to service_role;

create index if not exists gold_shadow_portfolio_outcomes_intent_idx
  on public.gold_shadow_portfolio_outcomes(intent_id);
create index if not exists gold_shadow_portfolio_outcomes_resolved_idx
  on public.gold_shadow_portfolio_outcomes(resolved_at desc);

drop trigger if exists prevent_v133_portfolio_decision_mutation on public.gold_shadow_portfolio_decisions;
create trigger prevent_v133_portfolio_decision_mutation
before update or delete on public.gold_shadow_portfolio_decisions
for each row execute function public.prevent_v125_gold_learning_mutation();

drop trigger if exists prevent_v133_portfolio_outcome_mutation on public.gold_shadow_portfolio_outcomes;
create trigger prevent_v133_portfolio_outcome_mutation
before update or delete on public.gold_shadow_portfolio_outcomes
for each row execute function public.prevent_v125_gold_learning_mutation();

create or replace function public.refresh_v133_gold_shadow_portfolio()
returns jsonb
language plpgsql
set search_path to 'public','extensions','pg_temp'
as $$
declare
  v_policy constant text := 'v133-one-slot-first-eligible-v1';
  i record;
  conflict record;
  d record;
  o record;
  v_decision text;
  v_reason text;
  v_allocated numeric;
  v_conflict_id bigint;
  v_sha text;
  v_outcome_sha text;
  v_decisions_inserted integer := 0;
  v_outcomes_inserted integer := 0;
begin
  perform public.refresh_v132_gold_shadow_trader();

  for i in
    select *
    from public.gold_shadow_trade_intents x
    where not exists (
      select 1 from public.gold_shadow_portfolio_decisions p
      where p.intent_id=x.id and p.policy_version=v_policy
    )
    order by x.source_market_time asc,x.id asc
  loop
    conflict:=null;
    select p.intent_id,p.source_market_time
    into conflict
    from public.gold_shadow_portfolio_decisions p
    left join public.gold_shadow_trade_outcomes so on so.intent_id=p.intent_id
    where p.policy_version=v_policy
      and p.decision='ALLOCATE'
      and p.source_market_time<i.source_market_time
      and (so.id is null or so.resolved_market_time>i.source_market_time)
    order by p.source_market_time desc,p.id desc
    limit 1;

    if found then
      v_decision:='SKIP';
      v_reason:='SHADOW_SLOT_OCCUPIED';
      v_allocated:=0;
      v_conflict_id:=conflict.intent_id;
    else
      v_decision:='ALLOCATE';
      v_reason:='FIRST_ELIGIBLE_FREE_SLOT';
      v_allocated:=1;
      v_conflict_id:=null;
    end if;

    v_sha:=encode(
      extensions.digest(
        convert_to(
          concat_ws('|',
            v_policy,i.id::text,i.transition_id::text,v_decision,v_reason,
            i.side,i.source_market_time::text,i.source_price::text,
            i.reference_rr::text,'1','1',v_allocated::text,
            coalesce(v_conflict_id::text,''),
            'false','false','false','false','NOT_CONNECTED'
          ),
          'UTF8'
        ),
        'sha256'
      ),
      'hex'
    );

    insert into public.gold_shadow_portfolio_decisions(
      intent_id,transition_id,policy_version,decision,decision_reason,
      side,source_market_time,source_price,reference_rr,
      allocated_risk_r,conflicting_open_intent_id,decision_sha256
    ) values (
      i.id,i.transition_id,v_policy,v_decision,v_reason,
      i.side,i.source_market_time,i.source_price,i.reference_rr,
      v_allocated,v_conflict_id,v_sha
    )
    on conflict(intent_id,policy_version) do nothing;

    if found then v_decisions_inserted:=v_decisions_inserted+1; end if;
  end loop;

  for d in
    select p.*
    from public.gold_shadow_portfolio_decisions p
    where p.policy_version=v_policy
      and p.decision='ALLOCATE'
      and not exists (
        select 1 from public.gold_shadow_portfolio_outcomes po where po.decision_id=p.id
      )
    order by p.id
  loop
    select *
    into o
    from public.gold_shadow_trade_outcomes x
    where x.intent_id=d.intent_id
    limit 1;

    if not found then continue; end if;

    v_outcome_sha:=encode(
      extensions.digest(
        convert_to(
          concat_ws('|',
            d.id::text,d.intent_id::text,o.id::text,o.resolved_market_time::text,
            o.resolution_code,d.allocated_risk_r::text,o.gross_r::text,
            (o.gross_r*d.allocated_risk_r)::text,o.cost_model_state,
            coalesce((o.net_r*d.allocated_risk_r)::text,'')
          ),
          'UTF8'
        ),
        'sha256'
      ),
      'hex'
    );

    insert into public.gold_shadow_portfolio_outcomes(
      decision_id,intent_id,shadow_outcome_id,resolved_market_time,
      resolution_code,allocated_risk_r,gross_trade_r,portfolio_gross_r,
      cost_model_state,portfolio_net_r,outcome_sha256
    ) values (
      d.id,d.intent_id,o.id,o.resolved_market_time,
      o.resolution_code,d.allocated_risk_r,o.gross_r,
      o.gross_r*d.allocated_risk_r,o.cost_model_state,
      case when o.net_r is null then null else o.net_r*d.allocated_risk_r end,
      v_outcome_sha
    )
    on conflict(decision_id) do nothing;

    if found then v_outcomes_inserted:=v_outcomes_inserted+1; end if;
  end loop;

  return jsonb_build_object(
    'ok',true,
    'version','v133-shadow-portfolio-v1',
    'policy_version',v_policy,
    'decisions_inserted',v_decisions_inserted,
    'outcomes_inserted',v_outcomes_inserted,
    'total_decisions',(
      select count(*) from public.gold_shadow_portfolio_decisions where policy_version=v_policy
    ),
    'allocated',(
      select count(*) from public.gold_shadow_portfolio_decisions
      where policy_version=v_policy and decision='ALLOCATE'
    ),
    'skipped_overlap',(
      select count(*) from public.gold_shadow_portfolio_decisions
      where policy_version=v_policy and decision='SKIP'
    ),
    'resolved_allocations',(select count(*) from public.gold_shadow_portfolio_outcomes),
    'open_allocations',(
      select count(*)
      from public.gold_shadow_portfolio_decisions p
      where p.policy_version=v_policy and p.decision='ALLOCATE'
        and not exists (
          select 1 from public.gold_shadow_portfolio_outcomes po where po.decision_id=p.id
        )
    ),
    'max_concurrent_positions',1,
    'shadow_risk_budget_r',1,
    'live_trading_enabled',false,
    'order_submission_enabled',false,
    'real_capital_permission','0R',
    'checked_at',now()
  );
end;
$$;

revoke all on function public.refresh_v133_gold_shadow_portfolio() from public, anon, authenticated;
grant execute on function public.refresh_v133_gold_shadow_portfolio() to service_role;

do $$
begin
  if not exists (select 1 from cron.job where jobname='tfa-v133-gold-shadow-portfolio') then
    perform cron.schedule(
      'tfa-v133-gold-shadow-portfolio',
      '*/2 * * * *',
      'select public.refresh_v133_gold_shadow_portfolio();'
    );
  end if;
end $$;
