-- V134 Broker Adapter Lab
-- Deterministic simulation of adapter lifecycle, idempotency, reconciliation, kill-switch and denial paths.
-- This migration intentionally contains no live broker route and cannot submit a real order.

create table if not exists public.gold_broker_adapter_lab_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  suite_version text not null,
  adapter_mode text not null default 'SIMULATED_ONLY',
  quote_source text not null default 'DETERMINISTIC_TEST_VECTOR',
  real_broker_connected boolean not null default false,
  live_order_route_present boolean not null default false,
  live_order_submission_enabled boolean not null default false,
  kill_switch_default_on boolean not null default true,
  run_sha256 text not null unique
);

alter table public.gold_broker_adapter_lab_runs enable row level security;
revoke all privileges on table public.gold_broker_adapter_lab_runs from public, anon, authenticated;
grant select, insert on table public.gold_broker_adapter_lab_runs to service_role;
grant usage, select on sequence public.gold_broker_adapter_lab_runs_id_seq to service_role;
create index if not exists gold_broker_adapter_lab_runs_started_idx
  on public.gold_broker_adapter_lab_runs(started_at desc);

create table if not exists public.gold_broker_adapter_lab_events (
  id bigint generated by default as identity primary key,
  run_id bigint not null references public.gold_broker_adapter_lab_runs(id),
  event_seq integer not null,
  event_at timestamptz not null default now(),
  scenario_code text not null,
  event_type text not null,
  client_order_id text not null,
  idempotency_key text not null,
  side text not null check (side in ('LONG','SHORT','NONE')),
  requested_r numeric,
  requested_price numeric,
  simulated_fill_price numeric,
  state text not null,
  real_order_sent boolean not null default false,
  payload jsonb not null default '{}'::jsonb,
  event_sha256 text not null,
  unique(run_id,event_seq),
  unique(run_id,event_sha256)
);

alter table public.gold_broker_adapter_lab_events enable row level security;
revoke all privileges on table public.gold_broker_adapter_lab_events from public, anon, authenticated;
grant select, insert on table public.gold_broker_adapter_lab_events to service_role;
grant usage, select on sequence public.gold_broker_adapter_lab_events_id_seq to service_role;
create index if not exists gold_broker_adapter_lab_events_run_idx
  on public.gold_broker_adapter_lab_events(run_id,event_seq);
create index if not exists gold_broker_adapter_lab_events_key_idx
  on public.gold_broker_adapter_lab_events(idempotency_key,event_at desc);

create table if not exists public.gold_broker_adapter_lab_results (
  id bigint generated by default as identity primary key,
  run_id bigint not null unique references public.gold_broker_adapter_lab_runs(id),
  evaluated_at timestamptz not null default now(),
  dry_run_lifecycle_pass boolean not null,
  idempotency_pass boolean not null,
  reconciliation_pass boolean not null,
  kill_switch_pass boolean not null,
  live_route_denial_pass boolean not null,
  unauthorized_submit_blocked boolean not null,
  real_orders_sent integer not null,
  orphan_event_count integer not null,
  result_state text not null,
  production_broker_readiness text not null default 'NOT_TESTED',
  payload_sha256 text not null
);

alter table public.gold_broker_adapter_lab_results enable row level security;
revoke all privileges on table public.gold_broker_adapter_lab_results from public, anon, authenticated;
grant select, insert on table public.gold_broker_adapter_lab_results to service_role;
grant usage, select on sequence public.gold_broker_adapter_lab_results_id_seq to service_role;
create index if not exists gold_broker_adapter_lab_results_eval_idx
  on public.gold_broker_adapter_lab_results(evaluated_at desc);

drop trigger if exists prevent_v134_lab_run_mutation on public.gold_broker_adapter_lab_runs;
create trigger prevent_v134_lab_run_mutation
before update or delete on public.gold_broker_adapter_lab_runs
for each row execute function public.prevent_v125_gold_learning_mutation();

drop trigger if exists prevent_v134_lab_event_mutation on public.gold_broker_adapter_lab_events;
create trigger prevent_v134_lab_event_mutation
before update or delete on public.gold_broker_adapter_lab_events
for each row execute function public.prevent_v125_gold_learning_mutation();

drop trigger if exists prevent_v134_lab_result_mutation on public.gold_broker_adapter_lab_results;
create trigger prevent_v134_lab_result_mutation
before update or delete on public.gold_broker_adapter_lab_results
for each row execute function public.prevent_v125_gold_learning_mutation();

create or replace function public.run_v134_gold_broker_adapter_selftest()
returns jsonb
language plpgsql
set search_path to 'public','extensions','pg_temp'
as $$
declare
  v_suite constant text := 'v134-broker-adapter-lab-v1';
  v_run_id bigint; v_run_sha text; v_seed text; v_events integer;
  v_real_orders integer; v_orphans integer; v_dry boolean; v_idem boolean;
  v_recon boolean; v_kill boolean; v_live_denial boolean; v_unauth boolean;
  v_state text; v_result_sha text;
begin
  v_seed:=concat_ws('|',v_suite,date_trunc('hour',now())::text,'SIMULATED_ONLY','DETERMINISTIC_TEST_VECTOR');
  v_run_sha:=encode(extensions.digest(convert_to(v_seed,'UTF8'),'sha256'),'hex');

  insert into public.gold_broker_adapter_lab_runs(
    suite_version,adapter_mode,quote_source,real_broker_connected,
    live_order_route_present,live_order_submission_enabled,kill_switch_default_on,run_sha256
  ) values (
    v_suite,'SIMULATED_ONLY','DETERMINISTIC_TEST_VECTOR',false,false,false,true,v_run_sha
  )
  on conflict(run_sha256) do nothing returning id into v_run_id;

  if v_run_id is null then
    select id into v_run_id from public.gold_broker_adapter_lab_runs where run_sha256=v_run_sha limit 1;
  end if;

  insert into public.gold_broker_adapter_lab_events(
    run_id,event_seq,scenario_code,event_type,client_order_id,idempotency_key,
    side,requested_r,requested_price,simulated_fill_price,state,real_order_sent,payload,event_sha256
  )
  select v_run_id,x.seq,x.scenario,x.etype,x.client_id,x.idem,x.side,x.req_r,x.req_px,x.fill_px,x.state,false,
         x.payload,
         encode(extensions.digest(convert_to(concat_ws('|',
           v_run_id::text,x.seq::text,x.scenario,x.etype,x.client_id,x.idem,x.side,
           coalesce(x.req_r::text,''),coalesce(x.req_px::text,''),coalesce(x.fill_px::text,''),
           x.state,'false',x.payload::text
         ),'UTF8'),'sha256'),'hex')
  from (values
    (1,'DRY_RUN_LIFECYCLE','ORDER_PREPARED','DRY-ORDER-A','IDEM-A','LONG',0.10::numeric,4200.00::numeric,null::numeric,'PREPARED',jsonb_build_object('route','SIMULATED_ONLY')),
    (2,'DRY_RUN_LIFECYCLE','DRY_RUN_ACK','DRY-ORDER-A','IDEM-A','LONG',0.10::numeric,4200.00::numeric,null::numeric,'ACKNOWLEDGED',jsonb_build_object('broker_order_id','SIM-ACK-A')),
    (3,'DRY_RUN_LIFECYCLE','DRY_RUN_FILL','DRY-ORDER-A','IDEM-A','LONG',0.10::numeric,4200.00::numeric,4200.25::numeric,'FILLED_SIMULATED',jsonb_build_object('fill_basis','DETERMINISTIC_TEST_VECTOR')),
    (4,'IDEMPOTENCY','DUPLICATE_BLOCKED','DRY-ORDER-A-DUP','IDEM-A','LONG',0.10::numeric,4200.00::numeric,null::numeric,'BLOCKED_DUPLICATE_KEY',jsonb_build_object('duplicate_of','DRY-ORDER-A')),
    (5,'KILL_SWITCH','ORDER_PREPARED','DRY-ORDER-KILL','IDEM-KILL','SHORT',0.10::numeric,4200.00::numeric,null::numeric,'PREPARED',jsonb_build_object('kill_switch',true)),
    (6,'KILL_SWITCH','KILL_SWITCH_BLOCKED','DRY-ORDER-KILL','IDEM-KILL','SHORT',0.10::numeric,4200.00::numeric,null::numeric,'BLOCKED_KILL_SWITCH',jsonb_build_object('kill_switch',true)),
    (7,'LIVE_ROUTE_DENIAL','LIVE_SUBMIT_BLOCKED','DRY-ORDER-LIVE','IDEM-LIVE','LONG',0.10::numeric,4200.00::numeric,null::numeric,'BLOCKED_NO_LIVE_ROUTE',jsonb_build_object('live_route_present',false)),
    (8,'AUTHZ_DENIAL','UNAUTHORIZED_SUBMIT_BLOCKED','DRY-ORDER-AUTHZ','IDEM-AUTHZ','NONE',null::numeric,null::numeric,null::numeric,'BLOCKED_UNAUTHORIZED',jsonb_build_object('authorized',false))
  ) as x(seq,scenario,etype,client_id,idem,side,req_r,req_px,fill_px,state,payload)
  on conflict(run_id,event_seq) do nothing;

  select count(*) into v_events from public.gold_broker_adapter_lab_events where run_id=v_run_id;
  select count(*) into v_real_orders from public.gold_broker_adapter_lab_events where run_id=v_run_id and real_order_sent=true;
  select count(*) into v_orphans
  from public.gold_broker_adapter_lab_events e
  where e.run_id=v_run_id and not exists(select 1 from public.gold_broker_adapter_lab_runs r where r.id=e.run_id);

  select
    count(*) filter(where scenario_code='DRY_RUN_LIFECYCLE' and event_type='ORDER_PREPARED')=1
      and count(*) filter(where scenario_code='DRY_RUN_LIFECYCLE' and event_type='DRY_RUN_ACK')=1
      and count(*) filter(where scenario_code='DRY_RUN_LIFECYCLE' and event_type='DRY_RUN_FILL')=1,
    count(*) filter(where scenario_code='IDEMPOTENCY' and event_type='DUPLICATE_BLOCKED')=1,
    count(*) filter(where scenario_code='KILL_SWITCH' and event_type='KILL_SWITCH_BLOCKED')=1,
    count(*) filter(where scenario_code='LIVE_ROUTE_DENIAL' and event_type='LIVE_SUBMIT_BLOCKED')=1,
    count(*) filter(where scenario_code='AUTHZ_DENIAL' and event_type='UNAUTHORIZED_SUBMIT_BLOCKED')=1
  into v_dry,v_idem,v_kill,v_live_denial,v_unauth
  from public.gold_broker_adapter_lab_events where run_id=v_run_id;

  v_recon:=v_dry and v_orphans=0;
  v_state:=case
    when v_dry and v_idem and v_recon and v_kill and v_live_denial and v_unauth and v_real_orders=0
      then 'PASS_SIMULATION_ONLY' else 'FAIL_CLOSED' end;

  v_result_sha:=encode(extensions.digest(convert_to(concat_ws('|',
    v_run_id::text,v_dry::text,v_idem::text,v_recon::text,v_kill::text,
    v_live_denial::text,v_unauth::text,v_real_orders::text,v_orphans::text,v_state,'NOT_TESTED'
  ),'UTF8'),'sha256'),'hex');

  insert into public.gold_broker_adapter_lab_results(
    run_id,dry_run_lifecycle_pass,idempotency_pass,reconciliation_pass,kill_switch_pass,
    live_route_denial_pass,unauthorized_submit_blocked,real_orders_sent,orphan_event_count,
    result_state,production_broker_readiness,payload_sha256
  ) values (
    v_run_id,v_dry,v_idem,v_recon,v_kill,v_live_denial,v_unauth,v_real_orders,v_orphans,
    v_state,'NOT_TESTED',v_result_sha
  )
  on conflict(run_id) do nothing;

  return jsonb_build_object(
    'ok',v_state='PASS_SIMULATION_ONLY','version',v_suite,'run_id',v_run_id,
    'event_count',v_events,'dry_run_lifecycle_pass',v_dry,'idempotency_pass',v_idem,
    'reconciliation_pass',v_recon,'kill_switch_pass',v_kill,
    'live_route_denial_pass',v_live_denial,'unauthorized_submit_blocked',v_unauth,
    'real_orders_sent',v_real_orders,'orphan_event_count',v_orphans,'result_state',v_state,
    'production_broker_readiness','NOT_TESTED','live_order_route_present',false,
    'live_order_submission_enabled',false,'real_capital_permission','0R','checked_at',now()
  );
end;
$$;

revoke all on function public.run_v134_gold_broker_adapter_selftest() from public, anon, authenticated;
grant execute on function public.run_v134_gold_broker_adapter_selftest() to service_role;

do $$
begin
  if not exists(select 1 from cron.job where jobname='tfa-v134-gold-broker-adapter-lab') then
    perform cron.schedule(
      'tfa-v134-gold-broker-adapter-lab','17 * * * *',
      'select public.run_v134_gold_broker_adapter_selftest();'
    );
  end if;
end $$;
