-- V137 Adaptive Paper Risk Governor
-- Parallel challenger to the fixed-1R V133 paper portfolio.
-- This policy governs PAPER risk only. It cannot enable live trading, broker routing, or real capital.

create table if not exists public.gold_adaptive_paper_risk_policies (
  policy_version text primary key,
  launched_at timestamptz not null default now(),
  max_paper_r numeric not null default 1 check (max_paper_r > 0 and max_paper_r <= 1),
  min_paper_r numeric not null default 0.10 check (min_paper_r > 0 and min_paper_r <= 1),
  discovery_sample integer not null default 5 check (discovery_sample >= 1),
  mature_sample integer not null default 30 check (mature_sample >= discovery_sample),
  drawdown_defense_r numeric not null default 2 check (drawdown_defense_r > 0),
  deep_defense_r numeric not null default 3 check (deep_defense_r > drawdown_defense_r),
  loss_streak_defense integer not null default 2 check (loss_streak_defense >= 1),
  loss_streak_deep integer not null default 4 check (loss_streak_deep > loss_streak_defense),
  live_trading_enabled boolean not null default false,
  order_submission_enabled boolean not null default false,
  real_capital_permission text not null default '0R'
);

insert into public.gold_adaptive_paper_risk_policies(
  policy_version,max_paper_r,min_paper_r,discovery_sample,mature_sample,
  drawdown_defense_r,deep_defense_r,loss_streak_defense,loss_streak_deep
) values (
  'v137-adaptive-paper-risk-v1',1,0.10,5,30,2,3,2,4
)
on conflict(policy_version) do nothing;

alter table public.gold_adaptive_paper_risk_policies enable row level security;
revoke all privileges on table public.gold_adaptive_paper_risk_policies from public, anon, authenticated;
grant select on table public.gold_adaptive_paper_risk_policies to service_role;

drop trigger if exists prevent_v137_policy_mutation on public.gold_adaptive_paper_risk_policies;
create trigger prevent_v137_policy_mutation
before update or delete on public.gold_adaptive_paper_risk_policies
for each row execute function public.prevent_v125_gold_learning_mutation();

create table if not exists public.gold_adaptive_paper_risk_snapshots (
  id bigint generated by default as identity primary key,
  evaluated_at timestamptz not null default now(),
  policy_version text not null references public.gold_adaptive_paper_risk_policies(policy_version),
  baseline_source text not null,
  resolved_events integer not null,
  cumulative_gross_r numeric not null,
  max_drawdown_r numeric not null,
  loss_streak integer not null,
  allowed_paper_r numeric not null check (allowed_paper_r > 0 and allowed_paper_r <= 1),
  risk_state text not null,
  reason_codes jsonb not null default '[]'::jsonb,
  current_open_positions integer not null default 0,
  live_trading_enabled boolean not null default false,
  order_submission_enabled boolean not null default false,
  real_capital_permission text not null default '0R',
  payload_sha256 text not null unique
);

alter table public.gold_adaptive_paper_risk_snapshots enable row level security;
revoke all privileges on table public.gold_adaptive_paper_risk_snapshots from public, anon, authenticated;
grant select, insert on table public.gold_adaptive_paper_risk_snapshots to service_role;
grant usage, select on sequence public.gold_adaptive_paper_risk_snapshots_id_seq to service_role;

create index if not exists gold_adaptive_paper_risk_snapshots_eval_idx
  on public.gold_adaptive_paper_risk_snapshots(evaluated_at desc);

drop trigger if exists prevent_v137_risk_snapshot_mutation on public.gold_adaptive_paper_risk_snapshots;
create trigger prevent_v137_risk_snapshot_mutation
before update or delete on public.gold_adaptive_paper_risk_snapshots
for each row execute function public.prevent_v125_gold_learning_mutation();

create table if not exists public.gold_adaptive_paper_decisions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  intent_id bigint not null references public.gold_shadow_trade_intents(id),
  transition_id bigint not null references public.gold_live_desk_transitions(id),
  policy_version text not null,
  risk_snapshot_id bigint not null references public.gold_adaptive_paper_risk_snapshots(id),
  decision text not null check (decision in ('ALLOCATE','SKIP')),
  decision_reason text not null,
  side text not null check (side in ('LONG','SHORT')),
  source_market_time timestamptz not null,
  source_price numeric not null,
  stop_price numeric not null,
  target_price numeric not null,
  reference_rr numeric not null,
  allocated_paper_r numeric not null check (allocated_paper_r >= 0 and allocated_paper_r <= 1),
  conflicting_open_decision_id bigint references public.gold_adaptive_paper_decisions(id),
  future_performance_used boolean not null default false,
  live_order_eligible boolean not null default false,
  live_trading_enabled boolean not null default false,
  broker_adapter_state text not null default 'NOT_CONNECTED',
  decision_sha256 text not null unique,
  unique(intent_id,policy_version)
);

alter table public.gold_adaptive_paper_decisions enable row level security;
revoke all privileges on table public.gold_adaptive_paper_decisions from public, anon, authenticated;
grant select, insert on table public.gold_adaptive_paper_decisions to service_role;
grant usage, select on sequence public.gold_adaptive_paper_decisions_id_seq to service_role;

create index if not exists gold_adaptive_paper_decisions_market_idx
  on public.gold_adaptive_paper_decisions(source_market_time desc,id desc);
create index if not exists gold_adaptive_paper_decisions_state_idx
  on public.gold_adaptive_paper_decisions(decision,source_market_time desc);

drop trigger if exists prevent_v137_adaptive_decision_mutation on public.gold_adaptive_paper_decisions;
create trigger prevent_v137_adaptive_decision_mutation
before update or delete on public.gold_adaptive_paper_decisions
for each row execute function public.prevent_v125_gold_learning_mutation();

create table if not exists public.gold_adaptive_paper_outcomes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  decision_id bigint not null unique references public.gold_adaptive_paper_decisions(id),
  intent_id bigint not null unique references public.gold_shadow_trade_intents(id),
  shadow_outcome_id bigint not null unique references public.gold_shadow_trade_outcomes(id),
  resolved_market_time timestamptz not null,
  resolution_code text not null,
  allocated_paper_r numeric not null,
  gross_trade_r numeric not null,
  portfolio_gross_r numeric not null,
  cost_model_state text not null,
  portfolio_net_r numeric,
  outcome_sha256 text not null unique
);

alter table public.gold_adaptive_paper_outcomes enable row level security;
revoke all privileges on table public.gold_adaptive_paper_outcomes from public, anon, authenticated;
grant select, insert on table public.gold_adaptive_paper_outcomes to service_role;
grant usage, select on sequence public.gold_adaptive_paper_outcomes_id_seq to service_role;

create index if not exists gold_adaptive_paper_outcomes_resolved_idx
  on public.gold_adaptive_paper_outcomes(resolved_market_time desc,id desc);

drop trigger if exists prevent_v137_adaptive_outcome_mutation on public.gold_adaptive_paper_outcomes;
create trigger prevent_v137_adaptive_outcome_mutation
before update or delete on public.gold_adaptive_paper_outcomes
for each row execute function public.prevent_v125_gold_learning_mutation();

create or replace function public.refresh_v137_gold_adaptive_paper_risk()
returns jsonb
language plpgsql
set search_path to 'public','extensions','pg_temp'
as $$
declare
  v_policy constant text := 'v137-adaptive-paper-risk-v1';
  p record;
  c record;
  v_source text := 'V136_CONTROL_BOOTSTRAP';
  v_n integer := 0;
  v_cum numeric := 0;
  v_dd numeric := 0;
  v_loss integer := 0;
  v_open integer := 0;
  v_allowed numeric := 0.25;
  v_state text := 'DISCOVERY_THROTTLE';
  v_reasons text[] := '{}'::text[];
  v_sha text;
  v_id bigint;
begin
  perform public.refresh_v136_gold_paper_portfolio_ledger();

  select * into p
  from public.gold_adaptive_paper_risk_policies
  where policy_version=v_policy
  limit 1;

  if not found then
    raise exception 'v137_policy_missing';
  end if;

  select count(*),coalesce(sum(portfolio_gross_r),0)
  into v_n,v_cum
  from public.gold_adaptive_paper_outcomes;

  if v_n > 0 then
    v_source := 'V137_ADAPTIVE_POLICY';

    with path as (
      select id,resolved_market_time,
             sum(portfolio_gross_r) over(order by resolved_market_time,id rows unbounded preceding) as cumulative_r
      from public.gold_adaptive_paper_outcomes
    ), drawdowns as (
      select cumulative_r,
             greatest(0::numeric,max(cumulative_r) over(order by resolved_market_time,id rows unbounded preceding)) as peak_r
      from path
    )
    select coalesce(max(peak_r-cumulative_r),0)
    into v_dd
    from drawdowns;

    with rev as (
      select portfolio_gross_r,
             sum(case when portfolio_gross_r >= 0 then 1 else 0 end)
               over(order by resolved_market_time desc,id desc rows unbounded preceding) as non_loss_seen
      from public.gold_adaptive_paper_outcomes
    )
    select count(*) into v_loss
    from rev
    where portfolio_gross_r < 0 and non_loss_seen=0;
  else
    select count(*) into v_n
    from public.gold_paper_portfolio_equity_events;

    select cumulative_gross_r,max_drawdown_r,loss_streak
    into c
    from public.gold_paper_portfolio_equity_events
    order by id desc
    limit 1;

    if found then
      v_cum := coalesce(c.cumulative_gross_r,0);
      v_dd := coalesce(c.max_drawdown_r,0);
      v_loss := coalesce(c.loss_streak,0);
    else
      v_n := 0;
      v_cum := 0;
      v_dd := 0;
      v_loss := 0;
    end if;
  end if;

  select count(*) into v_open
  from public.gold_adaptive_paper_decisions d
  where d.decision='ALLOCATE'
    and not exists (
      select 1 from public.gold_adaptive_paper_outcomes o where o.decision_id=d.id
    );

  if v_dd >= p.deep_defense_r or v_loss >= p.loss_streak_deep then
    v_allowed := p.min_paper_r;
    v_state := 'DEEP_DRAWDOWN_DEFENSE';
    v_reasons := array['DRAWDOWN_OR_LOSS_STREAK_DEEP'];
  elsif v_dd >= p.drawdown_defense_r or v_loss >= p.loss_streak_defense then
    v_allowed := 0.25;
    v_state := 'DRAWDOWN_DEFENSE';
    v_reasons := array['DRAWDOWN_OR_LOSS_STREAK_DEFENSE'];
  elsif v_n < p.discovery_sample then
    v_allowed := 0.25;
    v_state := 'DISCOVERY_THROTTLE';
    v_reasons := array['RESOLVED_SAMPLE_BELOW_5'];
  elsif v_n < 15 then
    v_allowed := 0.50;
    v_state := 'EARLY_SAMPLE_THROTTLE';
    v_reasons := array['RESOLVED_SAMPLE_BELOW_15'];
  elsif v_n < p.mature_sample then
    v_allowed := 0.75;
    v_state := 'MATURING_SAMPLE';
    v_reasons := array['RESOLVED_SAMPLE_BELOW_30'];
  elsif v_dd < 1.5 and v_loss < p.loss_streak_defense then
    v_allowed := p.max_paper_r;
    v_state := 'FULL_PAPER_BUDGET';
    v_reasons := array['MATURE_SAMPLE_AND_CONTROLLED_DRAWDOWN'];
  else
    v_allowed := 0.50;
    v_state := 'MATURE_DEFENSE';
    v_reasons := array['MATURE_SAMPLE_WITH_RISK_PRESSURE'];
  end if;

  v_allowed := greatest(p.min_paper_r,least(p.max_paper_r,v_allowed));

  v_sha := encode(
    extensions.digest(
      convert_to(
        concat_ws('|',
          v_policy,v_source,v_n::text,v_cum::text,v_dd::text,v_loss::text,
          v_open::text,v_allowed::text,v_state,array_to_string(v_reasons,','),
          'false','false','0R'
        ),
        'UTF8'
      ),
      'sha256'
    ),
    'hex'
  );

  insert into public.gold_adaptive_paper_risk_snapshots(
    policy_version,baseline_source,resolved_events,cumulative_gross_r,max_drawdown_r,
    loss_streak,allowed_paper_r,risk_state,reason_codes,current_open_positions,payload_sha256
  ) values (
    v_policy,v_source,v_n,v_cum,v_dd,v_loss,v_allowed,v_state,to_jsonb(v_reasons),v_open,v_sha
  )
  on conflict(payload_sha256) do nothing
  returning id into v_id;

  if v_id is null then
    select id into v_id
    from public.gold_adaptive_paper_risk_snapshots
    where payload_sha256=v_sha
    limit 1;
  end if;

  return jsonb_build_object(
    'ok',true,
    'version','v137-adaptive-paper-risk-governor-v1',
    'snapshot_id',v_id,
    'policy_version',v_policy,
    'baseline_source',v_source,
    'resolved_events',v_n,
    'cumulative_gross_r',v_cum,
    'max_drawdown_r',v_dd,
    'loss_streak',v_loss,
    'current_open_positions',v_open,
    'allowed_paper_r',v_allowed,
    'risk_state',v_state,
    'reason_codes',to_jsonb(v_reasons),
    'applies_to','V137_CHALLENGER_NEW_PAPER_DECISIONS_ONLY',
    'resizes_existing_positions',false,
    'live_trading_enabled',false,
    'order_submission_enabled',false,
    'automatic_real_capital',false,
    'real_capital_permission','0R',
    'checked_at',now()
  );
end;
$$;

revoke all on function public.refresh_v137_gold_adaptive_paper_risk() from public, anon, authenticated;
grant execute on function public.refresh_v137_gold_adaptive_paper_risk() to service_role;

create or replace function public.refresh_v137_gold_adaptive_paper_portfolio()
returns jsonb
language plpgsql
set search_path to 'public','extensions','pg_temp'
as $$
declare
  v_policy constant text := 'v137-adaptive-one-slot-v1';
  v_risk_policy constant text := 'v137-adaptive-paper-risk-v1';
  cfg record;
  risk record;
  i record;
  conflict record;
  so record;
  d record;
  v_decision text;
  v_reason text;
  v_alloc numeric;
  v_conflict bigint;
  v_late boolean;
  v_sha text;
  v_outcome_sha text;
  v_inserted integer := 0;
  v_outcomes integer := 0;
  v_open integer := 0;
  v_allocated integer := 0;
  v_skipped integer := 0;
begin
  perform public.refresh_v132_gold_shadow_trader();
  perform public.refresh_v137_gold_adaptive_paper_risk();

  select * into cfg
  from public.gold_adaptive_paper_risk_policies
  where policy_version=v_risk_policy
  limit 1;

  select * into risk
  from public.gold_adaptive_paper_risk_snapshots
  where policy_version=v_risk_policy
  order by id desc
  limit 1;

  if cfg.launched_at is null or risk.id is null then
    return jsonb_build_object(
      'ok',false,'version','v137-adaptive-shadow-portfolio-v1',
      'state','FAIL_CLOSED_POLICY_STATE_MISSING',
      'real_capital_permission','0R'
    );
  end if;

  for i in
    select *
    from public.gold_shadow_trade_intents x
    where x.created_at >= cfg.launched_at
      and not exists (
        select 1 from public.gold_adaptive_paper_decisions p
        where p.intent_id=x.id and p.policy_version=v_policy
      )
    order by x.created_at asc,x.id asc
  loop
    select exists(
      select 1 from public.gold_shadow_trade_outcomes x where x.intent_id=i.id
    ) into v_late;

    conflict := null;
    select p.id,p.intent_id,p.source_market_time
    into conflict
    from public.gold_adaptive_paper_decisions p
    left join public.gold_adaptive_paper_outcomes o on o.decision_id=p.id
    where p.policy_version=v_policy
      and p.decision='ALLOCATE'
      and p.source_market_time<i.source_market_time
      and (o.id is null or o.resolved_market_time>i.source_market_time)
    order by p.source_market_time desc,p.id desc
    limit 1;

    if v_late then
      v_decision := 'SKIP';
      v_reason := 'LATE_RESEARCH_EVENT_OUTCOME_ALREADY_KNOWN';
      v_alloc := 0;
      v_conflict := null;
    elsif found then
      v_decision := 'SKIP';
      v_reason := 'ADAPTIVE_SLOT_OCCUPIED';
      v_alloc := 0;
      v_conflict := conflict.id;
    elsif i.live_order_eligible or i.live_trading_enabled then
      v_decision := 'SKIP';
      v_reason := 'FAIL_CLOSED_LIVE_FLAG_PRESENT';
      v_alloc := 0;
      v_conflict := null;
    else
      v_decision := 'ALLOCATE';
      v_reason := 'ADAPTIVE_RISK_FREE_SLOT';
      v_alloc := risk.allowed_paper_r;
      v_conflict := null;
    end if;

    v_sha := encode(
      extensions.digest(
        convert_to(
          concat_ws('|',
            v_policy,i.id::text,i.transition_id::text,risk.id::text,
            v_decision,v_reason,i.side,i.source_market_time::text,
            i.source_price::text,i.stop_price::text,i.target_price::text,
            i.reference_rr::text,v_alloc::text,coalesce(v_conflict::text,''),
            'false','false','false','NOT_CONNECTED'
          ),
          'UTF8'
        ),
        'sha256'
      ),
      'hex'
    );

    insert into public.gold_adaptive_paper_decisions(
      intent_id,transition_id,policy_version,risk_snapshot_id,decision,decision_reason,
      side,source_market_time,source_price,stop_price,target_price,reference_rr,
      allocated_paper_r,conflicting_open_decision_id,decision_sha256
    ) values (
      i.id,i.transition_id,v_policy,risk.id,v_decision,v_reason,
      i.side,i.source_market_time,i.source_price,i.stop_price,i.target_price,i.reference_rr,
      v_alloc,v_conflict,v_sha
    )
    on conflict(intent_id,policy_version) do nothing;

    if found then v_inserted := v_inserted+1; end if;
  end loop;

  for d in
    select p.*
    from public.gold_adaptive_paper_decisions p
    where p.policy_version=v_policy
      and p.decision='ALLOCATE'
      and not exists (
        select 1 from public.gold_adaptive_paper_outcomes o where o.decision_id=p.id
      )
    order by p.id
  loop
    select * into so
    from public.gold_shadow_trade_outcomes x
    where x.intent_id=d.intent_id
    limit 1;

    if not found then continue; end if;

    v_outcome_sha := encode(
      extensions.digest(
        convert_to(
          concat_ws('|',
            d.id::text,d.intent_id::text,so.id::text,so.resolved_market_time::text,
            so.resolution_code,d.allocated_paper_r::text,so.gross_r::text,
            (so.gross_r*d.allocated_paper_r)::text,so.cost_model_state,
            coalesce((so.net_r*d.allocated_paper_r)::text,'')
          ),
          'UTF8'
        ),
        'sha256'
      ),
      'hex'
    );

    insert into public.gold_adaptive_paper_outcomes(
      decision_id,intent_id,shadow_outcome_id,resolved_market_time,resolution_code,
      allocated_paper_r,gross_trade_r,portfolio_gross_r,cost_model_state,
      portfolio_net_r,outcome_sha256
    ) values (
      d.id,d.intent_id,so.id,so.resolved_market_time,so.resolution_code,
      d.allocated_paper_r,so.gross_r,so.gross_r*d.allocated_paper_r,so.cost_model_state,
      case when so.net_r is null then null else so.net_r*d.allocated_paper_r end,
      v_outcome_sha
    )
    on conflict(decision_id) do nothing;

    if found then v_outcomes := v_outcomes+1; end if;
  end loop;

  perform public.refresh_v137_gold_adaptive_paper_risk();

  select count(*) into v_open
  from public.gold_adaptive_paper_decisions p
  where p.policy_version=v_policy and p.decision='ALLOCATE'
    and not exists (
      select 1 from public.gold_adaptive_paper_outcomes o where o.decision_id=p.id
    );

  select count(*) into v_allocated
  from public.gold_adaptive_paper_decisions
  where policy_version=v_policy and decision='ALLOCATE';

  select count(*) into v_skipped
  from public.gold_adaptive_paper_decisions
  where policy_version=v_policy and decision='SKIP';

  select * into risk
  from public.gold_adaptive_paper_risk_snapshots
  where policy_version=v_risk_policy
  order by id desc
  limit 1;

  return jsonb_build_object(
    'ok',true,
    'version','v137-adaptive-shadow-portfolio-v1',
    'policy_version',v_policy,
    'launched_at',cfg.launched_at,
    'decisions_inserted',v_inserted,
    'outcomes_inserted',v_outcomes,
    'total_decisions',v_allocated+v_skipped,
    'allocated',v_allocated,
    'skipped',v_skipped,
    'open_allocations',v_open,
    'next_paper_risk_r',risk.allowed_paper_r,
    'risk_state',risk.risk_state,
    'resolved_events',risk.resolved_events,
    'cumulative_gross_r',risk.cumulative_gross_r,
    'max_drawdown_r',risk.max_drawdown_r,
    'loss_streak',risk.loss_streak,
    'max_concurrent_positions',1,
    'resizes_existing_positions',false,
    'live_trading_enabled',false,
    'order_submission_enabled',false,
    'automatic_real_capital',false,
    'real_capital_permission','0R',
    'checked_at',now()
  );
end;
$$;

revoke all on function public.refresh_v137_gold_adaptive_paper_portfolio() from public, anon, authenticated;
grant execute on function public.refresh_v137_gold_adaptive_paper_portfolio() to service_role;

do $$
begin
  if not exists(select 1 from cron.job where jobname='tfa-v137-adaptive-paper-portfolio') then
    perform cron.schedule(
      'tfa-v137-adaptive-paper-portfolio',
      '*/2 * * * *',
      'select public.refresh_v137_gold_adaptive_paper_portfolio();'
    );
  end if;
end $$;
