create table if not exists public.gold_live_relay_events_v202 (
  id bigint generated by default as identity primary key,
  event_at timestamptz not null default now(),
  event_state text not null check (char_length(event_state) between 3 and 96),
  previous_state text,
  next_step_code text,
  bridge_enrolled boolean not null default false,
  authentication_reached boolean not null default false,
  first_tick_seen boolean not null default false,
  sustained_stream boolean not null default false,
  authenticated_requests bigint not null default 0 check (authenticated_requests >= 0),
  accepted_ticks bigint not null default 0 check (accepted_ticks >= 0),
  latest_tick_age_seconds integer check (latest_tick_age_seconds is null or latest_tick_age_seconds >= 0),
  source_version text not null,
  payload jsonb not null,
  state_fingerprint text not null check (state_fingerprint ~ '^[0-9a-f]{64}$'),
  previous_event_sha256 text check (previous_event_sha256 is null or previous_event_sha256 ~ '^[0-9a-f]{64}$'),
  event_sha256 text not null unique check (event_sha256 ~ '^[0-9a-f]{64}$'),
  action_permitted text not null default 'WAIT' check (action_permitted='WAIT'),
  capital_permission text not null default '0R' check (capital_permission='0R'),
  automatic_execution boolean not null default false check (automatic_execution=false),
  live_order_submission_enabled boolean not null default false check (live_order_submission_enabled=false)
);

alter table public.gold_live_relay_events_v202 enable row level security;
revoke all on table public.gold_live_relay_events_v202 from anon, authenticated;
grant select, insert on table public.gold_live_relay_events_v202 to service_role;
grant usage, select on sequence public.gold_live_relay_events_v202_id_seq to service_role;

create or replace function public.prevent_v202_relay_event_mutation()
returns trigger language plpgsql security invoker
set search_path=public,pg_temp
as $$
begin
  raise exception 'v202_relay_event_ledger_append_only';
end;
$$;

drop trigger if exists trg_v202_relay_event_append_only on public.gold_live_relay_events_v202;
create trigger trg_v202_relay_event_append_only
before update or delete on public.gold_live_relay_events_v202
for each row execute function public.prevent_v202_relay_event_mutation();

create or replace function public.capture_v202_gold_relay_event(p_event jsonb)
returns jsonb language plpgsql security invoker
set search_path=public,extensions,pg_temp
as $$
declare
  v_state text;
  v_now timestamptz := now();
  v_latest public.gold_live_relay_events_v202%rowtype;
  v_payload jsonb;
  v_fingerprint text;
  v_previous_hash text;
  v_event_hash text;
  v_id bigint;
  v_age integer;
begin
  if jsonb_typeof(p_event) is distinct from 'object' then
    return jsonb_build_object('ok',false,'error','invalid_event','capital_permission','0R');
  end if;

  v_state := upper(trim(coalesce(p_event->>'state','')));
  if v_state !~ '^[A-Z0-9_-]{3,96}$' then
    return jsonb_build_object('ok',false,'error','invalid_state','capital_permission','0R');
  end if;

  if coalesce(p_event->>'action_permitted','WAIT') <> 'WAIT'
     or coalesce(p_event->>'capital_permission','0R') <> '0R'
     or coalesce((p_event->>'automatic_execution')::boolean,false) <> false
     or coalesce((p_event->>'live_order_submission_enabled')::boolean,false) <> false then
    return jsonb_build_object('ok',false,'error','unsafe_governance_rejected','capital_permission','0R');
  end if;

  begin
    v_age := case when p_event ? 'latest_tick_age_seconds' and p_event->>'latest_tick_age_seconds' <> ''
      then greatest(0,(p_event->>'latest_tick_age_seconds')::integer) else null end;
  exception when invalid_text_representation or numeric_value_out_of_range then
    return jsonb_build_object('ok',false,'error','invalid_tick_age','capital_permission','0R');
  end;

  v_payload := jsonb_build_object(
    'state',v_state,
    'next_step_code',nullif(p_event->>'next_step_code',''),
    'bridge_enrolled',coalesce((p_event->>'bridge_enrolled')::boolean,false),
    'authentication_reached',coalesce((p_event->>'authentication_reached')::boolean,false),
    'first_tick_seen',coalesce((p_event->>'first_tick_seen')::boolean,false),
    'sustained_stream',coalesce((p_event->>'sustained_stream')::boolean,false),
    'authenticated_requests',greatest(0,coalesce((p_event->>'authenticated_requests')::bigint,0)),
    'accepted_ticks',greatest(0,coalesce((p_event->>'accepted_ticks')::bigint,0)),
    'latest_tick_age_seconds',v_age,
    'source_version',coalesce(nullif(p_event->>'source_version',''),'v199-gold-relay-observability-v1')
  );

  v_fingerprint := encode(extensions.digest(convert_to(v_payload::text,'UTF8'),'sha256'),'hex');
  perform pg_advisory_xact_lock(hashtextextended('v202_gold_relay_event_ledger',202));

  select * into v_latest from public.gold_live_relay_events_v202 order by id desc limit 1;

  if found and v_latest.state_fingerprint=v_fingerprint then
    return jsonb_build_object(
      'ok',true,'version','v202-gold-relay-event-ledger-v1','state','UNCHANGED',
      'inserted',false,'event_id',v_latest.id,'event_state',v_state,'capital_permission','0R'
    );
  end if;

  v_previous_hash := case when v_latest.id is null then null else v_latest.event_sha256 end;
  v_event_hash := encode(
    extensions.digest(
      convert_to(coalesce(v_previous_hash,'GENESIS') || '|' || v_state || '|' || v_fingerprint || '|' || v_now::text,'UTF8'),
      'sha256'
    ),
    'hex'
  );

  insert into public.gold_live_relay_events_v202(
    event_at,event_state,previous_state,next_step_code,bridge_enrolled,authentication_reached,
    first_tick_seen,sustained_stream,authenticated_requests,accepted_ticks,latest_tick_age_seconds,
    source_version,payload,state_fingerprint,previous_event_sha256,event_sha256,
    action_permitted,capital_permission,automatic_execution,live_order_submission_enabled
  ) values (
    v_now,v_state,case when v_latest.id is null then null else v_latest.event_state end,
    nullif(p_event->>'next_step_code',''),
    coalesce((p_event->>'bridge_enrolled')::boolean,false),
    coalesce((p_event->>'authentication_reached')::boolean,false),
    coalesce((p_event->>'first_tick_seen')::boolean,false),
    coalesce((p_event->>'sustained_stream')::boolean,false),
    greatest(0,coalesce((p_event->>'authenticated_requests')::bigint,0)),
    greatest(0,coalesce((p_event->>'accepted_ticks')::bigint,0)),
    v_age,coalesce(nullif(p_event->>'source_version',''),'v199-gold-relay-observability-v1'),
    v_payload,v_fingerprint,v_previous_hash,v_event_hash,'WAIT','0R',false,false
  ) returning id into v_id;

  return jsonb_build_object(
    'ok',true,'version','v202-gold-relay-event-ledger-v1','state','EVENT_RECORDED',
    'inserted',true,'event_id',v_id,'event_state',v_state,
    'previous_state',case when v_latest.id is null then null else v_latest.event_state end,
    'event_sha256',v_event_hash,'capital_permission','0R'
  );
end;
$$;

create or replace function public.get_v202_gold_relay_event_ledger(p_limit integer default 40)
returns jsonb language plpgsql security invoker
set search_path=public,extensions,pg_temp
as $$
declare
  v_limit integer := greatest(1,least(coalesce(p_limit,40),100));
  v_total bigint;
  v_failures bigint;
  v_latest timestamptz;
begin
  select count(*),max(event_at) into v_total,v_latest from public.gold_live_relay_events_v202;

  with ordered as (
    select id,event_at,event_state,state_fingerprint,previous_event_sha256,event_sha256,
      lag(event_sha256) over(order by id) as expected_previous
    from public.gold_live_relay_events_v202
  )
  select count(*) into v_failures
  from ordered
  where (expected_previous is null and previous_event_sha256 is not null)
     or (expected_previous is not null and previous_event_sha256 is distinct from expected_previous)
     or event_sha256 is distinct from encode(
       extensions.digest(
         convert_to(coalesce(previous_event_sha256,'GENESIS') || '|' || event_state || '|' || state_fingerprint || '|' || event_at::text,'UTF8'),
         'sha256'
       ),
       'hex'
     );

  return jsonb_build_object(
    'ok',true,'version','v202-gold-relay-event-ledger-v1',
    'state',case when v_failures=0 then 'HASH_CHAIN_VERIFIED' else 'HASH_CHAIN_BROKEN' end,
    'generated_at',now(),
    'counts',jsonb_build_object('events',v_total,'chain_failures',v_failures),
    'latest_event_at',v_latest,
    'events',coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',e.id,'event_at',e.event_at,'event_state',e.event_state,'previous_state',e.previous_state,
        'next_step_code',e.next_step_code,'bridge_enrolled',e.bridge_enrolled,
        'authentication_reached',e.authentication_reached,'first_tick_seen',e.first_tick_seen,
        'sustained_stream',e.sustained_stream,'authenticated_requests',e.authenticated_requests,
        'accepted_ticks',e.accepted_ticks,'latest_tick_age_seconds',e.latest_tick_age_seconds,
        'source_version',e.source_version,'event_sha256',e.event_sha256,
        'action_permitted','WAIT','capital_permission','0R'
      ) order by e.id desc)
      from (select * from public.gold_live_relay_events_v202 order by id desc limit v_limit) e
    ),'[]'::jsonb),
    'governance',jsonb_build_object(
      'append_only',true,'hash_chained',true,'bridge_secrets_excluded',true,
      'action_permitted','WAIT','capital_permission','0R',
      'automatic_execution',false,'live_order_submission_enabled',false
    )
  );
end;
$$;

revoke all on function public.capture_v202_gold_relay_event(jsonb) from public, anon, authenticated;
revoke all on function public.get_v202_gold_relay_event_ledger(integer) from public, anon, authenticated;
grant execute on function public.capture_v202_gold_relay_event(jsonb) to service_role;
grant execute on function public.get_v202_gold_relay_event_ledger(integer) to service_role;
revoke all on function public.prevent_v202_relay_event_mutation() from public, anon, authenticated;
