-- V136 Execution Qualification + Order Firewall
-- Converts the current V133 paper allocation into an immutable DRY-RUN order envelope.
-- This layer cannot connect to a broker, cannot submit a live order, and cannot grant real capital.

create table if not exists public.gold_execution_order_intents (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  source_portfolio_decision_id bigint not null references public.gold_shadow_portfolio_decisions(id),
  source_intent_id bigint not null references public.gold_shadow_trade_intents(id),
  source_transition_id bigint not null references public.gold_live_desk_transitions(id),
  firewall_version text not null,
  symbol text not null default 'XAUUSD',
  side text not null check (side in ('LONG','SHORT')),
  strategy_code text,
  reference_market_time timestamptz not null,
  reference_entry numeric not null,
  reference_stop numeric not null,
  reference_target numeric not null,
  reference_rr numeric not null,
  requested_r numeric not null,
  risk_geometry_valid boolean not null,
  risk_within_limit boolean not null,
  quote_class text not null default 'DELAYED_RESEARCH_REFERENCE',
  client_order_id text not null,
  idempotency_key text not null,
  kill_switch_on boolean not null default true,
  real_broker_connected boolean not null default false,
  live_order_route_present boolean not null default false,
  execution_grade_quote boolean not null default false,
  measured_spread_available boolean not null default false,
  measured_slippage_available boolean not null default false,
  human_release_complete boolean not null default false,
  submission_state text not null default 'BLOCKED_DRY_RUN_ONLY',
  submission_permitted boolean not null default false,
  real_order_sent boolean not null default false,
  blocker_codes text[] not null default '{}'::text[],
  payload_sha256 text not null unique,
  unique(source_portfolio_decision_id, firewall_version),
  unique(idempotency_key)
);

alter table public.gold_execution_order_intents enable row level security;
revoke all privileges on table public.gold_execution_order_intents from public, anon, authenticated;
grant select, insert on table public.gold_execution_order_intents to service_role;
grant usage, select on sequence public.gold_execution_order_intents_id_seq to service_role;

create index if not exists gold_execution_order_intents_created_idx
  on public.gold_execution_order_intents(created_at desc);
create index if not exists gold_execution_order_intents_source_intent_idx
  on public.gold_execution_order_intents(source_intent_id);
create index if not exists gold_execution_order_intents_transition_idx
  on public.gold_execution_order_intents(source_transition_id);

drop trigger if exists prevent_v136_execution_order_intent_mutation on public.gold_execution_order_intents;
create trigger prevent_v136_execution_order_intent_mutation
before update or delete on public.gold_execution_order_intents
for each row execute function public.prevent_v125_gold_learning_mutation();

create or replace function public.refresh_v136_gold_execution_firewall()
returns jsonb
language plpgsql
set search_path to 'public','extensions','pg_temp'
as $$
declare
  v_version constant text := 'v136-execution-order-firewall-v1';
  d record;
  i record;
  o record;
  v_geometry boolean := false;
  v_risk_ok boolean := false;
  v_requested_r numeric := 0;
  v_client_order_id text;
  v_idempotency_key text;
  v_blockers text[];
  v_sha text;
  v_inserted integer := 0;
  v_total integer := 0;
  v_real_orders integer := 0;
begin
  perform public.refresh_v133_gold_shadow_portfolio();

  select p.*
  into d
  from public.gold_shadow_portfolio_decisions p
  where p.policy_version='v133-one-slot-first-eligible-v1'
    and p.decision='ALLOCATE'
    and not exists (
      select 1
      from public.gold_shadow_portfolio_outcomes po
      where po.decision_id=p.id
    )
  order by p.source_market_time desc,p.id desc
  limit 1;

  if found then
    select x.*
    into i
    from public.gold_shadow_trade_intents x
    where x.id=d.intent_id
    limit 1;

    if found then
      v_geometry :=
        case
          when i.side='LONG' then i.stop_price < i.source_price and i.target_price > i.source_price
          when i.side='SHORT' then i.stop_price > i.source_price and i.target_price < i.source_price
          else false
        end
        and i.risk_points > 0
        and i.reference_rr > 0;

      v_requested_r := greatest(0, least(coalesce(d.allocated_risk_r,0), 1));
      v_risk_ok := v_requested_r > 0 and v_requested_r <= 1;

      v_client_order_id := 'TFA-V136-' || d.id::text;
      v_idempotency_key := encode(
        extensions.digest(
          convert_to(concat_ws('|',v_version,d.id::text,d.intent_id::text,d.transition_id::text),'UTF8'),
          'sha256'
        ),
        'hex'
      );

      v_blockers := array[
        'REAL_BROKER_NOT_CONNECTED',
        'LIVE_ORDER_ROUTE_ABSENT',
        'EXECUTION_GRADE_QUOTE_UNAVAILABLE',
        'MEASURED_SPREAD_UNAVAILABLE',
        'MEASURED_SLIPPAGE_UNAVAILABLE',
        'HUMAN_RELEASE_REVIEW_REQUIRED'
      ]::text[];

      if not v_geometry then
        v_blockers := array_append(v_blockers,'RISK_GEOMETRY_INVALID');
      end if;
      if not v_risk_ok then
        v_blockers := array_append(v_blockers,'RISK_LIMIT_INVALID');
      end if;

      v_sha := encode(
        extensions.digest(
          convert_to(
            concat_ws('|',
              v_version,d.id::text,d.intent_id::text,d.transition_id::text,
              'XAUUSD',i.side,coalesce(i.strategy_code,''),
              i.source_market_time::text,i.source_price::text,i.stop_price::text,
              i.target_price::text,i.reference_rr::text,v_requested_r::text,
              v_geometry::text,v_risk_ok::text,'DELAYED_RESEARCH_REFERENCE',
              v_client_order_id,v_idempotency_key,'true','false','false',
              'false','false','false','false','BLOCKED_DRY_RUN_ONLY',
              'false','false',array_to_string(v_blockers,',')
            ),
            'UTF8'
          ),
          'sha256'
        ),
        'hex'
      );

      insert into public.gold_execution_order_intents(
        source_portfolio_decision_id,source_intent_id,source_transition_id,
        firewall_version,symbol,side,strategy_code,reference_market_time,
        reference_entry,reference_stop,reference_target,reference_rr,requested_r,
        risk_geometry_valid,risk_within_limit,quote_class,client_order_id,
        idempotency_key,kill_switch_on,real_broker_connected,
        live_order_route_present,execution_grade_quote,measured_spread_available,
        measured_slippage_available,human_release_complete,submission_state,
        submission_permitted,real_order_sent,blocker_codes,payload_sha256
      ) values (
        d.id,d.intent_id,d.transition_id,
        v_version,'XAUUSD',i.side,i.strategy_code,i.source_market_time,
        i.source_price,i.stop_price,i.target_price,i.reference_rr,v_requested_r,
        v_geometry,v_risk_ok,'DELAYED_RESEARCH_REFERENCE',v_client_order_id,
        v_idempotency_key,true,false,
        false,false,false,
        false,false,'BLOCKED_DRY_RUN_ONLY',
        false,false,v_blockers,v_sha
      )
      on conflict(source_portfolio_decision_id,firewall_version) do nothing;

      if found then v_inserted:=1; end if;
    end if;
  end if;

  select count(*) into v_total
  from public.gold_execution_order_intents
  where firewall_version=v_version;

  select count(*) into v_real_orders
  from public.gold_execution_order_intents
  where firewall_version=v_version and real_order_sent=true;

  select e.*
  into o
  from public.gold_execution_order_intents e
  join public.gold_shadow_portfolio_decisions p on p.id=e.source_portfolio_decision_id
  where e.firewall_version=v_version
    and not exists (
      select 1 from public.gold_shadow_portfolio_outcomes po where po.decision_id=p.id
    )
  order by e.created_at desc,e.id desc
  limit 1;

  return jsonb_build_object(
    'ok', true,
    'version', v_version,
    'state', case when o.id is null then 'WAITING_FOR_PAPER_SIGNAL' else 'DRY_RUN_INTENT_PREPARED' end,
    'inserted', v_inserted,
    'total_order_intents', v_total,
    'real_orders_sent', v_real_orders,
    'current_order_intent', case when o.id is null then null else jsonb_build_object(
      'id',o.id,
      'source_portfolio_decision_id',o.source_portfolio_decision_id,
      'source_intent_id',o.source_intent_id,
      'source_transition_id',o.source_transition_id,
      'symbol',o.symbol,
      'side',o.side,
      'strategy_code',o.strategy_code,
      'reference_market_time',o.reference_market_time,
      'reference_entry',o.reference_entry,
      'reference_stop',o.reference_stop,
      'reference_target',o.reference_target,
      'reference_rr',o.reference_rr,
      'requested_r',o.requested_r,
      'risk_geometry_valid',o.risk_geometry_valid,
      'risk_within_limit',o.risk_within_limit,
      'quote_class',o.quote_class,
      'client_order_id',o.client_order_id,
      'idempotency_key',o.idempotency_key,
      'kill_switch_on',o.kill_switch_on,
      'submission_state',o.submission_state,
      'submission_permitted',o.submission_permitted,
      'real_order_sent',o.real_order_sent,
      'blocker_codes',o.blocker_codes
    ) end,
    'firewall', jsonb_build_object(
      'paper_source_valid',o.id is not null,
      'risk_geometry_valid',coalesce(o.risk_geometry_valid,false),
      'risk_within_one_r',coalesce(o.risk_within_limit,false),
      'idempotency_key_present',coalesce(length(o.idempotency_key)>0,false),
      'kill_switch_on',coalesce(o.kill_switch_on,true),
      'real_broker_connected',false,
      'live_order_route_present',false,
      'execution_grade_quote',false,
      'measured_spread_available',false,
      'measured_slippage_available',false,
      'human_release_complete',false,
      'submission_permitted',false
    ),
    'governance', jsonb_build_object(
      'dry_run_only',true,
      'live_trading_enabled',false,
      'order_submission_enabled',false,
      'automatic_real_capital',false,
      'real_capital_permission','0R'
    ),
    'checked_at', now()
  );
end;
$$;

revoke all on function public.refresh_v136_gold_execution_firewall() from public, anon, authenticated;
grant execute on function public.refresh_v136_gold_execution_firewall() to service_role;

do $$
begin
  if not exists(select 1 from cron.job where jobname='tfa-v136-gold-execution-firewall') then
    perform cron.schedule(
      'tfa-v136-gold-execution-firewall',
      '*/2 * * * *',
      'select public.refresh_v136_gold_execution_firewall();'
    );
  end if;
end $$;
