-- V130 Review Priority Intelligence
-- Transparent attention-routing for directional human-review candidates.
-- Uses only pre-review request metadata. No future performance, reviewer outcomes,
-- automatic execution, automatic promotion, or capital authority.

create table if not exists public.gold_review_priority_assignments (
  id bigint generated by default as identity primary key,
  review_request_id bigint not null references public.gold_trigger_review_requests(id),
  classifier_version text not null,
  scoring_version text not null,
  requested_at timestamptz not null,
  event_class text not null,
  transition_code text not null,
  signal_key text not null,
  direction text not null,
  review_stage text not null,
  source_state text,
  severity text not null,
  direction_score integer not null,
  event_class_score integer not null,
  severity_score integer not null,
  transition_score integer not null,
  priority_score integer not null,
  priority_band text not null,
  performance_evidence_used boolean not null default false,
  human_outcome_evidence_used boolean not null default false,
  automatic_execution boolean not null default false,
  automatic_promotion boolean not null default false,
  capital_permission text not null default '0R',
  source_request_sha256 text not null,
  priority_sha256 text not null,
  created_at timestamptz not null default now(),
  unique(review_request_id)
);

alter table public.gold_review_priority_assignments enable row level security;
revoke all privileges on table public.gold_review_priority_assignments from public, anon, authenticated;
grant select, insert on table public.gold_review_priority_assignments to service_role;
grant usage, select on sequence public.gold_review_priority_assignments_id_seq to service_role;

create index if not exists gold_review_priority_band_idx
  on public.gold_review_priority_assignments(priority_band,priority_score desc,requested_at desc);
create index if not exists gold_review_priority_classifier_idx
  on public.gold_review_priority_assignments(classifier_version,priority_score desc,requested_at desc);

drop trigger if exists prevent_v130_review_priority_update_delete
  on public.gold_review_priority_assignments;
create trigger prevent_v130_review_priority_update_delete
before update or delete on public.gold_review_priority_assignments
for each row execute function public.prevent_v125_gold_learning_mutation();

create or replace function public.refresh_v130_gold_review_priorities()
returns jsonb
language plpgsql
set search_path to 'public','extensions','pg_temp'
as $$
declare
  r record;
  v_direction integer;
  v_class integer;
  v_severity integer;
  v_transition integer;
  v_total integer;
  v_band text;
  v_sha text;
  v_inserted integer := 0;
begin
  for r in
    select
      q.id as review_request_id,
      q.classifier_version,
      q.requested_at,
      q.event_class,
      q.transition_code,
      q.signal_key,
      q.direction,
      q.review_stage,
      q.source_state,
      upper(coalesce(nullif(q.request_reason->>'severity',''),'UNKNOWN')) as severity,
      q.request_sha256
    from public.gold_trigger_review_requests q
    where q.classifier_version='v125.3-event-aware-v2'
      and q.direction in ('LONG','SHORT')
      and not exists (
        select 1
        from public.gold_review_priority_assignments p
        where p.review_request_id=q.id
      )
    order by q.id
  loop
    v_direction := 40;

    v_class := case upper(r.event_class)
      when 'LEVEL' then 25
      when 'STRUCTURE' then 22
      when 'SETUP' then 15
      else 8
    end;

    v_severity := case r.severity
      when 'CRITICAL' then 35
      when 'HIGH' then 30
      when 'WATCH' then 20
      when 'INFO' then 5
      else 10
    end;

    v_transition := case upper(r.transition_code)
      when 'LONG_RETEST_ZONE_ENTERED' then 15
      when 'SHORT_FAILURE_ZONE_ENTERED' then 15
      when 'DAILY_STRUCTURE_CHANGED' then 12
      when 'LONG_STATE_CHANGED' then 10
      when 'SHORT_STATE_CHANGED' then 10
      when 'DESK_STATE_CHANGED' then 8
      when 'DAILY_BIAS_CHANGED' then 8
      else 5
    end;

    v_total := least(100,v_direction+v_class+v_severity+v_transition);

    v_band := case
      when v_total >= 90 then 'P1_HIGH_ATTENTION'
      when v_total >= 80 then 'P2_PRIORITY'
      when v_total >= 70 then 'P3_STANDARD'
      else 'P4_BACKGROUND'
    end;

    v_sha := encode(
      extensions.digest(
        convert_to(
          concat_ws('|',
            r.review_request_id::text,r.classifier_version,'v130-rule-v1',
            r.requested_at::text,r.event_class,r.transition_code,r.signal_key,
            r.direction,r.review_stage,coalesce(r.source_state,''),r.severity,
            v_direction::text,v_class::text,v_severity::text,v_transition::text,
            v_total::text,v_band,'false','false','0R',r.request_sha256
          ),
          'UTF8'
        ),
        'sha256'
      ),
      'hex'
    );

    insert into public.gold_review_priority_assignments(
      review_request_id,classifier_version,scoring_version,requested_at,
      event_class,transition_code,signal_key,direction,review_stage,source_state,
      severity,direction_score,event_class_score,severity_score,transition_score,
      priority_score,priority_band,performance_evidence_used,human_outcome_evidence_used,
      automatic_execution,automatic_promotion,capital_permission,
      source_request_sha256,priority_sha256
    ) values (
      r.review_request_id,r.classifier_version,'v130-rule-v1',r.requested_at,
      r.event_class,r.transition_code,r.signal_key,r.direction,r.review_stage,r.source_state,
      r.severity,v_direction,v_class,v_severity,v_transition,
      v_total,v_band,false,false,false,false,'0R',
      r.request_sha256,v_sha
    )
    on conflict(review_request_id) do nothing;

    if found then v_inserted:=v_inserted+1; end if;
  end loop;

  return jsonb_build_object(
    'ok',true,
    'version','v130-review-priority-refresh-v1',
    'inserted',v_inserted,
    'assignments',(
      select count(*) from public.gold_review_priority_assignments
      where classifier_version='v125.3-event-aware-v2'
    ),
    'unreviewed_directional',(
      select count(*)
      from public.gold_trigger_review_requests q
      where q.classifier_version='v125.3-event-aware-v2'
        and q.direction in ('LONG','SHORT')
        and not exists (
          select 1 from public.gold_human_review_events h
          where h.review_request_id=q.id
            and h.event_type='HUMAN_EVIDENCE_REVIEW'
        )
    ),
    'performance_evidence_used',false,
    'human_outcome_evidence_used',false,
    'automatic_execution',false,
    'automatic_promotion',false,
    'capital_permission','0R',
    'checked_at',now()
  );
end;
$$;

revoke all on function public.refresh_v130_gold_review_priorities()
from public, anon, authenticated;
grant execute on function public.refresh_v130_gold_review_priorities()
to service_role;

do $$
begin
  if not exists (
    select 1 from cron.job where jobname='tfa-v130-gold-review-priority'
  ) then
    perform cron.schedule(
      'tfa-v130-gold-review-priority',
      '*/2 * * * *',
      'select public.refresh_v130_gold_review_priorities();'
    );
  end if;
end $$;
