-- V137 Adaptive Paper Risk Governor
-- Production-applied additive migration. The governor only scales future paper allocations.
-- Existing paper allocations are immutable; live trading/order submission remain OFF; real capital remains 0R.

create table if not exists public.gold_paper_risk_governor_snapshots (
  id bigint generated by default as identity primary key,
  evaluated_at timestamptz not null default now(),
  governor_version text not null,
  source_equity_event_id bigint references public.gold_paper_portfolio_equity_events(id),
  resolved_paper_trades integer not null,
  cumulative_gross_r numeric,
  current_drawdown_r numeric,
  max_drawdown_r numeric,
  win_streak integer not null default 0,
  loss_streak integer not null default 0,
  sample_band text not null,
  risk_state text not null,
  recommended_next_paper_r numeric not null check (recommended_next_paper_r in (0.10,0.25,0.50,1.00)),
  max_concurrent_positions integer not null default 1,
  pyramiding_allowed boolean not null default false,
  simultaneous_long_short_allowed boolean not null default false,
  reason_codes text[] not null default '{}'::text[],
  live_trading_enabled boolean not null default false,
  order_submission_enabled boolean not null default false,
  automatic_real_capital boolean not null default false,
  real_capital_permission text not null default '0R',
  source_event_sha256 text,
  snapshot_sha256 text not null unique
);

alter table public.gold_paper_risk_governor_snapshots enable row level security;
revoke all privileges on table public.gold_paper_risk_governor_snapshots from public, anon, authenticated;
grant select, insert on table public.gold_paper_risk_governor_snapshots to service_role;
grant usage, select on sequence public.gold_paper_risk_governor_snapshots_id_seq to service_role;

create index if not exists gold_paper_risk_governor_time_idx
  on public.gold_paper_risk_governor_snapshots(evaluated_at desc);
create index if not exists gold_paper_risk_governor_state_idx
  on public.gold_paper_risk_governor_snapshots(risk_state,evaluated_at desc);

drop trigger if exists prevent_v137_paper_risk_governor_mutation on public.gold_paper_risk_governor_snapshots;
create trigger prevent_v137_paper_risk_governor_mutation
before update or delete on public.gold_paper_risk_governor_snapshots
for each row execute function public.prevent_v125_gold_learning_mutation();

alter table public.gold_shadow_portfolio_decisions
  add column if not exists risk_governor_version text,
  add column if not exists risk_governor_snapshot_id bigint references public.gold_paper_risk_governor_snapshots(id);

-- The live database function body is source-frozen below.
create or replace function public.refresh_v137_gold_paper_risk_governor()
returns jsonb
language plpgsql
set search_path to 'public','extensions','pg_temp'
as $$
declare
  v_version constant text := 'v137-adaptive-paper-risk-governor-v1';
  e record; v_resolved integer := 0; v_cum numeric := 0; v_dd numeric := 0; v_max_dd numeric := 0;
  v_wins integer := 0; v_losses integer := 0; v_sample text; v_state text; v_risk numeric;
  v_reasons text[] := '{}'::text[]; v_sha text; v_id bigint;
begin
  perform public.refresh_v136_gold_paper_portfolio_ledger();
  select x.* into e from public.gold_paper_portfolio_equity_events x order by x.id desc limit 1;
  if found then
    select count(*) into v_resolved from public.gold_paper_portfolio_equity_events;
    v_cum:=coalesce(e.cumulative_gross_r,0); v_dd:=coalesce(e.drawdown_r,0); v_max_dd:=coalesce(e.max_drawdown_r,0);
    v_wins:=coalesce(e.win_streak,0); v_losses:=coalesce(e.loss_streak,0);
  end if;
  v_sample:=case when v_resolved<10 then 'DISCOVERY_LT_10' when v_resolved<30 then 'EARLY_10_TO_29' else 'MATURE_30_PLUS' end;
  if v_resolved=0 then v_state:='DISCOVERY_PROBE';v_risk:=0.25;v_reasons:=array_append(v_reasons,'NO_RESOLVED_PAPER_SAMPLE');
  elsif v_max_dd>=3 or v_losses>=3 then v_state:='DEEP_CAPITAL_DEFENSE';v_risk:=0.10;
    if v_max_dd>=3 then v_reasons:=array_append(v_reasons,'MAX_DRAWDOWN_GE_3R'); end if;
    if v_losses>=3 then v_reasons:=array_append(v_reasons,'LOSS_STREAK_GE_3'); end if;
  elsif v_max_dd>=2 or v_losses>=2 then v_state:='CAPITAL_DEFENSE';v_risk:=0.25;
    if v_max_dd>=2 then v_reasons:=array_append(v_reasons,'MAX_DRAWDOWN_GE_2R'); end if;
    if v_losses>=2 then v_reasons:=array_append(v_reasons,'LOSS_STREAK_GE_2'); end if;
  elsif v_resolved<10 then v_state:='DISCOVERY_PROBE';v_risk:=0.25;v_reasons:=array_append(v_reasons,'SAMPLE_BELOW_10');
  elsif v_max_dd>=1 or v_losses>=1 or v_cum<=0 then v_state:='CAUTIOUS';v_risk:=0.50;
    if v_max_dd>=1 then v_reasons:=array_append(v_reasons,'DRAWDOWN_GE_1R'); end if;
    if v_losses>=1 then v_reasons:=array_append(v_reasons,'ACTIVE_LOSS_STREAK'); end if;
    if v_cum<=0 then v_reasons:=array_append(v_reasons,'CUMULATIVE_GROSS_R_NON_POSITIVE'); end if;
  elsif v_resolved<30 then v_state:='EARLY_EVIDENCE';v_risk:=0.50;v_reasons:=array_append(v_reasons,'SAMPLE_BELOW_30');
  else v_state:='NORMAL_PAPER_RISK';v_risk:=1.00;v_reasons:=array_append(v_reasons,'MATURE_POSITIVE_PAPER_EVIDENCE'); end if;
  v_reasons:=array_append(v_reasons,'ONE_SLOT_ONLY');
  v_reasons:=array_append(v_reasons,'LIVE_CAPITAL_ALWAYS_0R');
  v_sha:=encode(extensions.digest(convert_to(concat_ws('|',v_version,coalesce(e.id,0)::text,v_resolved::text,
    v_cum::text,v_dd::text,v_max_dd::text,v_wins::text,v_losses::text,v_sample,v_state,v_risk::text,
    array_to_string(v_reasons,','),'1','false','false','false','false','false','0R',coalesce(e.event_sha256,'')),'UTF8'),'sha256'),'hex');
  insert into public.gold_paper_risk_governor_snapshots(
    governor_version,source_equity_event_id,resolved_paper_trades,cumulative_gross_r,current_drawdown_r,max_drawdown_r,
    win_streak,loss_streak,sample_band,risk_state,recommended_next_paper_r,max_concurrent_positions,pyramiding_allowed,
    simultaneous_long_short_allowed,reason_codes,source_event_sha256,snapshot_sha256
  ) values (v_version,e.id,v_resolved,v_cum,v_dd,v_max_dd,v_wins,v_losses,v_sample,v_state,v_risk,1,false,false,v_reasons,e.event_sha256,v_sha)
  on conflict(snapshot_sha256) do nothing returning id into v_id;
  if v_id is null then select id into v_id from public.gold_paper_risk_governor_snapshots where snapshot_sha256=v_sha limit 1; end if;
  return jsonb_build_object('ok',true,'version',v_version,'snapshot_id',v_id,'state',v_state,'sample_band',v_sample,
    'resolved_paper_trades',v_resolved,'cumulative_gross_r',v_cum,'current_drawdown_r',v_dd,'max_drawdown_r',v_max_dd,
    'win_streak',v_wins,'loss_streak',v_losses,'recommended_next_paper_r',v_risk,'max_concurrent_positions',1,
    'pyramiding_allowed',false,'simultaneous_long_short_allowed',false,'reason_codes',to_jsonb(v_reasons),
    'live_trading_enabled',false,'order_submission_enabled',false,'automatic_real_capital',false,
    'real_capital_permission','0R','checked_at',now());
end;
$$;

revoke all on function public.refresh_v137_gold_paper_risk_governor() from public, anon, authenticated;
grant execute on function public.refresh_v137_gold_paper_risk_governor() to service_role;

-- refresh_v133_gold_shadow_portfolio is also upgraded in production to read the latest
-- V137 snapshot and apply recommended_next_paper_r only when a future free slot is allocated.
-- Existing rows are never rewritten. See the deployment commit for the frozen function body.

do $$
begin
  if not exists(select 1 from cron.job where jobname='tfa-v137-gold-paper-risk-governor') then
    perform cron.schedule('tfa-v137-gold-paper-risk-governor','*/2 * * * *',
      'select public.refresh_v137_gold_paper_risk_governor();');
  end if;
end $$;
