-- V131 Review Freshness Watch
-- Tracks operational review aging and real human response latency.
-- Targets are queue-management SLAs, not market signals. No execution or capital authority.

create table if not exists public.gold_review_response_latency_events (
  id bigint generated by default as identity primary key,
  review_event_id bigint not null references public.gold_human_review_events(id),
  review_request_id bigint not null references public.gold_trigger_review_requests(id),
  priority_assignment_id bigint not null references public.gold_review_priority_assignments(id),
  reviewer_user_id uuid not null,
  classifier_version text not null,
  priority_band text not null,
  priority_score integer not null,
  requested_at timestamptz not null,
  reviewed_at timestamptz not null,
  response_latency_seconds numeric not null,
  source_priority_sha256 text not null,
  source_review_sha256 text not null,
  payload_sha256 text not null,
  created_at timestamptz not null default now(),
  unique(review_event_id)
);

alter table public.gold_review_response_latency_events enable row level security;
revoke all privileges on table public.gold_review_response_latency_events from public, anon, authenticated;
grant select, insert on table public.gold_review_response_latency_events to service_role;
grant usage, select on sequence public.gold_review_response_latency_events_id_seq to service_role;

create index if not exists gold_review_latency_request_idx
  on public.gold_review_response_latency_events(review_request_id);
create index if not exists gold_review_latency_priority_idx
  on public.gold_review_response_latency_events(priority_assignment_id);
create index if not exists gold_review_latency_band_idx
  on public.gold_review_response_latency_events(priority_band,reviewed_at desc);

drop trigger if exists prevent_v131_review_latency_update_delete
  on public.gold_review_response_latency_events;
create trigger prevent_v131_review_latency_update_delete
before update or delete on public.gold_review_response_latency_events
for each row execute function public.prevent_v125_gold_learning_mutation();

create or replace function public.refresh_v131_gold_review_response_latency()
returns jsonb
language plpgsql
set search_path to 'public','extensions','pg_temp'
as $$
declare
  r record;
  v_latency numeric;
  v_sha text;
  v_inserted integer := 0;
begin
  perform public.refresh_v130_gold_review_priorities();

  for r in
    select
      h.id as review_event_id,
      h.review_request_id,
      h.reviewer_user_id,
      h.classifier_version,
      h.event_at as reviewed_at,
      h.evidence_sha256 as source_review_sha256,
      p.id as priority_assignment_id,
      p.priority_band,
      p.priority_score,
      p.requested_at,
      p.priority_sha256 as source_priority_sha256
    from public.gold_human_review_events h
    join public.gold_review_priority_assignments p
      on p.review_request_id=h.review_request_id
    where h.event_type='HUMAN_EVIDENCE_REVIEW'
      and h.classifier_version='v125.3-event-aware-v2'
      and p.classifier_version='v125.3-event-aware-v2'
      and h.reviewer_user_id is not null
      and not exists (
        select 1
        from public.gold_review_response_latency_events x
        where x.review_event_id=h.id
      )
    order by h.id
  loop
    v_latency:=greatest(0,extract(epoch from (r.reviewed_at-r.requested_at)));

    v_sha:=encode(
      extensions.digest(
        convert_to(
          concat_ws('|',
            r.review_event_id::text,r.review_request_id::text,
            r.priority_assignment_id::text,r.reviewer_user_id::text,
            r.classifier_version,r.priority_band,r.priority_score::text,
            r.requested_at::text,r.reviewed_at::text,v_latency::text,
            r.source_priority_sha256,r.source_review_sha256
          ),
          'UTF8'
        ),
        'sha256'
      ),
      'hex'
    );

    insert into public.gold_review_response_latency_events(
      review_event_id,review_request_id,priority_assignment_id,reviewer_user_id,
      classifier_version,priority_band,priority_score,requested_at,reviewed_at,
      response_latency_seconds,source_priority_sha256,source_review_sha256,payload_sha256
    ) values (
      r.review_event_id,r.review_request_id,r.priority_assignment_id,r.reviewer_user_id,
      r.classifier_version,r.priority_band,r.priority_score,r.requested_at,r.reviewed_at,
      v_latency,r.source_priority_sha256,r.source_review_sha256,v_sha
    )
    on conflict(review_event_id) do nothing;

    if found then v_inserted:=v_inserted+1; end if;
  end loop;

  return jsonb_build_object(
    'ok',true,'version','v131-review-response-latency-refresh-v1',
    'inserted',v_inserted,
    'latency_events',(
      select count(*) from public.gold_review_response_latency_events
      where classifier_version='v125.3-event-aware-v2'
    ),
    'automatic_execution',false,'automatic_promotion',false,
    'capital_permission','0R','checked_at',now()
  );
end;
$$;

revoke all on function public.refresh_v131_gold_review_response_latency()
from public, anon, authenticated;
grant execute on function public.refresh_v131_gold_review_response_latency()
to service_role;

do $$
begin
  if not exists (
    select 1 from cron.job where jobname='tfa-v131-gold-review-response-latency'
  ) then
    perform cron.schedule(
      'tfa-v131-gold-review-response-latency',
      '*/2 * * * *',
      'select public.refresh_v131_gold_review_response_latency();'
    );
  end if;
end $$;
