-- V128 Human x Machine Disagreement Intelligence
-- Compare explicit human agreement/disagreement with future endpoint evidence.
-- No human or machine override, no automatic weighting/promotion/orders, capital remains 0R.

create table if not exists public.gold_human_machine_disagreement_events (
  id bigint generated by default as identity primary key,
  review_outcome_id bigint not null references public.gold_human_review_outcomes(id),
  review_event_id bigint not null references public.gold_human_review_events(id),
  review_request_id bigint not null references public.gold_trigger_review_requests(id),
  reviewer_user_id uuid not null,
  classifier_version text not null,
  horizon_minutes integer not null,
  decision text not null,
  signal_key text not null,
  direction text not null,
  human_stance text not null,
  machine_endpoint_state text not null,
  human_endpoint_state text not null,
  comparison_state text not null,
  human_advantage_score integer,
  source_outcome_sha256 text not null,
  payload_sha256 text not null,
  created_at timestamptz not null default now(),
  unique(review_outcome_id)
);

alter table public.gold_human_machine_disagreement_events enable row level security;
revoke all privileges on table public.gold_human_machine_disagreement_events from public, anon, authenticated;
grant select, insert on table public.gold_human_machine_disagreement_events to service_role;
grant usage, select on sequence public.gold_human_machine_disagreement_events_id_seq to service_role;

create index if not exists gold_hm_disagreement_reviewer_idx
  on public.gold_human_machine_disagreement_events(reviewer_user_id,horizon_minutes,created_at desc);
create index if not exists gold_hm_disagreement_request_idx
  on public.gold_human_machine_disagreement_events(review_request_id);
create index if not exists gold_hm_disagreement_review_event_idx
  on public.gold_human_machine_disagreement_events(review_event_id,horizon_minutes);

drop trigger if exists prevent_v128_hm_disagreement_update_delete
  on public.gold_human_machine_disagreement_events;
create trigger prevent_v128_hm_disagreement_update_delete
before update or delete on public.gold_human_machine_disagreement_events
for each row execute function public.prevent_v125_gold_learning_mutation();

create or replace function public.refresh_v128_gold_disagreement_intelligence()
returns jsonb
language plpgsql
set search_path to 'public','extensions','pg_temp'
as $$
declare
  o record;
  v_stance text;
  v_comparison text;
  v_advantage integer;
  v_sha text;
  v_inserted integer := 0;
begin
  perform public.refresh_v127_gold_review_intelligence();

  for o in
    select *
    from public.gold_human_review_outcomes x
    where x.classifier_version='v125.3-event-aware-v2'
      and not exists (
        select 1
        from public.gold_human_machine_disagreement_events d
        where d.review_outcome_id=x.id
      )
    order by x.id
  loop
    v_stance:=case
      when o.decision='EVIDENCE_SUPPORTIVE' then 'AGREE_WITH_MACHINE'
      when o.decision='EVIDENCE_CONTRADICTORY' then 'DISAGREE_WITH_MACHINE'
      when o.decision='EVIDENCE_INCONCLUSIVE' then 'INCONCLUSIVE'
      when o.decision='DEFERRED' then 'DEFERRED'
      else 'UNCLASSIFIED'
    end;

    v_comparison:=case
      when v_stance='AGREE_WITH_MACHINE' and o.baseline_signal_state='FAVORABLE_ENDPOINT'
        then 'AGREEMENT_ALIGNED_WITH_ENDPOINT'
      when v_stance='AGREE_WITH_MACHINE' and o.baseline_signal_state='ADVERSE_ENDPOINT'
        then 'AGREEMENT_CONTRADICTED_BY_ENDPOINT'
      when v_stance='AGREE_WITH_MACHINE'
        then 'AGREEMENT_NEUTRAL_ENDPOINT'
      when v_stance='DISAGREE_WITH_MACHINE' and o.baseline_signal_state='ADVERSE_ENDPOINT'
        then 'DISAGREEMENT_HUMAN_ALIGNED'
      when v_stance='DISAGREE_WITH_MACHINE' and o.baseline_signal_state='FAVORABLE_ENDPOINT'
        then 'DISAGREEMENT_MACHINE_ALIGNED'
      when v_stance='DISAGREE_WITH_MACHINE'
        then 'DISAGREEMENT_NEUTRAL_ENDPOINT'
      else 'NON_DIRECTIONAL_HUMAN_REVIEW'
    end;

    v_advantage:=case
      when v_comparison='DISAGREEMENT_HUMAN_ALIGNED' then 1
      when v_comparison='DISAGREEMENT_MACHINE_ALIGNED' then -1
      else null
    end;

    v_sha:=encode(
      extensions.digest(
        convert_to(
          concat_ws('|',
            o.id::text,o.review_event_id::text,o.review_request_id::text,
            o.reviewer_user_id::text,o.classifier_version,o.horizon_minutes::text,
            o.decision,o.signal_key,o.direction,v_stance,o.baseline_signal_state,
            o.human_alignment_state,v_comparison,coalesce(v_advantage::text,''),
            o.outcome_sha256
          ),
          'UTF8'
        ),
        'sha256'
      ),
      'hex'
    );

    insert into public.gold_human_machine_disagreement_events(
      review_outcome_id,review_event_id,review_request_id,reviewer_user_id,
      classifier_version,horizon_minutes,decision,signal_key,direction,
      human_stance,machine_endpoint_state,human_endpoint_state,
      comparison_state,human_advantage_score,source_outcome_sha256,payload_sha256
    ) values (
      o.id,o.review_event_id,o.review_request_id,o.reviewer_user_id,
      o.classifier_version,o.horizon_minutes,o.decision,o.signal_key,o.direction,
      v_stance,o.baseline_signal_state,o.human_alignment_state,
      v_comparison,v_advantage,o.outcome_sha256,v_sha
    )
    on conflict(review_outcome_id) do nothing;

    if found then v_inserted:=v_inserted+1; end if;
  end loop;

  return jsonb_build_object(
    'ok',true,
    'version','v128-human-machine-disagreement-refresh-v1',
    'inserted',v_inserted,
    'human_review_events',(
      select count(*) from public.gold_human_review_events
      where event_type='HUMAN_EVIDENCE_REVIEW'
        and classifier_version='v125.3-event-aware-v2'
    ),
    'review_outcomes',(select count(*) from public.gold_human_review_outcomes),
    'disagreement_events',(select count(*) from public.gold_human_machine_disagreement_events),
    'scorable_disagreements',(
      select count(*) from public.gold_human_machine_disagreement_events
      where human_advantage_score is not null
    ),
    'automatic_human_override',false,
    'automatic_machine_override',false,
    'automatic_weighting',false,
    'automatic_promotion',false,
    'capital_permission','0R',
    'checked_at',now()
  );
end;
$$;

revoke all on function public.refresh_v128_gold_disagreement_intelligence() from public, anon, authenticated;
grant execute on function public.refresh_v128_gold_disagreement_intelligence() to service_role;

do $$
begin
  if not exists (
    select 1 from cron.job where jobname='tfa-v128-gold-disagreement-intelligence'
  ) then
    perform cron.schedule(
      'tfa-v128-gold-disagreement-intelligence',
      '*/2 * * * *',
      'select public.refresh_v128_gold_disagreement_intelligence();'
    );
  end if;
end $$;
